### ISSUE TITLE
Stable/Prometheus Doesnt allow Exec on the Pod

### ISSUE THREAD

**Issue by saurabh1git** [helm/charts#10098]
**Is this a request for help?**:
Yes

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
feature Request
If this is a BUG REPORT, please:
No
If this is a FEATURE REQUEST, please:
we are looking to get into the prometheus Server pod to have a look at the metrics being collected.

**Version of Helm and Kubernetes**:
helm: 2.9.1
k8s: 1.9.10

**Which chart**:
Prometheus

**What you expected to happen**:
Able to get onto command prompt

**How to reproduce it** (as minimally and precisely as possible):
Just try to get into pod using Exec

**Comment by carroarmato0** [comment]
The issue is that an upstream image of Prometheus is being used: prom/prometheus
That container image doesn't contain /bin/bash, which is what Kube defaults to use to exec into the running container.

As a workaround you can use kubectl and use /bin/sh, which works.

Example:   kubectl exec -it <prometheus pod name> -- /bin/sh

**Comment by carroarmato0** [comment]
The issue appears too if you try exec'ing into the pod through the Kubernetes Dashboard.
Normally the Dashboard defaults to executing /bin/bash, and if that fails, tries /bin/sh, but for some reason that seems to not work either.

**Comment by carroarmato0** [comment]
Also keep in mind that a pod can run multiple containers, so it's not enough to specify the pod, but also the specific container name with -c

kubectl exec --namespace default -it <pod name> -c <container name> -- /bin/sh
