### ISSUE TITLE
how to set [stable/percona-xtradb-cluster] use hostpath volume

### ISSUE THREAD

**Issue by lanyangkj** [helm/charts#10246]
As we all know, under the business scenario of large data volume, the read and write performance of local disk is superior to that of network Shared disk, so how to set [stable/percona-xtradb-cluster] to use hostpath instead of PVC?

thanks!!

**Comment by ap1969** [comment]
Hi @lanyangkj 
Did you ever find a solution for this? I'm been playing with Bitnami's master/slave helm chart, and I had to install the chart, then patch the pods to map the standard bitnami mysql data directory on the container, to the host path.

This worked, but i just kept hitting problems with the master/slave not syncing properly, I think because I was creating/destroying dev environments often.

So I thought I'd try Percona cluster, and encountered the same problem as you - I can only think of patching again as the solution to this.
