### ISSUE TITLE
[stable/gocd] GoCD Ingress default template

### ISSUE THREAD

**Issue by colachg** [helm/charts#10750]
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

FEATURE REQUEST  

**Version of Helm and Kubernetes**:

helm v2.12.1
kubernetes v1.12.4

**Which chart**:

stable/gocd

**Anything else we need to know**:

In file "gocd/templates/ingress.yaml":
I would like to change `spec`
from

```
  backend:
    serviceName: {{ template "gocd.fullname" . }}-server
    servicePort: {{ .Values.server.service.httpPort }}
  rules:
    {{- range $host := .Values.server.ingress.hosts }}
    - host: {{ $host }}
    {{- end -}}
  {{- if .Values.server.ingress.tls }}
  tls:
{{ toYaml .Values.server.ingress.tls | indent 4 }}
  {{- end -}}
{{- end -}}
{{- end -}}

```
to

```
  rules:
    {{- range $host := .Values.server.ingress.hosts }}
    - host: {{ $host }}
      http:
        paths:
        - path: /
          backend:
            serviceName: {{ template "gocd.fullname" . }}-server
            servicePort: {{ .Values.server.service.httpPort }}
    {{- end -}}
  {{- if .Values.server.ingress.tls }}
  tls:
{{ toYaml .Values.server.ingress.tls | indent 4 }}
  {{- end -}}
{{- end -}}
{{- end -}}
```

Because when I use the default ingress config I can not access gocd by the hostname that I defined in `values.yaml`.   
I deploy  gocd behind traefik.
Here is the error log: `"level":"warning","msg":"Error in ingress: HTTP is nil"`

@varshavaradarajan Could you check this? Thanks.

**Comment by varshavaradarajan** [comment]
@colachg - I believe its a bug in traefik which does not allow default backends in ingress. See https://github.com/containous/traefik/issues/1073 and https://github.com/containous/traefik/issues/1051. What you suggest works except for 

```
serviceName: {{ template "gocd.fullname" . }}-server
servicePort: {{ .Values.server.service.httpPort }}
```
So because you are in a range block, `.` no longer refers to the top level scope. You should store the context of `.` before beginning rules by doing 

```
{{ $dot := .}}
 and using that in the backend:
serviceName: {{ template "gocd.fullname" $dot }}-server
servicePort: {{ $dot.Values.server.service.httpPort }}

```

I have been unable to verify the fix though. Not sure if its because I am using minikube. Here's what I did: 
```
minikube stop; minikube delete; minikube start --bootstrapper kubeadm --memory 4096; minikube addons enable ingress; helm init

helm install stable/traefik (tried both with LoadBalancer and NodePort svc types)
kubectl apply -f https://raw.githubusercontent.com/containous/traefik/master/examples/k8s/ui.yaml

Changed ingress annotations in gocd/values.yaml to kubernetes.io/ingress.class: traefik
Added host test.go.cd in gocd/values.yaml for ingress and added <minikube ip> test.go.cd to /etc/hosts

helm install stable/gocd
```

Let me know if I am missing something. 

The proposed fix to make ingress work with `traefik` does not affect anything when used with the default ingress controller that comes with minikube, which is `nginx`. 

/cc @arvindsv , @GaneshSPatil

**Comment by colachg** [comment]
@varshavaradarajan Thanks for your time. I also think it's a bug in `traefik`.  My proposal can be compatible with traefik so could we use this before traefik works(or regardless of traefik)?

**Comment by varshavaradarajan** [comment]
@colachg - which version of traefik did you try it with? I used the helm chart, which had the app version 1.7.6 which is supposed to contain the fix for default backends. But, as I said, been unable to do so on minikube. It just brings up the page with `default backend - 404`.

**Comment by colachg** [comment]
@varshavaradarajan  em... Did you change your hosts file to make the host in ingress point to `minikube ip`:)?

**Comment by varshavaradarajan** [comment]
@colachg - yes. Here's what my hosts file has: 

```
127.0.0.1	localhost
255.255.255.255	broadcasthost
::1             localhost
192.168.99.100  test.go.cd
192.168.99.100 traefik-ui.minikube
```

**Comment by colachg** [comment]
@varshavaradarajan  Haha, thanks for your quick respose. Do you have some IM channels(like discord or slack)? we can talk immediately there.

**Comment by varshavaradarajan** [comment]
@colachg - mind using gitter? Join https://gitter.im/gocd/gocd and DM me?

**Comment by varshavaradarajan** [comment]
Update: The proposed fix works with traefik.

The error `default http backend - 404` was coming from the default nginx ingress controller. Ideally, this should not have happened, as the annotation `kubernetes.io/ingress.class` was set to `traefik`.  But as indicated in https://github.com/containous/traefik/issues/2633#issuecomment-354549234, the ingress.class annotation is not respected in minikube. The fix was working for @colachg because the minikube setup specifically involved `minikube addons disable ingress`, which terminated the nginx ingress controller. 

@colachg - can you please submit a PR so that this can be verified with GKE? 

I think that this issue should be fixed as it does not affect the way requests are handled when used with nginx or gce ingress controllers and allows for gocd to work with `traefik`, another ingress controller till traefik can support single service ingress properly.
