### ISSUE TITLE
[stable/efs-provisioner] storageclass template regression

### ISSUE THREAD

**Issue by grischa** [helm/charts#10936]
**Is this a request for help?**: no

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Helm and Kubernetes**: 
$ helm version
Client: &version.Version{SemVer:"v2.12.3", GitCommit:"eecf22f77df5f65c823aacd2dbd30ae6c65f186e", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.3", GitCommit:"eecf22f77df5f65c823aacd2dbd30ae6c65f186e", GitTreeState:"clean"}

K8s 1.11

**Which chart**: stable/efs-provisioner

**What happened**: template error when storageclass is set to default

**What you expected to happen**:
no error

**How to reproduce it** (as minimally and precisely as possible):
set `storageClass.isDefault` to true and do not provide annotations

**Anything else we need to know**:
Explained here https://github.com/helm/charts/pull/10829/files#r251376176

**Comment by stormmore** [comment]
I added the following to my ovverride values.yaml to get it working:
```
# HACK: workaround for https://github.com/helm/charts/issues/10936
annotations:
  storageclass.beta.kubernetes.io/is-default-class: "true"
```
Otherwise I would get errors deploying it. It is worth noting that the gp2 original default storageclass has both annotations - `storageclass.kubernetes.io` amd `storage.beta.kubernetes.io` in my `kops` deployed cluster. I, however, did try a "made up" annotation too which didn't work out so well but this one works perfectly.
