### ISSUE TITLE
[incubator/vault] Readiness and Liveness Probe Failed leading to CrashLoopBackOff

### ISSUE THREAD

**Issue by julekrut** [helm/charts#11067]
**Is this a request for help?**: No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Helm and Kubernetes**:
Helm: v2.12.3
K8s: v1.11.6

**Which chart**:
incubator/vault

**What happened**:
Liveness probe failed
Readiness probe failed

**What you expected to happen**:
Vault pods up and running

**How to reproduce it** (as minimally and precisely as possible):
I follow the incubator/vault manual

> helm repo add incubator http://storage.googleapis.com/kubernetes-charts-incubator

> helm install incubator/vault --set vault.dev=false --set vault.config.storage.consul.address="myconsul-svc-name:8500",vault.config.storage.consul.path="vault"

**Anything else we need to know**:
None

**Comment by edwardbartholomew** [comment]
@julekrut I received same error you did when trying this chart and then noticed below in README:
```
Please note that a backend service for Vault (for example, Consul) must be deployed beforehand and configured with the `vault.config` option.
```

Do you already have consul deployed [as myconsul-svc-name], otherwise you need to use helm to deploy consul before deploying Vault chart.

I used https://github.com/hashicorp/consul-helm to deploy Consul and then substituted resulting service (ie, running-hummingbird-consul-server:8500) for the vault.config.storage.consul.address parameter.

**Comment by kilhage** [comment]
I have the same issue, I tried to use the mysql and consul backend...

**Comment by edwardbartholomew** [comment]
Does `kubectl logs <pod>` reveal the error message? I've been using both HashiCorp's official chart (https://github.com/hashicorp/consul-helm) and this repo's stable/consul without issue with incubator/vault on GKE.

**Comment by kilhage** [comment]
I finally found my issue. I had to set `hostNetwork: true` under `spec.template.spec` in `deployment.yml` in order for the dns lookup to work properly when using the mysql storage.

This may also be the case for S3 and all other storage backends that are using external services.

Consul was not working since I didn't manage to get consul up and running properly due to network configuration issues in AWS.

When using AWS and `service.type=LoadBalancer` and a SSL certificate I have to change `spec.ports.name`: https in `service.yml`, otherwise HTTPS will not work properly.

**Comment by mkozjak** [comment]
Related to #9462.

**Comment by zdevi** [comment]
Hello, this issue is very anoying, is it going to be be merged anytime soon ?

**Comment by imorti** [comment]
I'm getting this even on Minikube.

**Comment by imorti** [comment]
Readiness probe failed: Key Value --- ----- Seal Type shamir Initialized false Sealed true Total Shares 0 Threshold 0 Unseal Progress 0/0 Unseal Nonce n/a Version n/a HA Enabled false
kubelet minikube
spec.containers{vault}
297
Successfully assigned default/vault-helm-0 to minikube
default-scheduler
-
0
Container image "vault:1.2.4" already present on machine
kubelet minikube
spec.containers{vault}
1
