### ISSUE TITLE
Airflow Scheduler goes into CrashLoopBackoff due to schedulerNumRuns

### ISSUE THREAD

**Issue by yardik** [helm/charts#11198]
**Is this a request for help?**:
Yes
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Helm and Kubernetes**:
Helm v2.12.1
Kube v1.12

**Which chart**:
stable/airflow

**What happened**:
if schedulerNumRuns: 10 is set, the container will go into CrashLoopBackoff after a few restarts of the scheduler.

**What you expected to happen**:
The container exists gracefully and kubernetes continues to restart it gracefully

**How to reproduce it** (as minimally and precisely as possible):
helm install with --set schedulerNumRuns=10

**Anything else we need to know**:
Happy to do a PR for possible solutions. Might need to add a loop to deployments-scheduler.yaml which constantly restarts scheduler without relying on kube to do so? Is this chart working without this problem for anyone?

**Comment by ckannon** [comment]
@gsemet do you see this bug in your usage of this chart? Seems to be consistently repeatable if scheduler runs is set to 10 (or less)

**Comment by ckannon** [comment]
For the number of failures, it's all based on how long the container stays up - if your scheduler restarts in < 10 minutes crashloopbackoff should start happening. Kubernetes resets CrashLoopBackoff after 10 minutes of uptime. I think the schedulerNumRuns would need to be 100 or so before we hit that 10 minute mark, or 0 (never restart). I've never understood why the restarts either!

The fix feels like a hack.. but simply wrapping the airflow scheduler start line in a loop with check for 
exit code solves the problem and takes a lot of the load off the kube cluster because the container stays up until the scheduler crashes for real. I'll PR it later today..

**Comment by gsemet** [comment]
I am ok if you find a proper solution. There is a PR going on that may be merged today, you may want to rebase it when it is merged. You can increase the smallest version number (0.16.1 I guess)

**Comment by gsemet** [comment]
For your info, 0.17.0 is merged ;)
