### ISSUE TITLE
Helm install with persistant volumes True

### ISSUE THREAD

**Issue by dimthe** [helm/charts#1137]
hello

i have 3 nfs shares and i would like to use those for persistent volume storage. They are called /var/db0 , var/db1 and /var/db2
there is a file values.yaml but i dont see where i need to enter my nfs shares.
i am installing from here : https://kubeapps.com/charts/stable/mongodb-replicaset

thank you

**Comment by lachie83** [comment]
@foxish Can you provide some details on the best way to handle this?

**Comment by dimthe** [comment]
@foxish @lachie83 to make this more clear 
if i install the helm chart with persistanvolumes false everything is fine.  I have created 3 nfs shares so i can use persistenvolumes true but where do i enter my nfs shares in the values.yaml and in what syntax ? thanks

**Comment by foxish** [comment]
I think one way to do this may be to setup a [storage provisioner](https://github.com/kubernetes-incubator/external-storage) and storage class which lets you consume the volume. In this case, if you want to use those specific shares that you created (instead of having them dynamically provisioned in the manner mentioned), you'd need to create the PVCs and PVs manually for the StatefulSet to consume. The PVC names will be the same as each individual statefulset pod's name.

Let me know if you need more details about the above steps.

**Comment by dimthe** [comment]
hello 
i have created 3 PVs and added them via kubectl create -f . please see the logs below and tell me what am i missing ? 

i dont really have to use the shares i created just whatever is easier :)

some logs here
https://pastebin.com/Q3vdkWxC

**Comment by foxish** [comment]
Since you're not using a dynamic provisioner for NFS, you'd also need to create the [PVCs](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#persistentvolumeclaims) manually before deploying the helm chart. The result should be that the PVCs say that they are bound to your created PVs, in place of `Pending` as they do now.

**Comment by dimthe** [comment]
ok so i can delete everything and start over

first i will have to create the 3 above PVs like i previously did  ( do filenames matter? )
secondly i will install the chart 

is this enough ?

**Comment by foxish** [comment]
You'd need to create 3 PVs, and 3 PVCs; (only the PVC names matter, and must be in the format that the StatefulSet expects, i.e. `datadir-dimi-mongodb-replicaset-0` in your example). `kubectl get pvc` must report them as being `Bound` before proceeding. Following that, you can create the helm chart.

**Comment by foxish** [comment]
Of course, if you're doing this often, I highly recommend installing a dynamic provisioner for your cluster which should automate this entire process and then the chart will work as it is.

**Comment by dimthe** [comment]
hello @foxish 
so i have 3 pv and 3 pvc , please see this 

kubectl get pv
NAME      CAPACITY   ACCESSMODES   RECLAIMPOLICY   STATUS    CLAIM                                     REASON    AGE
pv00      5Gi        RWO           Retain          Bound     default/datadir-dt-mongodb-replicaset-1             12m
pv01      5Gi        RWO           Retain          Bound     default/datadir-dt-mongodb-replicaset-2             12m
pv02      5Gi        RWO           Retain          Bound     default/datadir-dt-mongodb-replicaset-0             12m
[root@atomic01 auvious]# kubectl get pvc
NAME                              STATUS    VOLUME    CAPACITY   ACCESSMODES   AGE
datadir-dt-mongodb-replicaset-0   Bound     pv02      5Gi        RWO           12m
datadir-dt-mongodb-replicaset-1   Bound     pv00      5Gi        RWO           12m
datadir-dt-mongodb-replicaset-2   Bound     pv01      5Gi        RWO           12m
[root@atomic01 auvious]# 






if i run the helm chart now it waits for ever to complete the first pod and i have to ctrl c 

what am i doing wrong  ?

**Comment by crimsonfaith91** [comment]
@dimthe Do you mind to post the logs for the first pod? 
`kubectl describe pod <pod-name>`
