### ISSUE TITLE
Gitlab Official Chart

### ISSUE THREAD

**Issue by kwent** [helm/charts#1138]
## Gitlab Official Charts

Gitlab just released their official [charts](https://gitlab.com/charts/charts.gitlab.io/tree/master/charts/gitlab), might be worth is to deprecate or mention it for:

- https://github.com/kubernetes/charts/tree/master/stable/gitlab-ce
- https://github.com/kubernetes/charts/tree/master/stable/gitlab-ee

Regards,

**Comment by rimusz** [comment]
maybe to contact Gitlab guys and ask to publish the new charts here?

**Comment by twk3** [comment]
Some discussion on this has gone on here: https://github.com/kubernetes/charts/pull/608#issuecomment-304136866

and here: https://gitlab.com/charts/charts.gitlab.io/issues/10#note_29333155

Instead of a gitlab-ce and gitlab-ee chart, we have a gitlab chart that can be used for either. Our chart is a renamed iteration of the gitlab-ce chart from this repo.

We want to be able to iterate faster on our charts than the review process here in this repo, but we also value the review feedback we get here.

We do plan to keep our own repo, and continue iterating and officially supporting the charts there. But are open to suggestions on how to deal with the charts in this repo.

**Comment by viglesiasce** [comment]
We are going to be looking at how to delegate the responsibility of these charts in the near future. If you have ideas on how you'd like to see this work please let us know.

**Comment by lambertjosh** [comment]
@viglesiasce our general plan would be to deprecate the existing charts here in this repo, and then introduce the officially supported charts, [`gitlab-omnibus`](http://docs.gitlab.com/ce/install/kubernetes/gitlab_omnibus.html) and [`gitlab-runner`](http://docs.gitlab.com/ce/install/kubernetes/gitlab_runner_chart.html). These chart names would also handily avoid name conflicts. We really appreciate all of the work done here on these charts by the community.

If there is some way for a set of authorized GitLab maintainers to more quickly update these here either manually or via CI that would be very helpful. Right now we are actively improving our charts, so we tend to push updates relatively frequently. 

Perhaps a bot could auto-approve PR's from a company's maintainers, or instead automatically sync with an upstream repo periodically?
