### ISSUE TITLE
[Atlantis] ATLANTIS_ATLANTIS_URL does not set https when TLS enabled

### ISSUE THREAD

**Issue by leowmjw** [helm/charts#11431]
**Is this a request for help?**:
No
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):  BUG

**Version of Helm and Kubernetes**:
N/A

**Which chart**:
stable/atlantis

**What happened**:
For webhook, ATLANTIS_ATLANTIS_URL seems to hardcode the scheme to http
e.g
```
tlsSecretName: secrettls
...
- name: ATLANTIS_ATLANTIS_URL
   value: http://atlantis.example.io
```

**What you expected to happen**:
ATLANTIS_ATLANTIS_URL should have https when tls is enabled
e.g
```
tlsSecretName: secrettls
...
- name: ATLANTIS_ATLANTIS_URL
   value: https://atlantis.example.io
```

**How to reproduce it** (as minimally and precisely as possible):
Set tls; run helm with --debug and --dry-run

**Anything else we need to know**:

**Comment by lkysow** [comment]
@leowmjw sorry I'm just seeing this now. It's probably better to open up issues in the Atlantis repo: https://github.com/runatlantis/atlantis

To answer your question, if you're manually setting `ATLANTIS_ATLANTIS_URL` then I think it makes sense for Atlantis to just use what you've set. Maybe you have a reason for setting `http` even though you have the ssl config set up. Since the user actually has to enter in their URL then I think it's fair to expect them to enter in `https://` instead of `http://`.

If you're not setting that variable, then Atlantis defaults to `http://$(hostname)` so in this case I think it's fair to detect that you've set the ssl config and default to `https://$(hostname)` instead.
