### ISSUE TITLE
[stable/concourse] Bump postgresql dependency

### ISSUE THREAD

**Issue by cirocosta** [helm/charts#11610]
There's been quite a while since the last time we bumped the `PostgreSQL` dependency:

https://github.com/helm/charts/blob/e62284c1e5db576530f6ea74dc1705449acc0176/stable/concourse/requirements.yaml#L1-L5

https://github.com/helm/charts/blob/e62284c1e5db576530f6ea74dc1705449acc0176/stable/postgresql/Chart.yaml#L1-L3

As part of the PR to address this, it'd be good to verify whether there are any breaking changes that we should be aware of beforehand.

On the `concourse` side, I'm sure that the 4.x and 5.x series is perfectly compatible with Postgres 11.1 and 9.6.x (as it's the former is the version we use in our own testing of Concourse and the later we use for another internal deployment), so compatibility in these terms should not be an issues.

Eventually, in a near future, we could have a pipeline that continuously tests these bumps as well 🤔

**Acceptance criteria**

- having a PR in this repository that bumps the version, and
- a test in k8s/topgun that verifies that Concourse still communicates with the database.

Thanks!

**Comment by cirocosta** [comment]
As part of https://github.com/concourse/concourse/issues/3106, the Concourse team will be testing the compatibility with it 👍

Once we conclude whether there are changes, we can then follow up with a PR here 😁

**Comment by cirocosta** [comment]
🙌

**Comment by cirocosta** [comment]
🙌

**Comment by cirocosta** [comment]
Hi,

I just created https://github.com/helm/charts/pull/14945 where I upgrade the version of the subchart to 5.3.8 (from 0.13.1!!!).

I'm still running the e2e test suite (https://github.com/concourse/concourse/tree/27097c93f25e84cd3f346f81d8013b550ca01a93/topgun/k8s), but so far, seems all right 😁  

Thanks!

**Comment by M0nsieurChat** [comment]
Hello there :)

I don't know if this is because of our setup or something but yesterday while upgrading the Helm release of stable/concourse (adding an annotation on the ingress), we ended up with an empty postgresql.

Post-mortem : the new way of deploying postgres uses another PVC naming convention / creation scheme.

- The old PVC name was : concourse-postgresql 
- The new PVC name after the upgrade was : data-concourse-postgresql-0 
 
So Helm deleted the old PVC (ewww... :) ) and created a new empty one.

Thanksfully, we were able to restore the PVC from a few hours ago with Velero. We then added updated values.yaml with postgresql.persistence.existingClaim=concourse-postgresql

So looking at the PVC names, it appears postgres was deployed using a deployment pre-upgrade and switched to a statefulset with a volumeClaimTemplate post-upgrade.

Cheers,

**Comment by cirocosta** [comment]
woooooow damn! I'm sorry to hear that it caused trouble for you! thanks for sharing though!

I'm wondering whether this instruction should be part of the `CHANGELOG` then to make clear that folks should be very careful about it - wdyt?

Thanks!

**Comment by YoussB** [comment]
wondering if we should add a sort of upgrade testing to mitigate such problems 🤔

**Comment by databus23** [comment]
Not of much help but I need to vent here that we also lost our production concourse database because of this change. I made a complete fool of myself in front of the whole team not having a backup ready...
