### ISSUE TITLE
[stable/prometheus] pathPrefix is not populated in prometheus server html template for static assets

### ISSUE THREAD

**Issue by cortopy** [helm/charts#11708]
**Is this a request for help?**:
No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Not sure

**Version of Helm and Kubernetes**:
v2.12.3 and 1.11.0

**Which chart**:
prometheus

**What happened**:
`pathPrefix` variable in the base [html template](https://github.com/prometheus/prometheus/blob/master/web/ui/templates/_base.html) is not populated, and so static files (js files, css, etc.) are not referenced correctly

**What you expected to happen**:
`pathPrefix` to be populated with the `prefixURL` value

**How to reproduce it** (as minimally and precisely as possible):
Set `prefixURL: "/prometheus"` and include `web.route-prefix: "/prometheus"` in `extraArgs`. 

**Anything else we need to know**:
This behaviour only applies to the prometheus server. Alert manager has static files html paths updated correctly using `prefixUrl`

Even though the [html template in the server](https://github.com/prometheus/prometheus/blob/master/web/ui/templates/_base.html) has a `pathPrefix` value, this is set to an empty string.

Resources like `/static/vendor/js/jquery.min.js?v=62e591f928ddf6b3468308b7ac1de1c63aa7fcf3` are available using the prefix `\prometheus` but the html doesn't add this path

**Comment by Persi** [comment]
Using the parameter server.prefixURL as well as alertmanager.prefixURL causes my Deployments to fail, because of the readinessprobe returning HTTP 404.

Seems like this issue is still a relevant bug.

My configuration looks as follows:
`alertmanager:
  persistentVolume:
    storageClass: local-storage
  # Path wird aktuell vom Helm Chart bei der Erzeugung des Ingress ignoriert!
  prefixURL: /alert
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: traefik
      traefik.frontend.rule.type: PathPrefix
    hosts:
      - MYHOST
    tls: []

server:
  persistentVolume:
    storageClass: local-storage
  # Path wird aktuell vom Helm Chart bei der Erzeugung des Ingress ignoriert!
  prefixURL: /prometheus
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: traefik
      traefik.frontend.rule.type: PathPrefix
    hosts:
      - MYHOST
    tls: []`

For the traefik ingress being able to work i would normally need to configure a path, otherwise both ingresses listen for the context root. I fixed this locally by setting the path directly via kubectl, but my server still fail the readiness probe.
