### ISSUE TITLE
Documentation on running as non-root is inadequate

### ISSUE THREAD

**Issue by derrickburns** [helm/charts#11755]
**Is this a request for help?**:

Yes.

Your documentation on running as non-root is inadequate.  

How do you configure an ingress to use a non-privileged port?  How do you configure it on AWS?  What is the difference between servicePort and target port?  None of this is clear and leads to major confusion. HELP!

**Comment by vsliouniaev** [comment]
@derrickburns This repository is a collection of many charts, most of which are independently maintained by completely different people in their free time, so when you say "Your documentation" is there a specific chart that you are referring to?

There are a lot of open issues here and in order to make it easier for the right people to answer your question the template asks for information to help someone to answer your question so please take the time to fill it out that someone else trying to help would have to take in answering your question.

From the information you have provided in your issue, I don't know whether the information you're looking for is simply located in the kubernetes docs themselves or not.

**Comment by derrickburns** [comment]
Apologies. This is for ambassador.

**Comment by Flydiverny** [comment]
Not really sure what you actually need help with but here's some pointers.

The ambassador chart runs by default on a non-privileged port, if using all the [default values](https://github.com/helm/charts/blob/master/stable/ambassador/values.yaml). The ambassador chart doesn't use any ingress resource.

In regards to ambassador `service_port`, the chart by default sets this to `8080`, this specifies the port that ambassador will listen to.
For the traffic to actually hit this port you can set `http.targetPort` or `https.targetPort` to the same value.

Snippet from ambassador [docs](https://www.getambassador.io/reference/modules/#the-ambassador-module)
```
  # If present, service_port will be the port Ambassador listens
  # on for microservice access. If not present, Ambassador will
  # use 443 if TLS is configured, 80 otherwise. In future releases
  # of Ambassador, this will change to 8080 when we run Ambassador
  # as non-root by default.
  # service_port: 80
```

For kubernetes services port & targetPort see k8s [docs](https://kubernetes.io/docs/concepts/services-networking/service/)

> Note that a Service can map an incoming port to any targetPort. By default the targetPort will be set to the same value as the port field. Perhaps more interesting is that targetPort can be a string, referring to the name of a port in the backend Pods. The actual port number assigned to that name can be different in each backend Pod. This offers a lot of flexibility for deploying and evolving your Services. For example, you can change the port number that pods expose in the next version of your backend software, without breaking clients.

The ambassador helm chart lets you configure the service port and target ports like this:
```yaml
service:
  http:
    port: 80 // configures service to listen on port 80
    targetPort: 8080 // configures service to send traffic to pod(s) on port 8080
```

For hints about Ambassador and AWS there's also a [docs](https://www.getambassador.io/reference/ambassador-with-aws/#ambassador-on-aws) section :) its not updated for the latest helm chart but there's some hints. You'll probably want to use some of the annotations and config.
