### ISSUE TITLE
[stable/rabbitmq-ha] docker-entrypoint.sh: line 196: /var/lib/rabbitmq/.erlang.cookie: Permission denied

### ISSUE THREAD

**Issue by sigmascord** [helm/charts#12025]
**Is this a request for help?**:
NO
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Bug report

**Version of Helm and Kubernetes**:
Helm 2.12.3
Kubernetes 1.13.3 (on DigitalOcean)

**Which chart**:
stable/rabbitmq-ha

**What happened**:
When installing the chart and using a customized _values.yaml_ file with **persistentVolume** enabled, the first pod loops in in error without ever becoming ready and "Running". By checking the pod's logs one can see the following error:

> $ kubectl -n workspace logs -f rabbitmq-0
> /usr/local/bin/docker-entrypoint.sh: line 196: /var/lib/rabbitmq/.erlang.cookie: Permission denied

**What you expected to happen**:
To have the rabbitmq pods starting and running as usual.

**How to reproduce it** (as minimally and precisely as possible):
`helm install --namespace workspace --name rabbitmq -f rabbitmq-helm-config.yaml stable/rabbitmq-ha`

**Anything else we need to know**:
Our config file worked at the beginning of last week and the previous weeks, we notice that recently the rabbitmq and rabbitmq-ha added a _securityContext_ section that was non-existing a few days ago. Also, we are using this with DigitalOcean to provide dynamic provisioning with Persistent Volume Claims and someone pointed that this error manifests in the stable/rabbitmq for NFS file systems on _stable/rabbitmq_ in #11926

**Comment by steven-sheehy** [comment]
We have a few options to try. If you can try each of these fixes in turn to see which solves your problem:

1. Via helm set`securityContext.fsGroup=101`
2. `kubectl edit` the statefulset and add into the init container: `/bin/chown -R 100:101 /var/lib/rabbitmq`
3. Via helm set `securityContext=null`

The last one should definitely work since it's reverting to the previous functionality of running as root, but please try the others first so we can find a better approach.

**Comment by sigmascord** [comment]
@steven-sheehy Thanks, the 1st one worked immediately.

The new `securityContext.runAsGroup: 101` setting in #11863 doesn't seem to work as intended (at least for me in DigitalOcean), that config doesn't even show up in the pod's yaml config as soon as you install it, whereas _fsGroup_ shows up immediately.

When I execute the command below for both versions, that's what I get on the working and non-working YAML's securityContext sections:
`$ kubectl -n master get statefulset rabbitmq -o yaml `

*NOT WORKING*:
      securityContext:
        runAsNonRoot: true
        runAsUser: 100

*WORKING*:
      securityContext:
        fsGroup: 101
        runAsNonRoot: true
        runAsUser: 100

**Comment by steven-sheehy** [comment]
Thanks for verifying. `runAsGroup` and `fsGroup` have separate uses with the former being used for the process and the latter for the filesystem. `runAsGroup` is just not enabled by default in clusters and has to be enabled via the feature gate `RunAsGroup=true`. So sounds like we just need to add fsGroup: 101. Do you think you would be able to create a PR adding that one line and bump the bugfix version in the Chart.yaml?

**Comment by sigmascord** [comment]
@steven-sheehy Sure, I can do it, but do I need you or the team to give me privileges for that?

**Comment by steven-sheehy** [comment]
Nope, anyone can create PRs. I can approve PRs for this chart once you do. I can't however approve my own though, so your help would be appreciated. 👍

**Comment by asavtch** [comment]
How is fsGroup=101 supposed to universally resolve this issue? When I mount a persistent volume /var/lib/rabbitmq is mounted with root:root ownership and as the init container runs in the security context I can't chown the folder from there. Please could you explain how to get the root:101 permissons of /var/lib/rabbitmq in the first place in order to proceed with fsGroup=101.
