### ISSUE TITLE
[stable/logstash] Multiple Pipelines Definition in helm charts

### ISSUE THREAD

**Issue by TsofiaTsuriel1234** [helm/charts#12314]
**Is this a request for help?**:
YEP :)
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT - ???

**Version of Helm and Kubernetes**:
Helm version v2.11.0
Kubernetes server version v1.10.13

**Which chart**:
logstash

**What happened**:
Several pipelines defined in inputs, filters and outputs as described in values.yaml but in the logstash container itself, pipelines.yml is created only with "main" pipeline with 'path.config: "/usr/share/logstash/pipeline"',  ignoring custom pipeline definitions; pipelines input/filter/output files are created under "pipeline" directory as define in configMap: logstash/templates/pipeline-config.yaml

**What you expected to happen**:
config/pipelines.yml created with a list of pipelines

**How to reproduce it** (as minimally and precisely as possible):
Define several pipelines in input/filter/output in values.yaml and deploy

**Anything else we need to know**:
The guideline in the README: "To achieve multiple pipelines with this chart, current best practice is to maintain one pipeline per chart release. In this way configuration is simplified and pipelines are more isolated from one another." is really not clear because values.yaml gives the option to define several pipeline "keys"

**Comment by andreykaipov** [comment]
Hey @TsofiaTsuriel1234 - I'd like this feature too. Can you reopen the issue? 😄

One of the reasons Logstash introduced multiple pipelines in 6.x was to prevent running multiple instances of Logstash. The motivation behind that is very clear from the blog post announcing it https://www.elastic.co/blog/logstash-multiple-pipelines. Not supporting it in this chart feels like a mistake.

I've added support for multiple pipelines in my own fork of this chart, and am happy to submit a PR. It's a breaking change though since it removes the `inputs`, `filters`, and `outputs` values. Instead, I have `pipelines` and `pipelineSettings` values that are used as follows:

```
pipelineSettings:
  one:
    queue.type: persisted
  two:
    queue.type: persisted

pipelines:
  one: |
    input { tcp { port => 1514 } }
    output { stdout {} }
  two: |
    input { tcp { port => 1515 } }
    output { stdout {} }
```

Lemme know if you think this approach can be improved!

**Comment by kimxogus** [comment]
I like this feature too

**Comment by oliverbaehler** [comment]
Would like this implementation as @andreykaipov described it as well. Especially I see potential for the usage of the Logstash Pipeline Viewer (https://www.elastic.co/guide/en/logstash/6.7/logstash-pipeline-viewer.html). With the current approach you only have as overview the pipeline main. With each pipeline being seperated you would see dedicated metrics and have a better overview rather a general overview for just one pipeline. Is there any approach for the implementation of this feature?

**Comment by cc-stjm** [comment]
I like @andreykaipov 's approach above. You could avoid making it a breaking change by having a bool that toggles multiple pipeline support, and so switches between old and new way of doing it. (Means that templates are more complicated though)

**Comment by mrszop** [comment]
Any news on this issue?

**Comment by oliverbaehler** [comment]
Hi @andreykaipov 
I took a look at your forked chart and it seems that would do it for me. Maybe a little nicer hierarchie for the values would be something like this:

`pipelines:
  one:
    settings:
      queue.type: persisted
      ...
    config: |
      input { tcp { port => 1514 } }
      output { stdout {} }
  two:
    settings:
      queue.type: memory
      ...
    config: |
      input { tcp { port => 1515 } }
      output { stdout {} }`

We could simply take every element for `settings` for each child and just insert it to the pipelines.yml (`{{ toYaml $range.settings }}`). I could make a contribution to your fork, if you agree with such changes.

But I would prefer it, if we could bring these changes to this stable chart. Since It makes more sence to maintain the chart on the stable repo for everyone. Or am I wrong?

**Comment by oliverbaehler** [comment]
Hi @TsofiaTsuriel1234 
Are you interested in reopening this issue? Otherwise we should consider rising a new one.
