### ISSUE TITLE
[stable/rabbitmq] feature request: automatic configuration for schedulers threads using resources requests

### ISSUE THREAD

**Issue by thomas-riccardi** [helm/charts#13050]
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): feature request

**Which chart**:
`stable/rabbitmq`

**What happened**:
Since #13044 the schedulers threads are configurable from the chart values, with hardcoded default values.
The default value could be derived from the actual `resources.requests.cpu` (cf https://github.com/helm/charts/issues/3855#issuecomment-482161801).

Prior to #13044 the default values were computed by rabbitmq: derived from the actual core count; thus #13044 could introduce performance regression with default values.

**Comment by juan131** [comment]
Hi @thomas-riccardi 

As it was mentioned at #3855 there are two ways to automatically configure the scheduler threads:

- Helm templating
  - It's not trivial at all since it'll require to perform some parameters transformations to do the calculations. E.g. `resource.requests.cpu` can be `100m`, so it's necessary to transform that into a float.
- Using the Downward API

I'd rather use the second approach for simplicity. What do you think @thomas-riccardi @tompizmor ?

**Comment by thomas-riccardi** [comment]
Hi @juan141 

I'm not sure either.
pros:
- more flexibility in bash
cons:
- less code in the already large shell command may be better
- for `resource.requests.cpu` the only non number case is the milli `m` suffix: it could probably be handled in helm template (a possible rule is `resource.requests.cpu <= 1` => 1 core)

However, a followup issue would raise the same questions for `resource.limits.memory` (to properly auto-configure the memory alarm), and there the variety of units is much bigger.

=> maybe it's better to do it in bash (and maybe it should be moved to the bitnami image? (Since #4591 the bitnami init script is half bypassed, leading to all kinds of problems, but this is another issue...))

**Comment by thomas-riccardi** [comment]
bump to remove the `lifecycle/stale` label.

**Comment by juan131** [comment]
Hi @thomas-riccardi 

Good news! We already moved the RabbitMQ so it's based on Bash scripts. See:

https://github.com/bitnami/bitnami-docker-rabbitmq/tree/master/3.7/debian-9/rootfs

Now we need to decide wether we want to replace the current command and we use the logic available in the Bash container or not. As I mentioned on a previous comment, there'll be user that'll complain for this change since they're not using the Bitnami image.

As an alternative, we could create a parameter in the template to decide whether to use a custom command or not (relying on the container init scripts).
