### ISSUE TITLE
coredns target is down in prometheus 

### ISSUE THREAD

**Issue by vrathore18** [helm/charts#13055]
I have upgraded Prometheus-operator chart to .29. But ever since I am getting target down error on prometheus.

![image](https://user-images.githubusercontent.com/35921967/56134645-a512d800-5fac-11e9-8636-2c79c9a937ee.png)

When I edited the service

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: 2019-04-12T09:24:29Z
  labels:
    app: k8s-utils-prometheus-operator-coredns
    appname: k8s-utils-prometheus-operator
    chart: prometheus-operator-5.0.11
    component: k8-utils
    heritage: Tiller
    jobLabel: coredns
    release: k8s-utils-prometheus-operator-v1
    stage: dev
  name: k8s-utils-prometheus-op-coredns
  namespace: kube-system
  resourceVersion: "18998998"
  selfLink: /api/v1/namespaces/kube-system/services/pb-k8s-utils-prometheus-op-coredns
  uid: c5ebcbdb-5d04-11e9-ad54-12075a8e5e3c
spec:
  clusterIP: None
  ports:
  - name: http-metrics
    port: 9153
    protocol: TCP
    targetPort: 9153
  selector:
    k8s-app: kube-dns
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}

**Comment by vsliouniaev** [comment]
What is the version of the chart you upgrade from and to? .29. doesn't sound like a chart version

**Comment by vrathore18** [comment]
from  0.26.0 to 0.29.0

**Comment by vsliouniaev** [comment]
That's not a version of the prometheus-operator helm chart. That's a version of prometheus-operator.
What are the versions of the chart you are using?

**Comment by vrathore18** [comment]
$helm ls gives me this:
prometheus-operator-5.0.11              0.29.0

**Comment by vsliouniaev** [comment]
So you're on chart 5.0.11, what was the previous version of the chart that you upgraded from?

Regardless, the issue is that the target is discovered but it is refusing connections. 9153 is the correct port for coredns, but I cannot say why the endpoint is refusing connections. You can try to CURL it directly from within the cluster to diagnose the issue further, but this doesn't appear to be a prometheus operator helm chart issue.
