### ISSUE TITLE
[stable/drone] prometheus metrics not working

### ISSUE THREAD

**Issue by minhdanh** [helm/charts#13353]
**Is this a request for help?**: Yes

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Version of Helm and Kubernetes**:

Helm version:
```
Client: &version.Version{SemVer:"v2.13.0", GitCommit:"79d07943b03aea2b76c12644b4b54733bc5958d6", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.13.0", GitCommit:"79d07943b03aea2b76c12644b4b54733bc5958d6", GitTreeState:"clean"}
```

Kubernetes version:
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:53:57Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-01T20:00:57Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**: stable/drone

**What happened**:
Prometheus cannot scrape metrics of drone server:
```
Get http://10.233.126.90:8000/metrics: dial tcp 10.233.126.90:8000: connect: connection refused
```

**What you expected to happen**:
Prometheus can scrape drone server metrics

**How to reproduce it** (as minimally and precisely as possible):
Deploy stable/drone chart with `metrics.prometheus.enabled: true`

**Anything else we need to know**:

There're two thing here: first, the metrics port seems wrong. The correct port should be `80` instead of `8000`: https://github.com/helm/charts/blob/master/stable/drone/templates/deployment-server.yaml#L89

Second, metrics now requires authentication: https://docs.drone.io/administration/server/metrics/
So even the port is correct, Promtheus won't be able to scrape drone server's metrics.
At the moment Prometheus doesn't have an annotation to support an additional bearer token.

**Comment by minhdanh** [comment]
@christian-roggia @paulczar What do you think?

**Comment by runningman84** [comment]
According to this wiki
https://github.com/coreos/prometheus-operator/blob/master/Documentation/api.md#endpoint
You can configure a bearerTokenFile in order to access a protected resource. Unfortunatly I do not now where I would have to inject this kind of file in order to be able to use it.

**Comment by zgorizzo69** [comment]
@minhdanh  here is how I configured prometheus and drone to get prometheus scrape from the  `metrics` endpoint which is restricted and requires an authorization token.

1. create a user for prometheus
```
$ drone user add prometheus --machine 
Successfully added user prometheus
Generated account token e5a68397023c63792bbbd0b3d4918d46
```
2. create a secret with that token in the Prometheus namespace
`kubectl create secret generic drone-metrics --from-literal=token=e5a68397023c63792bbbd0b3d4918d46`

3. make sure that the drone server annotation point to the right port
 ```
             prometheus.io/port: 80
              prometheus.io/scrape: true
```
4. update prometheus helm chart to mount the secret
```
  server:
    extraSecretMounts:
    - name: drone-secret
      mountPath: /etc/prometheus/secrets/drone-metrics
      secretName: drone-metrics
      readOnly: true
```
5. update the prometheus configuration to add the bearer token for the kubernetes pod. _Which is not  ideal because it will add it to all the kubernetes POD_
```
kubectl edit cm prometheus-server
```
```  
data:
   ....
    - job_name: kubernetes-pods 
      bearer_token_file: /etc/prometheus/secrets/drone-metrics/token 
```
6. verify on the prometheus UI  http://localhost:9090/targets
http://10.244.3.38:80/metrics | **UP** | app="**drone**" component="server"|
