### ISSUE TITLE
[stable/prometheus-operator] better support for PriorityClass

### ISSUE THREAD

**Issue by dioguerra** [helm/charts#13411]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

 Would be nice to have a way to create a PriorityClass for the chart deployment and/or to create a ResourceQuota assigned to the namespace where the chart is going to be deployed.

This is important because of Pod priority and mitigate k8s engine to drop monitoring pods in favour of higher priority ones (when there are higher priority pods than the default value)

My planning was to use the default kubernetes system-cluster-critical but this cannot be used outside of the kube-system namespace. 

A MR is ongoing to solve this https://github.com/kubernetes/kubernetes/issues/76308

**Version of Helm and Kubernetes**:kubectl version
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:11:31Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.3", GitCommit:"435f92c719f279a3a67808c80521ea17d5715c66", GitTreeState:"clean", BuildDate:"2018-11-26T12:46:57Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
helm version
Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}

```

**Which chart**: stable/prometheus-operator

**How to reproduce it** (as minimally and precisely as possible):
values.yaml> http://paste.openstack.org/show/750115/
helm install stable/prometheus-operator --namespace monitoring --name prometheus-operator --version v5.3.0 --values values.yaml

**Comment by vsliouniaev** [comment]
I think the first option is viable, since it relates to the chart specifically. We should be able to provision a PriorityClass or use an existing one.

**Comment by Pluies** [comment]
Fo what it's worth, we ran into that issue specifically with the pods created by the `prometheus-node-exporter` DaemonSet, and it turns out that the [prometheus-node-exporter](https://github.com/helm/charts/tree/master/stable/prometheus-node-exporter) chart (imported through `requirements.yaml`) [already supports PriorityClassName](https://github.com/helm/charts/commit/2a7038bbdb9a42eda8a64f2f66e38dba8ef3170b).

So the fix in our case turned out to be creating our own PriorityClass and simply adding:

```yaml
prometheus-node-exporter:
  priorityClassName: custom-high-priority
```

In our `values.yaml`. :)

Of course this won't help for the main Prometheus, AlertManager etc deployments.

**Comment by vsliouniaev** [comment]
These also support adding priority class through `AlertmanagerSpec` and `PrometheusSpec`. @Pluies
