### ISSUE TITLE
[stable/jenkins] add clusterrole for executing helm inside pipeline

### ISSUE THREAD

**Issue by denis111** [helm/charts#13458]
**Is your feature request related to a problem? Please describe.**
jenkins service account has no sufficient permissions to execute helm inside pipeline.

**Describe the solution you'd like**
Add an option to include clusterrole for jenkins account allowing him to get,list,create on pods,pods/portforward

**Describe alternatives you've considered**
I've created manually clusterrole and binding:
```
kubectl create clusterrole jenkins --verb=get,list,create --resource=pods,pods/portforward
kubectl create clusterrolebinding jenkins-binding --clusterrole=jenkins --serviceaccount=ci:jenkins
```

**Comment by torstenwalter** [comment]
Are you running your pilelines on Jenkins master or on agents which are scheduled via the Kubernetes plugin?

> It is pretty common when starting with Jenkins to have a single server which runs the master and all builds, however Jenkins architecture is fundamentally "Master+Agent". The master is designed to do co-ordination and provide the GUI and API endpoints, and the Agents are designed to perform the work. The reason being that workloads are often best "farmed out" to distributed servers. This may be for scale, or to provide different tools, or build on different target platforms. Another common reason for remote agents is to enact deployments into secured environments (without the master having direct access). 
https://wiki.jenkins.io/display/JENKINS/Distributed+builds

I am asking because there are different service accounts involved and depending on who executes builds permission for the correct service account need to be set.

Jenkins Master uses one service account which is configured within the Deployment
https://github.com/helm/charts/blob/master/stable/jenkins/templates/jenkins-master-deployment.yaml#L70 
This service account is created automatically when `serviceAccount.create` is set to `true`, which is the default. As `rbac.create` also defaults to `true` we also create two roles for this service account:

- {{ $serviceName }}-schedule-agents # This role is used to allow Jenkins scheduling of agents via Kubernetes plugin.
- {{ template "jenkins.fullname" . }}-casc-reload # The sidecar container which is responsible for reloading configuration changes needs permissions to watch ConfigMaps

Source: https://github.com/helm/charts/blob/master/stable/jenkins/templates/rbac.yaml

This are just enough permission for Jenkins to be able to schedule agents via the Kubernetes plugin.

These agents can use a different service account (if nothing is configured the one named `default` will be used).


As the builds running on either Jenkins master or Agents use the service account from the pod to communicate with Kubernetes you need to grant necessary permissions to the correct service account.

It seems to be common best practice to only run builds on agent and to run no builds at the master at all.

**Comment by denis111** [comment]
Yes, I run builds on agents and put serviceAccount to jenkins in podTemplates of Jenkinsfile but it only has permission to pods in it's namespace while helm inside the pipeline deploys charts in another namespaces. I understand that I can create others accounts but just wanted fully automated solution like deploy jenkins and have it working without additional configuration of the cluster.

**Comment by torstenwalter** [comment]
Are you using the same service account for Jenkins master and agents? I think it's best to separate both, but that's just personal preference.

**Comment by denis111** [comment]
The same account just to not create any accounts manually and it worked in some older chart version. I think it's good to restrict jenkins service account permissions but now it requieres manual creation of clusterrole or another account.

**Comment by torstenwalter** [comment]
What's been there in the past was the possibility to create a rolebinding to existing roles. I am fine with adding similar options again, but it shoud not default to being `cluster-admin` as that is certainly bad practice.

What would your suggestion be of how to implement this? Creating a custom role, just offer functinality to bind to an existing role?

**Comment by denis111** [comment]
I'm not sure, some option in values.yaml maybe to create and bind a clusterrole to jenkins account with customizable verb and resource?...

**Comment by RicoToothless** [comment]
I have same issue too.
Maybe can add more option in `values.yaml`.

**Comment by lgg42** [comment]
Hey, I just faced with this issue because I also need to run helm inside the pipelines.
I agree with @torstenwalter that it's best to separate both service account for Jenkins master and agents.

@RicoToothless That seems like an option to me. I could go with what @denis111 said or... just creating a simple extra service account with the cluster-admin role for it to be available.

Now since release 1.11.0 we can define podTemplates using JCasC definition, it could get as simple as just putting the former ServiceAccount name under a `serviceAccount` field in a `agent.podTemplates` key. Now you have agents with a cluster-admin role out-of-the-box like @denis111 mentioned.

I'd be more that happy to open a PR since I also need this.

**Comment by torstenwalter** [comment]
> @RicoToothless That seems like an option to me. I could go with what @denis111 said or... just creating a simple extra service account with the cluster-admin role for it to be available.

Granting the extra service account cluster-admin permissions renders the existing limited roles kind of useless from a security perspective.

I usually run Jenkins agents in a separate namespace (e.g `jenkins-agents`). This way one has a clean separation between Jenkins master and agents. Service account used for agents is then also located in a different namespaces.

If I want to allow Jenkins agents to make changes in a 'dev' namespace the following RoleBinding can be used:

```
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-edit
  namespace: dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
- kind: ServiceAccount
  name: default
  namespace: jenkins-agents
```

With helm version 3 that's sufficient for most charts. In case they want to create 'Roles' or ' RoleBindings' one can also bind this ClusterRole 'admin'. Note: I am still using a `RoleBinding` and not a `ClusterRoleBinding`, which means that the permissions are only for a specific namespace.

**Comment by RicoToothless** [comment]
@torstenwalter Can it support multi namespaces in chart?
It look like only 1 namespace can be define in `values.yaml`

**Comment by torstenwalter** [comment]
> @torstenwalter Can it support multi namespaces in chart?
> It look like only 1 namespace can be define in `values.yaml`

Which namespace are you referring to? Can you name the key of the value?

**Comment by RicoToothless** [comment]
I check `templates/rbac.yaml` and find `jenkins.master.slaveKubernetesNamespace`
If I want to deploy multi namespaces. how to do that?
