### ISSUE TITLE
[stable/prometheus-operator] make alert rule annotations consistent

### ISSUE THREAD

**Issue by gregbacchus** [helm/charts#13708]
**Is your feature request related to a problem? Please describe.**
Yes, it is difficult to create templates for formatting the alerts (e.g. into a slack message) as the annotations are inconsistent between different alerts.

Some alerts have the annotations [e.g. here](https://github.com/helm/charts/blob/master/stable/prometheus-operator/templates/prometheus/rules/etcd.yaml)
- `message`

And others have [e.g. here](https://github.com/helm/charts/blob/master/stable/prometheus-operator/templates/prometheus/rules/prometheus.rules.yaml)
- `description`
- `summary`

**Describe the solution you'd like**
Personally I like the `summary` and `description` approach. Where the summary has a *static*  human readable title (that can then be grouped by) and the longer description that has the details of what has offended and how. I believe that this way is more flexible.

But I'd be happy with anything that is consistent.

**Describe alternatives you've considered**
I have tried to get my noobish template-foo on and make an advanced template that handles either case, but short of duplicating the whole thing wrapped by some `if` statements, I haven't had much luck. When I try `default` or `coalesce` functions they don't seem to exist.

**Comment by vsliouniaev** [comment]
I think you raise a good point and it would be useful to address it.

@gregbacchus The alerts are sourced from two different upstream repositories, outlined here: https://github.com/helm/charts/tree/master/stable/prometheus-operator/hack, and are merged into the repository using the scripts. I think the best option would be to ask the two repos to converge on a standard way of labelling the alerts, but as that may be a longer-term goal, I think it would be feasible to amend the scripts so that labels are standardized in this repo. What do you think?

cc: @paskal

**Comment by paskal** [comment]
I think preparing PR to change things on [etcd side](https://github.com/etcd-io/etcd/blob/master/Documentation/op-guide/etcd3_alert.rules.yml) for consistency and then importing changes there is the right way to do that.

**Comment by vsliouniaev** [comment]
Yea sounds like a good idea. I think many of the contributors are the same, so it should make sense
