### ISSUE TITLE
[stable/grafana][stable/prometheus-operator] CrashLoopBackOff - failed to open log file "...": no such file or directory

### ISSUE THREAD

**Issue by msschl** [helm/charts#13715]
**Describe the bug**
The grafana pod instance of the prometheus-operator chart occasionally crashes due to the error `failed to open log file "...": no such file or directory`

**Version of Helm and Kubernetes**:
Helm:
Client: &version.Version{SemVer:"v2.12.1", GitCommit:"02a47c7249b1fc6d8fd3b94e6b4babf9d818144e", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.1", GitCommit:"02a47c7249b1fc6d8fd3b94e6b4babf9d818144e", GitTreeState:"clean"}
Kubernetes:
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:17:39Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-01T20:00:57Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}

**Which chart**:
stable/grafana
stable/prometheus-operator
Chart: prometheus-operator-5.5.1
App Version: 0.29.0

**What happened**:
Grafana instance keeps crashing and never recovers.

**Anything else we need to know**:
After deleting the pod instance, the replica set redeploys a new pod and initializes it. This new instance runs some time until it begins again. The pod crashes and never recovers.

**Comment by vsliouniaev** [comment]
I think this is an issue with `[stable/grafana]` rather than `[stable/prometheus-operator]`. Could you please update the chart in your issue, it should help the chart maintainers find this issue more easily?

Googling for the log line, I think the issue you are facing is not related to the grafana pod specifically, but rather with the ability of the container to write logs to the node, so it doesn't look chart-specific to me.
