### ISSUE TITLE
[stable/mongodb] change the default value "mongodbEnableIPv6" to false

### ISSUE THREAD

**Issue by nvpnathan** [helm/charts#14002]
I'm currently trying to deploy Jenkins-X and one of the requirements is monocular, monocular depends on MongoDB. Monocular is listed in Jenkins-X `requirements.txt`, and MongoDB is listed in Monocular's `requirements.txt`. So changing a value in the MongoDB helm chart doesn't seem doable when deploying with Jenkins-X. 
The majority of K8s CNI's deploy by default with IPv4 as well, so I would assume that most deployments have to toggle this in the `values.yaml`.

If this is possible to do with Helm, that would work as well.

Jenkins-X Helm Chart Hierarchy: 

Jenkins-X
-->Monocular
----->MongoDB
-------->values.yaml ## This is what I need to change when deploying Jenkins-X

**Describe the solution you'd like**
Please change the default value `mongodbEnableIPv6: true` to `mongodbEnableIPv6: false`

**Describe alternatives you've considered**
Helm workarounds but looking at the Hierarchy above I don't believe this is possible.

**Comment by miguelaeh** [comment]
Hi @nvpnathan ,
This parameter does not mean MongoDB is using IPv6, just enables the support to use it. To allow IPv6 you must configure other parameters too. You can refer to this link: https://docs.mongodb.com/manual/reference/configuration-options/#net.ipv6 . Also you can refer to this issue: https://github.com/bitnami/bitnami-docker-mongodb/issues/108 
Are you getting an error with this parameter?

In the other hand, to change the value you want I guess you can use the option `--set monocular.mongodb.mongoEnableIPv6=true`

**Comment by nvpnathan** [comment]
So Jenkins-X it doesn't support `--set` commands, but it does support the values file. And I've tried adding this into the `myvalues.yaml` for Jenkins-X
```
monocular:
  mongodb:
    mongodbEnableIPv6: false
```
If it's set to true the pod never comes up.
2019-05-23T23:11:28.191+0000 I STORAGE  [initandlisten] exception in initAndListen std::exception: open: Address family not supported by protocol, terminating
2019-05-23T23:11:28.191+0000 I CONTROL  [initandlisten] now exiting
2019-05-23T23:11:28.191+0000 I CONTROL  [initandlisten] shutting down with code:100

**Comment by miguelaeh** [comment]
Are the logs you are sending from monocular, mongodb or jenkins-X?
Not sure about that but, it could be possible you have some special configuration in your environment?
The fact that the `mongodbEnableIPv6` parameter is true does not means that MongoDB will use IPv6 but it can use it.
Has you set either `net.bindIp` or ` net.bindIpAll` to true? In that case MongoDB will use IPv6.
In any case, if setting it to false works for you just set it.

Answer the original request, we will not change that parameter because most of people haven't problems and if we change it, MongoDB would not support IPv6, so we think it is better set it to `true`. 

Thanks for your report, feel free to ask any question.

**Comment by benc-uk** [comment]
I found in my Kubernetes cluster (v1.14) that the default (true) causes the readiness probe to always fail `Error: couldn't connect to server 127.0.0.1:27017`

Setting `mongodbEnableIPv6: false` fixed this

**Comment by miguelaeh** [comment]
Hi @benc-uk,
I tried it again, and it works for me.
Could you tell me how did you deploy it exactly initially?

**Comment by carrodher** [comment]
We released a [new MongoDB chart version](https://github.com/helm/charts/pull/15229) (`stable/mongodb 6.0.0`) disabling IPv6 by default in order to fix this kind of issues, as you can see in the description, depending on the way in which IPv6 is disabled in the host, the mongodb service could fail if it is configured to support this protocol by setting `net.ipv6: true` in the _mongodb.conf_ file.

In the same way, the `bitnami/mongodb` image will have the `MONGODB_ENABLE_IPV6 ` env. variable disabled by default [since the latest versions](https://github.com/bitnami/bitnami-docker-mongodb#3613-r33-4010-r42-4113-r40-and-4113-r41).

Please, feel free to ping me if you find some issues with the new approach.
