### ISSUE TITLE
[stable/traefik] Rename dashboard.* to web.*?

### ISSUE THREAD

**Issue by kachkaev** [helm/charts#1457]
**Which chart**:
[stable/traefik](https://github.com/kubernetes/charts/tree/master/stable/traefik)

**Anything else we need to know**:

I noticed a discrepancy between how the web UI is referred in the charts't `values.yaml` and [in traefik.toml](https://docs.traefik.io/toml/#api-backend). Traefik's `web` section is named `dashboard` in the chart and although this does not cause much confusion to humans, there seems to be little benefit in having two words referring to the same entity. What do you guys think of renaming `dashboard` to `web` in `values.yaml` (and other parts of the chart) so that the term used matches the upstream terminology?

The chart will need to become v2 as this is a breaking change. I can submit a PR, just want to discuss this first.

/cc @krancour @c-knowles @viglesiasce

**Comment by cknowles** [comment]
@kachkaev although I'm not the maintainer of the chart, I noticed the same thing when I originally used it. I didn't mind either way really, `web` can mean so many things that's probably why `dashboard` was chosen for the chart.

**Comment by kachkaev** [comment]
cc @djsly. What do you think?

I'd like to add `[web statistics] RecentErrors = 10` [from the toml](https://docs.traefik.io/toml/) available as a chart config, but the current diff in naming makes things a bit confusing. Would be good to collect opinions on this issue first.

**Comment by krancour** [comment]
> web can mean so many things that's probably why dashboard was chosen for the chart

That was indeed my reason for deviating and choosing "dashboard." I felt it added some clarity for the users of _the chart_, who are not necessarily familiar with configuring `traefik.toml` manually. The discrepancy is only apparent to those who _are_ intimately familiar with raw Traefik configuration.

Of course, you can disagree with me on the rationale used above, but even if there were a broad consensus that this is wrong and needs to be "fixed," the question then needs to be asked whether this very, very minor fix is a worthy reason to introduce a breaking change. I would argue very strongly that it is not. It strikes me as ill-advised to make all the users of chart incur the effort to adapt to this breaking change all for the sake of eliminating an internal inconsistency that most of them are unaware of.

**Comment by kachkaev** [comment]
That's a pretty inconvenient breaking change indeed, but I wonder if not doing it now will only make things more problematic in future for a larger user audience. The helm chart ecosystem is still pretty young, so it feels to me that the total amount of human hours lost will not be terrifying, if the change is done soon.

I guess that the reason why traefik designers took `web` instead of `dashboard` is because there may be plans on making the public-facing HTTP endpoint a bit more than just a webpage with charts. You can make the whole API available via `web`, but hardly via `dashboard`. If something does happen in this direction, the word `dashboard` will become more confusing, so there may rise  a strong demand on changing it in the chart at some point. But the further we are in future, the more pain for more people this will cause.

**Comment by krancour** [comment]
> I guess that the reason why traefik designers took web instead of dashboard is because there may be plans on making the public-facing HTTP endpoint a bit more than just a webpage with charts. You can make the whole API available via web, but hardly via dashboard.

I don't feel convinced by this.

For starters, this is speculation. Personally, I find it unlikely that a dashboard (their web UI) and an API would ever be served from the same endpoint. This is now speculation on _my_ part of course, but I would expect those two concerns to be _independently_ enabled/disabled/configured so that one could, for instance, serve them from two different domains, or even enable one and disable the other... or make one publicly accessible and the other accessible only from within the cluster.

Even if your speculation is correct, note that the domain name associated with the "dashboard" is configurable. The default value in this chart's `values.yaml` is `traefik.example.com`, but you can and should change that to whatever suits you. If you would find it weird to serve an API from `dashboard.example.com`, then don't. Go ahead and use `web.example.com` or whatever else you are comfortable with.

So, ultimately, what this comes down to is the possibility that what Traefik considers to be "web" _might_ one day encompass _more_ than just the dashboard. If that happens, the fact that there's a section of `values.yaml` configuration _called_ "dashboard" becomes odd, yes, but I don't think it's worth introducing a breaking change to account for the slim possibility of that scenario right now... because I don't even think it's worth introducing a breaking change to account for this in the future if it actually does happen. If it happens, the "dashboard" section of `values.yaml` just becomes an idiosyncrasy of the chart that's easily explainable due to the parallel evolution of the chart and Traefik itself. These things happen all the time. That idiosyncrasy can easily be addressed farther on down the line if and when some other more compelling reason forces us to make a breaking change. At that point, we could more reasonably implement a wish list of breaking changes while the opportunity exists.

**Comment by kachkaev** [comment]
> These things happen all the time. That idiosyncrasy can easily be addressed farther on down the line if and when some other more compelling reason forces us to make a breaking change. At that point, we could more reasonably implement a wish list of breaking changes while the opportunity exists.

You're probably right. Shall we close the issue (at least until someone raises it again)?

**Comment by krancour** [comment]
I would say yes. My gut feeling is that whenever Traefik 2.0 happens (I haven't followed their roadmap closely, so idk how far in the future that might be) that's the opportunity to go scorched earth (cause we'll have to) and re-imagine the chart in a way that pays down these minor debts.
