### ISSUE TITLE
[stable/airflow] Not compatible with the latest apache/airflow container

### ISSUE THREAD

**Issue by will-beta** [helm/charts#14683]
Just saw Apache released its official [apache/airflow](https://hub.docker.com/r/apache/airflow) container.
Tried it with current chart, resulting in the `CrashLoopBackOff` status all the time.
Seems like a compatible issue.

**Comment by stevenmanton** [comment]
This chart is designed to work with the pucke/docker-airflow image. Unfortunately, it's not compatible with the official airflow container, which is set up quite a bit differently (e.g. environment variables, entrypoint script).

I've heard that some of the core Airflow dev's are working on a new image, which would be great. (Puckel's image has a lot of downsides and breaks frequently because it doesn't pin python versions.) But until then, I recommend starting from the puckel image and modifying as you need.

**Comment by will-beta** [comment]
@stevenmanton Thanks a lot for the reply! Expecting that new image!
