### ISSUE TITLE
Stable Drupal Chart , mistake in Notes.txt

### ISSUE THREAD

**Issue by EleanorRigby** [helm/charts#1490]
**Is this a request for help?**: No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Version of Helm and Kubernetes**:
*Helm Version*
```
Client: &version.Version{SemVer:"v2.4.2", GitCommit:"82d8e9498d96535cc6787a6a9194a76161d29b4c", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.5.0", GitCommit:"012cb0ac1a1b2f888144ef5a67b8dab6c2d45be6", GitTreeState:"clean"}
```
*Kubernetes Version*
```Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.3", GitCommit:"0480917b552be33e2dba47386e51decb1a211df6", GitTreeState:"clean", BuildDate:"2017-05-10T15:48:59Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.7", GitCommit:"8eb75a5810cba92ccad845ca360cf924f2385881", GitTreeState:"clean", BuildDate:"2017-04-27T09:42:05Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:
Drupal

**What happened**:
Notes.txt lists these two commands 
```
export SERVICE_IP=$(kubectl get svc --namespace default silly-aardvark-drupal -o jsonpath='{.status.loadBalancer.ingress[0].*ip*}')
echo http://$SERVICE_IP/
```
There is no field ip in `ingress[0]` instead there is hostname. Is this specific to me because I am using aws for deployment and aws has its own loadbalancer

**What you expected to happen**:
I expect for Notes.txt to print right field value.
Like, in Notes.txt
this line should change 
```
from 

export SERVICE_IP=$(........... -o jsonpath='{.status.loadBalancer.ingress[0].ip}')

to

export SERVICE_IP=$(........... -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')
```

**How to reproduce it** (as minimally and precisely as possible):
Just do `helm install stable/drupal`. Read notes and do 
`kubectl get svc --namespace default <releasename> -o json` . See ip field is absent under ingress

**Anything else we need to know**:

**Comment by EleanorRigby** [comment]
If this really is a bug , I would like to fix it.

**Comment by sameersbn** [comment]
@EleanorRigby

This is not a bug. Your kubernetes setup probably cannot assign a external ip address to the service. Since the default `serviceType` field is defined to be of type `LoadBalancer`. We expect the platform to auto-assign a external ip address to the service. This is known to work on a kubernetes cluster set up on GKE. It may not work on other platforms out-of-the-box.

You should try specifying the value of `.Values.serviceType` to `ClusterIP` or `NodePort` depending on your kubernetes setup.  If you're using minikube, you can simply do `minikube service silly-aardvark-drupal` to access the service.

**Comment by sameersbn** [comment]
Looks like you may be using kubernetes on AWS where they define `hostname`. I guess we need to mention it in the Notes.
.
