### ISSUE TITLE
[stable/postgresql] Replication fails when persistence is enabled

### ISSUE THREAD

**Issue by ih8d8** [helm/charts#15000]
**Describe the bug**
I can successfully bring up a PostgreSQL cluster with a master node and two slave nodes when persistence is disabled; However, replication fails when persistence is enabled. I use Local Persistent Volumes as my storage solution for postgresql databases. I've been told that this might the best storage solution for a containerized postgresql cluster so I deployed it and expected the helm chart to go smoothly but it turned out that some slave nodes couldn't join the cluster because of failed data cloning from master to those slaves. This is the error that I got in failed slave nodes:

`2019-06-22 22:04:45.431 GMT [1424] FATAL:  database system identifier differs between the primary and standby`

I thought this might be related to wal_receiver_timeout or wal_sender_timeout so I increased their values via an extendedConfConfigMap but it didn't help and I got the same error. What can I do to solve this problem. 
**Version of Helm and Kubernetes**:
Helm v2.14.1 and Kubernetes v1.15.0

**Which chart**:
stable/postgresql v5.3.9

**Comment by i8ad8** [comment]
I was able to solve this on my own. The problem was not related to the postgresql helm chart. Replication failed because the local PVs weren't cleared so when they got reattached to postgresql pods the old data from the previous replications were present in slave nodes and that caused the cloning process to fail.
I'm closing this issue.

**Comment by carrodher** [comment]
Thanks for letting us know, feel free to reopen the issue if needed.
