### ISSUE TITLE
[stable/postgresql] values-production.yaml not setting up replication correctly

### ISSUE THREAD

**Issue by ceastman-ibm** [helm/charts#15078]
**Describe the bug**
Copied the values-production.yaml to values.yaml to turn on slave replication. When the slaves try to start I get the following error in their logs:

pg_basebackup: could not connect to server: FATAL:  password authentication failed for user "<<redacted>>"

i verified that the user is the one im expecting that was defined in .Values.global.postgresql.replicationUser

**Version of Helm and Kubernetes**:
Helm: 2.9.1
Kube: 1.12.9

**Which chart**:
version: 5.3.10
appVersion: 11.4.0

**What happened**:
master node seems to start up fine, slaves are in CrashLoopBackOff start

**What you expected to happen**:
Slave to start and replicate from the master node

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by miguelaeh** [comment]
Hi @ceastman-ibm,
Did you deploy this chart before? In that case did you delete your PVC? Probably the problem is that the password is stored on the cluster from the previous deployment and the new installation is configured with a different password while the slaves are using the old one because it is stored.
Please try removing the PVC:
```
$ kubectl delete pvc <pvc-name>
```

**Comment by ceastman-ibm** [comment]
yep i deleted the pvc in between installations.

**Comment by miguelaeh** [comment]
Hi @ceastman-ibm ,
Could you try to set a password manually at deploy time?

**Comment by ceastman-ibm** [comment]
would that be an environment variable in the slave yaml file?

**Comment by cr2025x1** [comment]
Similar issue here, but with this log showing up on the slave pod with CrashLoopBackOff.
I set replication.password and .postgresql, .postgresqlPassword.

---

WARN  ==> Data directory is set with a legacy value, adapting POSTGRESQL_DATA_DIR...
WARN  ==> POSTGRESQL_DATA_DIR set to "/bitnami/postgresql/data"!!

Welcome to the Bitnami postgresql container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-postgresql
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-postgresql/issues
Send us your feedback at containers@bitnami.com

INFO  ==> ** Starting PostgreSQL setup **
INFO  ==> Validating settings in POSTGRESQL_* env vars..
ERROR ==> The POSTGRESQL_PASSWORD environment variable is empty or not set. Set the environment variable ALLOW_EMPTY_PASSWORD=yes to allow the container to be started with blank passwords. This is recommended only for development.

**Comment by miguelaeh** [comment]
Install using  `helm install stable/postgresql --set replication.password=<password>`

You can see all the available parameters (here)[https://github.com/helm/charts/tree/master/stable/postgresql#configuration].

**Comment by zazu86** [comment]
Hi everyone,
I confirm the existence of the problem, I tried different versions of the chart, starting from:
version: 5.3.1
appVersion: 11.3.0
until:
version: 5.3.10
appVersion: 11.4.0
I also tried to change various versions of the container, up until the last 11.4.0-debian-9-r14

and always behaves in the same way
the final problem is that it is not possible to obtain a master/slave postgres system,
the problem occurs as described in the first post from "ceastman-ibm"

in the master:
```
2019-07-08 13:07:03.691 GMT [164] FATAL:  password authentication failed for user "postgres"
2019-07-08 13:07:03.691 GMT [164] DETAIL:  User "postgres" has no password assigned.
	Connection matched pg_hba.conf line 1: "host     all             all             0.0.0.0/0               md5"
```

in the slave:

```
pg_basebackup: could not connect to server: FATAL:  password authentication failed for user "repl_user"
```

I think the problem is deeper, the system does not work at all, in the master, the postgres user does not even exist, nor is the password set;

in the master the system user is not created, and the container starts with a 1001 UID which does not exist in /etc/passwd and entering the shell by trying some commands I get this:

```I have no name!@cluster-pgsql-postgresql-master-0:/$ psql
psql: local user with ID 1001 does not exist
I have no name!@cluster-pgsql-postgresql-master-0:/$ su -
su: Cannot determine your user name.
I have no name!@cluster-pgsql-postgresql-master-0:/$```

to set the parameters I used the values-production.yaml file,

I also tried to pass the parameters with --set in the commandline,

in the pod the variables are loaded correctly.
