### ISSUE TITLE
 stable/openvpn --version 3.13.1

### ISSUE THREAD

**Issue by Warok21** [helm/charts#15119]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
With this chart, is it possible to deploy a VPN between two nodes of one cluster?

**Describe alternatives you've considered**
I have three nodes, a master wich is geographically located elsewhere, and the two other nodes that are close, but not on the same network. I've create a cluster with those three, and now, I want to make a tunnel between the two (close) nodes to compare the benefits to communicate without going to the master, and then come back
**Additional context**

**Comment by jasongwartz** [comment]
@Warok21 I don’t believe this is possible (using the openvpn chart to connect nodes to each other to form a cluster), because this chart relies on the kubernetes overlay network already being in place.

If anyone knows if this is possible, I’d be happy to see an explanation, but if I understand your question correctly, I don’t believe this would work using a helm chart.
