### ISSUE TITLE
Nginx: 502 Bad Gateway error after deploying redmine in kubernetes cluster.

### ISSUE THREAD

**Issue by MK1993** [helm/charts#15144]
I tried to deploy redmine in kubernetes cluster (containing 1 master and 2 workers) through this helm chart "https://gitlab.com/kanzari.1993/redmine" with nginx ingress controller enabled, the deployment done with success but when I tried to access the application through the name of the host mentioned in the ingress.yaml file I get this warning: "502 Bad Gateway nginx / 1.17.0" on the other hand all the pods are in "running" state.

Do you have an idea about how to solve this problem?

Thanks in advance!
![Capture](https://user-images.githubusercontent.com/36052172/60394835-1c72f500-9b22-11e9-8ee6-fcc061010498.PNG)

**Comment by Aisuko** [comment]
Did you deploy nginx-ingress control on your cluster? Please check the link below https://kubernetes.io/docs/concepts/services-networking/ingress-controllers/

Some advice for HTTPS backend server:

If there was you have an HTTPS backend server. Make sure your secret include the HTTPS certificate which was used by your backend server and add `nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"` is helpful with HTTPS.

And ingress annotations document address https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/

**Comment by Mehrez27** [comment]
Aisuko I did the nginx-ingress control is deployed and working like a charm! but my problem was "the ingress is working but your backend is not".

**Comment by Aisuko** [comment]
Did you deploy nginx-ingress controll with the host Network?  You can deploy the nginx-ingress controll with the `service=Nodeport ` and check if that working well.

**Comment by Mehrez27** [comment]
Aisuko how to deploy nginx-ingress controller using **service=Nodeport** ?

**Comment by Aisuko** [comment]
Please take to look at  ```controller.service.type``` in Readme.md

**Comment by Mehrez27** [comment]
Aisuko I think the problem is coming from the deployed application itself "redmine" there is the outputs to explain more the situation.
![Capture](https://user-images.githubusercontent.com/36052172/60670076-b8c13280-9e67-11e9-9519-635bdd65d8e5.PNG)
![Capture1](https://user-images.githubusercontent.com/36052172/60670077-b8c13280-9e67-11e9-933f-30ade47407ca.PNG)
![Capture2](https://user-images.githubusercontent.com/36052172/60670078-b8c13280-9e67-11e9-81ee-162b457b587b.PNG)
![Capture3](https://user-images.githubusercontent.com/36052172/60670080-b959c900-9e67-11e9-94f0-f8ef0f3460db.PNG)
