### ISSUE TITLE
[stable/prometheus-operator] Decouple Grafana dashboards from prometheus-operator chart.

### ISSUE THREAD

**Issue by P6rguVyrst** [helm/charts#15623]
**Problem:**
Since I am using Grafana as a central place to aggregate all kinds of different datasources, I find deploying Grafana as a sidekick of Prometheus too restrictive. I would, however, like to use the nice Dashboards this chart comes with (https://github.com/helm/charts/tree/master/stable/prometheus-operator/templates/grafana/dashboards) in my own instance of Grafana.

**Solution 1:**
Add dashboards defined under prometheus-operator chart to Grafana community at: https://grafana.com/grafana/dashboards, this way the dashboards have their own revision history and "gnetId" and are decoupled from this chart. This will alloow me to reference "gnetId" in my Grafana values file.

**Solution 2:** 
Remove the ".Values.grafana.enabled" filter from dashboard ConfigMap templates, and allow ".Values.grafana.defaultDashboardsEnabled" to be enabled without installing THIS Grafana. This will allow me to use the ConfigMap elsewhere.

**Alternatives:**
* Hold my own copy of the json files defined in ConfigMaps, which I can then reference from my Grafana values file.
* Add the dashboards to Grafana community myself, which I can then reference with "gnetId".

**NB!** I would be willing to do this feature myself, if that is appropriate.

**Comment by haf-afa** [comment]
Hey; this would be great. Currently the chart generates 35000 lines of code when run against a k8s cluster; so it was pretty hard to do much anything at all. I created some tooling to work with the chart:

https://gist.github.com/haf-afa/575ed9f546037ea99c5b9e97f75b9c83

Some stats from using this:

The template.yaml file that Helm generates contains 129 non-empty files, 31 empty ones.

You can remove almost all things it generates with grafana_templates in the name; and keep all grafana_dashboards.

Then you can use the Grafana Helm chart instead of this to deploy Grafana independently. Have a look at the linked gist.

Hey stale, open up this issue.
