### ISSUE TITLE
[stable/jenkins] Freedom to specify master deployment replicas

### ISSUE THREAD

**Issue by HarithJ** [helm/charts#15980]
**Is your feature request related to a problem? Please describe.**
We have just migrated from using CircleCI to Jenkins. We have a lot of projects that require CI/CD pipeline. Because I do not know how much resources Jenkins would need in order for it to run smoothly, I keep on running into OOM issues. Every time this happens, Jenkins server goes down, which causes interruption to our pipelines. Also, when I update the settings related to the master deployment, the Jenkins server goes down.

**Describe the solution you'd like**
I would like the freedom to specify the number of replicas I want the master deployment to have in order to have a Highly Available Jenkins server.

**Describe alternatives you've considered**
I have considered two alternatives; 
   1. To have 2 master deployment, one acting as a backup server.
   2. To increase the master replicas via the GKE deployment edit functionality.

**Additional context**
None

**Comment by torstenwalter** [comment]
Changing the number of replicas won't help. Jenkins does not support HA. It's hard to predict what happens if multiple Jenkins master writing to the same volume, but I am pretty sure that it will cause trouble.

Where do you run your builds on the Jenkins master or on worker nodes? The first one often causes trouble and is not recommend.

**Comment by HarithJ** [comment]
I run **all** the builds on the worker nodes.

Thank you for the reply, I manually set the replicas to two and it did not work out.
