### ISSUE TITLE
[stable/external-dns] Should not default to bitnami chart.

### ISSUE THREAD

**Issue by marcoceppi** [helm/charts#16042]
**Describe the bug**
Upstream maintains their own docker repository, this chart - as part of helm/charts stable should use vendor agnostic and upstream images. There is no value add to the bitnami image and it's not documented that users won't be getting upstream's builds.

**Which chart**: stable/external-dns

**What happened**: Vendor docker image was deployed by default

**What you expected to happen**: For upstreams image

**How to reproduce it** (as minimally and precisely as possible): Deploy the latest chart

**Anything else we need to know**:

**Comment by juan131** [comment]
Hi @marcoceppi 

Thanks so much for your suggestion! If experienced any issue with the Bitnami image, please let us know it so we can work on improving the image.

Regarding replacing the image with the upstream one, this is a discussion to be answered by the Helm community.

**The "external-dns" helm chart is currently maintained by the Bitnami team since there were no maintainers of this chart** and the community accepted the Bitnami team in the "Call for maintainers" that took place 3 months ago. IMHO this chart has been improved significantly since Bitnami team is maintaining it. In these 3 months, the team attended more than 40 PRs and issues (many of which were abandoned due to the lack of maintainers) and extended the chart supporting new DNS providers such PowerDNS or adding new features such as PodSecurityPolicies or Prometheus exporters.

On the other hand, Bitnami images are up-to-date and built on a daily basis to ensure there are no CVEs. They're available in Quay & DockerHub and signed with Docker Content Trust, and you can also access the CVE scan reports available at Quay. These images also follow some of the best practices to improve the security on production environments such as ensuring they're executed as "non-root" containers. And, **the chart is still compatible with the image maintained by Zalando team**.

Due to our internal quality assurance processes, security audits, etc. **we (Bitnami) cannot maintain any chart that do not use our images by default**. As I mentioned, it's the community who decides who's maintaining the charts and what images are used on them, so **we're open to continue maintaining this chart in our repo (bitnami/charts) and leave this chart open for new maintainers**.
