### ISSUE TITLE
[stable/prometheus-operator] prometheusOperator.cleanupCustomResource=true doesn't delete custom resource definitions

### ISSUE THREAD

**Issue by krichter722** [helm/charts#16079]
**Describe the bug**
Specifying `--set prometheusOperator.cleanupCustomResource=true` to `helm install` doesn't delete the custom resource definitions as stated in the docs at https://github.com/helm/charts/tree/master/stable/prometheus-operator, e.g.

```
> helm install --name test-monitoring --namespace=test-monitoring stable/prometheus-operator --set prometheusOperator.cleanupCustomResource=true
Error: customresourcedefinitions.apiextensions.k8s.io "alertmanagers.monitoring.coreos.com" already exists
```

**Version of Helm and Kubernetes**:
```
> helm version
Client: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.2", GitCommit:"a8b13cc5ab6a7dbef0a58f5061bcc7c0c61598e7", GitTreeState:"clean"}
```

microk8s v1.15.1 (720)

**Which chart**:
stable/prometheus-operator

**What happened**:
Installation routine should delete custom resource definitions if `prometheusOperator.cleanupCustomResource=true`

**What you expected to happen**:
The installation fails due to `Error: customresourcedefinitions.apiextensions.k8s.io "alertmanagers.monitoring.coreos.com" already exists`

**How to reproduce it** (as minimally and precisely as possible):
```
helm install --name test-monitoring --namespace=test-monitoring stable/prometheus-operator
helm install --name test-monitoring-2 --namespace=test-monitoring-2 stable/prometheus-operator --set prometheusOperator.cleanupCustomResource=true
```

**Anything else we need to know**:
./.

**Comment by pvorb** [comment]
This issue is still relevant. I am seeing the exact same problem with a fresh installation of the chart.

1. The initial `helm install stable/prometheus-operator` timed out.
2. A subsequent `helm install stable/prometheus-operator` results in `Error: customresourcedefinitions.apiextensions.k8s.io "alertmanagers.monitoring.coreos.com" already exists`
3. `helm upgrade` results in `Error: UPGRADE FAILED: "prometheus-operator" has no deployed releases`.

I also expected `prometheusOperator.cleanupCustomResource=true` would fix the issue but has no effect as far as I can see.

As a workaround, I had to manually run the following statements before I was finally able to install the chart.

~~~
kubectl delete crd alertmanagers.monitoring.coreos.com
kubectl delete crd podmonitors.monitoring.coreos.com
kubectl delete crd prometheuses.monitoring.coreos.com
kubectl delete crd prometheusrules.monitoring.coreos.com
kubectl delete crd servicemonitors.monitoring.coreos.com
~~~
