### ISSUE TITLE
[stable/traefik] Support acme.onDemand

### ISSUE THREAD

**Issue by adamgoose** [helm/charts#1626]
**Is this a request for help?**: Nah

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Feature Request

Requesting the ability to configure acme.onDemand via values in the stable/traefik chart.

**Comment by adamgoose** [comment]
Actually, this might also be a bug report? It appears as though `acme.onHostRule` is a typo, and should be `acme.OnHostRule`. https://docs.traefik.io/toml/#acme-lets-encrypt-configuration

**Comment by grugnog** [comment]
acme.onHostRule is correct, however having the option to also enable acme.onDemand is useful for our case:

Public facing Traefik Ingress Controller -> oAuth Proxy -> Internal Traefik Ingress Controller -> Internal Applications

Since the internal applications are only registering against the Internal Traefik Ingress Controller the Public facing Traefik Ingress Controller does not have a complete set of hostnames to retrieve certificates for in advance. Once LE releases wildcard support (hopefully soon!) this will become less of an issue, but in the mean time this is a nice option providing you are happy to accept the delay on initial connection and LE rate limits (for our case of internal applications this is not an issue).

**Comment by grugnog** [comment]
This feature was just depreciated in Traefik so it doesn't seem to make much sense to add this. I closed the associated pull request and guessing we should probably close this too.

Of note, LE wildcard certs are going live February 27 which should cover many of the use cases this would be needed for.

**Comment by krancour** [comment]
@unguiculus, would you mind closing this, please?
