### ISSUE TITLE
[stable/concourse] allow definition of custom secrets

### ISSUE THREAD

**Issue by tbe** [helm/charts#16303]
**Is your feature request related to a problem? Please describe.**
We are using an external PostgreSQL Operator for all our PostgreSQL deployments. The Operator creates secrets for each database user. As the chart does not allow us to set a custom secret, we have to create a new secret instead of using the managed one from the database operator.

**Describe the solution you'd like**
Allow the user to set a custom key

**Describe alternatives you've considered**
There are not much alternative expect rendering the template and edit it by hand or "repack" the database password

**Comment by YoussB** [comment]
Hey @tbe, 
Thanks for the issue, apologies for the late reply.

I am not sure how to solve that 🤷‍♂ 
we already have an option to set the postgres connection in the values here
https://github.com/helm/charts/blob/b3cabd44ae3f846b6694f39007a92c9e8bf029e8/stable/concourse/values.yaml#L1895-L1899

- Are you looking to be able to reference a secret here instead of the values directly?

**Comment by tbe** [comment]
> * Are you looking to be able to reference a secret here instead of the values directly?

Exactly. Writing sensitive data into something inside git is nothing we want to do. Also, there values may change, so we need to reference the external secret. The same is true for every other secret that my be required, like:
- vault credentials
- AWS
- CF
- github
- ...
