### ISSUE TITLE
stable/jenkins Changelog

### ISSUE THREAD

**Issue by 23ewrdtf** [helm/charts#16324]
**Describe *in detail* the feature/behavior/change you'd like to see.**
As I can't find the changelog it would be a good idea to add one. I'm using one of the old charts and as I want to update Jenkins I would like to know what changed.

The problem is when updating release there is no way of knowing what exactly changed.

**Describe the solution you'd like**
A simple changelog.md file would be enough.

**Describe alternatives you've considered**
An alternative would be to check https://github.com/helm/charts/commits/master/stable/jenkins or diff charts but it would take too long.

**Comment by torstenwalter** [comment]
Did you consider this? https://github.com/helm/charts/tree/master/stable/jenkins#upgrading-an-existing-release-to-a-new-major-version

**Comment by tretos53** [comment]
I did but I was thinking more about changes between each version.

For example what changed between those?

version: 1.5.1
version: 1.5.0
version: 1.4.9
version: 1.4.8

or those:

0.50.0
0.49.0
0.48.0

Especially parameters added/changed, maybe major bugs fixed. Simple changelog file would be enough, going through the commits is no fun.

**Comment by tretos53** [comment]
So basically going from 0.40 to 1.5.0:

- values have been renamed so that all variables start with a lowercase letter and words are separated with camelcase.
(I renamed them already)

 - The selectors of the deployment have been updated. In order to upgrade, delete the Jenkins Deployment before upgrading.
(Delete release before installing a new one.)

I should be fine then (famous last words).

**Comment by torstenwalter** [comment]
I'd love to see a pull request which contains the change log for previous changes. Happy to continue it afterwards.

**Comment by tretos53** [comment]
Thank you for this. I generated a changelog using auto-changelog but yours is much better :)
