### ISSUE TITLE
[stable/mongodb] initConfigMap not propagating to secondary

### ISSUE THREAD

**Issue by rjanovski** [helm/charts#16574]
**Describe the bug**
Added an init configmap script and pointed to it:
```
initConfigMap:
  name: init-config-mongodb
```

the change is getting into the primary node, but not to the secondary.

also  verified that the template for secondary is missing the initConfigmap code

**Comment by javsalgar** [comment]
Hi,

Yes. This was done on purpose because we did not want the secondary nodes to repeat the same commands as the primary node (for example, initializing a database twice). Could you specify your use case so we can understand the kind of scripts you would like to execute in the secondary nodes? Maybe it would make sense to have a second configMap for the secondary initialization. Otherwise, the scripts would require logic to distinguish between primary and secondary.

**Comment by rjanovski** [comment]
I see, thanks for the clarification.

my current usecase is really an ugly workaround to change a single configuration value without having to specify the *entire* mongodb.config in the `configmap` (I want future chart upgrades to add their future config values). Specifically, I wanted to set just the `enableMajorityReadConcern` to false on my psa setup, so added a simple sed in a script.

primary.initConfigMap and secondary.initConfigMap sounds like a good generic solution.

I'm starting to think I better manage the entire mongo config manually via the `configmap` option, unless there is a better way to override a single config value that I'm missing :)

**Comment by kwill4026** [comment]
question for you @rjanovski, are you able to specify your mongo configmap settings in the values.yaml file and actually get the arbiter, primary and secondary pod to run?
I wrote a script to enable the replicaset cluster to be TLS enabled. The script is in the /mongodb/files/docker-entrypoint-initdb.d/ directory and is being consumed as a init container. It creates a self signed CA (which gets created in all the pods to include the arbiter, primary and secondary) then for each primary and secondary it creates the pem cert in each pod which is different. My goal was to enable the mongod conf file to take in TLS paramaters to include --sslPEMKeyFile and -- sslCAFile however when I specify this manually in the values.yaml file under "configmap", the pods crash even though I see in the logs that it has detected a mongodb config fille . I even tried specifying the TLS settings in the values.yaml file by including something simple such as "--sslMode=allowSSL" under the mongodbExtraFlags section but still no luck. 
Have you been able to start up your cluster by specifying your own configmap and not using the default configmap?

**Comment by rjanovski** [comment]
@kwill4026 , 
I managed to start with custom configmap, but its tricky because the configmap is **replacing** the default config file entirely, not appending your changes to it.

So what I did:
1. started the cluster with default config file
2. entered the pod and copied the default config file (`kubectl exec -it mongo-main-mongodb-secondary-0 -- cat /opt/bitnami/mongodb/conf/mongodb.conf`)
3. used the default config file as basis for my changes (via the values.yaml `configmap`)

The real default config file is _very_ different from the commented configmap section in the values.yaml.

**Comment by kwill4026** [comment]
@rjanovski I see. So you basically copied the default config file which gets loaded upon pod start time if you keep the default values, and copied and paste that into the "configmap" section of the values.yaml file as your way of starting the cluster with your own mongo config settings. And yes I noticed the commented configmap section that comes with the values.yaml file will not run when I uncomment it. I tried using literally the same values copied from the default running pod located at 
/opt/bitnami/mongodb/conf/mongodb.conf but still cannot get the pod to run. I will have to look at it some more

**Comment by kwill4026** [comment]
@rjanovski were you able to start this cluster with your modified default config file using just a standalone cluster. Or were you able to produce this on a replicaset in which the modified conf file was able to produce the arbiter, master, and secondary?

I ask this because I was able to get the modiified conf file to produce only in the standalone mode and not when I enabled replicaset in the values.yaml file

**Comment by nicolas-g** [comment]
@rjanovski @kwill4026 how did you use the initConfigMap to work  ? I'm trying to follow the [documentation](https://github.com/bitnami/charts/tree/master/bitnami/mongodb#initialize-a-fresh-instance)  "In order to execute the scripts, they must be located inside the chart folder files/docker-entrypoint-initdb.d" but I'm not sure I understand what is considered to be the **chart** folder ?

This is what I'm trying and getting errors:
```
tree files
files
└── docker-entrypoint-initdb.d
    └── mongodb-init.js
```

mongodb-values.yml
```
initConfigMap:
  name: "mongodb-init.js"
```

helm install -f mongodb-values.yml my-mongo stable/mongodb
```
Events:
  Type     Reason                  Age                  From                                                 Message
  ----     ------                  ----                 ----                                                 -------
  Normal   Scheduled               2m21s                default-scheduler                                    Successfully assigned my-mongo-primary-0 to ip-10-72-93-181.eu-west-1.compute.internal
  Normal   SuccessfulAttachVolume  2m19s                attachdetach-controller                              AttachVolume.Attach succeeded for volume "pvc-360f1b4f-4c04-4a7f-ae29-a9be4524fe78"
  Warning  FailedMount             18s                  kubelet, ip-10-72-93-181.eu-west-1.compute.internal  Unable to mount volumes for pod "my-mongo-primary-0_hux(bc6b0d00-8f61-44f5-a93e-1a44b780644e)": timeout expired waiting for volumes to attach or mount for pod "hux"/"my-mongo-primary-0". list of unmounted volumes=[custom-init-scripts]. list of unattached volumes=[datadir custom-init-scripts default-token-8w2mm]
  Warning  FailedMount             13s (x9 over 2m20s)  kubelet, ip-10-72-93-181.eu-west-1.compute.internal  MountVolume.SetUp failed for volume "custom-init-scripts" : configmap "mongodb-init.js" not found
```

Any help will be appreciated, thanks.

**Comment by kwill4026** [comment]
@nicolas-g You are on the right track. From what the documentation reads to me, it seems as if there are two ways to get the configMap to work. This is the way I did it. You can put the .js or .sh file in the files/docker-entrypoint-initdb.d directory as you did. From here you do nothing and simply continue with your helm install -f mongodb-values.yml my-mongo stable/mongodb command. This will consume the .js as a configmap, which you can see from the initialization-configmap.yaml file in the templates directory. 

The other way, which it seems you are attempting to do, looks to be failing because somehow its not mounting the configmap as a volume. Its not recognizing it/finding it as the error states. 
I'm not sure as to why its doing that but for now try the first option and let me know what you get.

**Comment by nicolas-g** [comment]
@kwill4026 the correct command is helm install -f mongodb-values.yml my-mongo `"mongodb_chart_directory"` (instead of stable/mongodb) .

Helm install now runs but for some reason mongodb primary pod doesn't get deployed... only arbiter and secondary ...
