### ISSUE TITLE
[stable/prometheus] Cluster Roles & Role bindings created for disabled componenets

### ISSUE THREAD

**Issue by DimitrijeManic** [helm/charts#16907]
**Describe the bug**
Chart will create ClusterRoles & ClusterRolerBindings for components which are not enabled.
The ClusterRoles do not have any rules associated but are still created. 

Is this the desired behaviour? 

**Version of Helm and Kubernetes**:
helm: v2.14.3
K8s: minikube v1.3.1

**Which chart**:
stable/prometheus

**What happened**:
Empty cluster roles and cluster role bindings created for disabled components

**What you expected to happen**:
ClusterRoles & ClusterRoleBindings should not be created for disabled components

**How to reproduce it** (as minimally and precisely as possible):
```
values.yml:
-----
pushgateway:
  enabled: false
alertmanager:
  enabled: false
```
`helm install --name dev-prom stable/prometheus -f values.yml --debug --dry-run`

Running after install:
`k get clusterroles | grep dev-prom`
Shows unnecessarily created cluster roles .

**Anything else we need to know**:

**Comment by schoofsc** [comment]
Hello,
this problem is still topical. 
This problem is due to missing if queries in the following files: 
- alertmanager-clusterrole.yaml
- alertmanager-clusterrolebinding.yaml
- pushgateway-clusterrole.yaml
- pushgateway-clusterrolebinding.yaml 

There, adjustments must be made analogous to the file: server-clusterrole.yaml and server-clusterrolebinding. 

The problem is that it only checks if rbac is activated and not if the components themselves are activated. 

I made the appropriate changes and submitted a pull request. (#17746)

**Comment by cstaud** [comment]
I agree to you this is not the desired behavior. Thanks for your research! Could you imagine to get your hands on this and open a PR?

**Comment by schoofsc** [comment]
Hey @cstaud 
I have already opened a PR.
#17746
