### ISSUE TITLE
[stable/rabbitmq] touch: cannot touch '/opt/bitnami/rabbitmq/var/lib/rabbitmq/.start': Permission denied

### ISSUE THREAD

**Issue by heckad** [helm/charts#17250]
**Describe the bug**
Container can't start.

**Version of Helm and Kubernetes**:
Helm:
```
Client: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
```
Kubernets: 
```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:54Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:50Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:
stable/rabbitmq

**What happened**:
Rabbitmq can't start

**What you expected to happen**:
Rabbitmq should start

**How to reproduce it** (as minimally and precisely as possible):
`helm install -n rabbitmq stable/rabbitmq`

**Comment by alemorcuq** [comment]
Hi, @heckad.

As the image run as non-root by default, it is necessary to adjust the ownership of the persistent volume so that the container can write data into it.

By default, the chart is configured to use Kubernetes Security Context to automatically change the ownership of the volume. However, this feature does not work in all Kubernetes distributions.
As an alternative, this chart supports using an `initContainer` to change the ownership of the volume before mounting it in the final destination.

You can enable this `initContainer` by setting `volumePermissions.enabled` to `true`.

I will make sure this bit of information is added to the `README.md`.

Regards,
Alejandro

**Comment by huineng** [comment]
i solved it by setting runAsUser: 0

**Comment by alemorcuq** [comment]
Thanks for letting us know, @huineng.
