### ISSUE TITLE
[stable/prometheus] Kubernetes 1.16 incompatibility

### ISSUE THREAD

**Issue by sbishakafenix** [helm/charts#17779]
**Is your feature request related to a problem? Please describe.**
I get a validation error when installing the helm chart stable/prometheus in kubernetes 1.16
```bash
Error: validation failed: [unable to recognize "": no matches for kind "DaemonSet" in version "extensions/v1beta1", unable to recognize "": no matches for kind "Deployment" in version "extensions/v1beta1"]

```

**Describe the solution you'd like**
Either change the apiversion to apps/v1 or provide a mechanism to sink in the api version via a value.yaml

**Describe alternatives you've considered**
Downloading the templates folder to localhost and manually change the api version

**Additional context**
According to https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.16.md, extensions/v1beta1, apps/v1beta1, and apps/v1beta2 APIs have been retired in kubernetes 1.16!

**Comment by artsilenkov** [comment]
https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/

NetworkPolicy (in the extensions/v1beta1 API group)
Migrate to use the networking.k8s.io/v1 API, available since v1.8. Existing persisted data can be retrieved/updated via the networking.k8s.io/v1 API.
PodSecurityPolicy (in the extensions/v1beta1 API group)
Migrate to use the policy/v1beta1 API, available since v1.10. Existing persisted data can be retrieved/updated via the policy/v1beta1 API.
DaemonSet, Deployment, StatefulSet, and ReplicaSet (in the extensions/v1beta1 and apps/v1beta2 API groups)
Migrate to use the apps/v1 API, available since v1.9. Existing persisted data can be retrieved/updated via the apps/v1 API.

**Comment by sixcorners** [comment]
Can we fix other charts too or should they get their own tickets?
the stable/ipfs chart also has this issue:

> Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "StatefulSet" in version "apps/v1beta1"

**Comment by sixcorners** [comment]
Is it safe to just submit a pull requests with all of these changes at once?
I'm not sure if I would be able to test it all.

**Comment by sixcorners** [comment]
I guess this is a duplicate of #17267

**Comment by Terrones-Oscar** [comment]
I have same problem in a rancher deploy 
Error: validation failed: [unable to recognize "": no matches for kind "PodSecurityPolicy" in version "extensions/v1beta1", unable to recognize "": no matches for kind "DaemonSet" in version "apps/v1beta2", unable to recognize "": no matches for kind "DaemonSet" in version "extensions/v1beta1", unable to recognize "": no matches for kind "Deployment" in version "apps/v1beta2", unable to recognize "": no matches for kind "Deployment" in version "extensions/v1beta1", unable to recognize "": no matches for kind "StatefulSet" in version "apps/v1beta2", unable to recognize "": no matches for kind "StatefulSet" in version "apps/v1beta1"]
