### ISSUE TITLE
[stable/redis-ha] Should we have an option to change updateStrategy for redis-ha StatefulSet?

### ISSUE THREAD

**Issue by Aracki** [helm/charts#17860]
While in `stable/redis` we have deployment config: `master.statefulset.updateStrategy` which defaults to `onDelete` in `stable/redis-ha` there is no option to change default one (`rollingUpdate`) for StatefulSet.

It this intended this way for some reason?

**Comment by DandyDeveloper** [comment]
There's no explicit reasons from memory, although there are restrictions on how STS works with update strategies. 

It's probably not a bad idea to do this. However, one thing to keep in mind is, rolling updates would result in certain state maintained in the Redis instances from being lost, I.E. transient storage of keys / items still replicating. Because of this, OnDelete is definitely the "safest" and most responsible update strategy.

**Comment by Aracki** [comment]
It makes sense! Thanks @DandyDeveloper 👍
