### ISSUE TITLE
Can't install a Chart

### ISSUE THREAD

**Issue by BaerSy** [helm/charts#18004]
Hello, Need your advise on installing a Chart. My kubernetes is 1.16.0. Helm is 2.14.3.  How can I fix this problem?

I tried to install a chart with  "helm install --dep-up --name hono --namespace hono eclipse-hono/", got some errors:
Error: validation failed: [unable to recognize "": no matches for kind "PodSecurityPolicy" in version "extensions/v1beta1", unable to recognize "": no matches for kind "Deployment" in version "apps/v1beta2", unable to recognize "": no matches for kind "Deployment" in version "extensions/v1beta1", unable to recognize "": no matches for kind "Deployment" in version "apps/v1beta1", unable to recognize "": no matches for kind "StatefulSet" in version "apps/v1beta1"]

**Comment by EricLemieux** [comment]
That chart isn't in this repository, but from their repository I can see that are having some issues with k8s 1.16, due to the [removal of deprecated apis](https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/)

This pr adds some notes for getting that chart working with 1.16
https://github.com/eclipse/hono/pull/1584/files
