### ISSUE TITLE
[stable/mediawiki] Add PodDisruptionBudget and make replicas configurable

### ISSUE THREAD

**Issue by nesl247** [helm/charts#18092]
**Is your feature request related to a problem? Please describe.**
Mediawiki should be highly available.

**Describe the solution you'd like**
Add a PDB so that there is a guarantee of 1 pod or more always, and allow the replica count to be configurable.

**Comment by juan131** [comment]
Hi @nesl247 

Thanks for your suggestions. I'm okay with adding the PDB to guarantee there's a minimum of pods always running. Please feel free to create a PR and I'll be glad to review it.

Regarding allowing more than one replica (ha), please note that this will only work if you're using a RWX PV (using a NFS provider or any other similar solution) since it's the only way to sync the Mediawiki data across the replicas.

**Comment by nesl247** [comment]
Yep, I am aware that using `nfs-server-provisioner`, or some other NFS provider, or some other sort of RWM PV would be required. Having the PDB and minimum replicas should be optional because by default this chart does not install `nfs-server-provisioner` or another compatible RWM PV.

Maybe doing that in the future would make sense though so that the default setup is a HA setup. Without this, it really isn't production ready IMO.

**Comment by juan131** [comment]
> Maybe doing that in the future would make sense though so that the default setup is a HA setup. Without this, it really isn't production ready IMO.

I totally agree with you!

Did you create a PR to add this feature (I just saw one to fix the issue with https port)? I can also do it if you're very busy, just let me know how I should proceed.

**Comment by nesl247** [comment]
I haven't tackled this because I can't get the chart to work (see my ticket about the DB migrations). Once I do, then I'll focus on getting the PDB working.

**Comment by juan131** [comment]
Great @nesl247 ! Let's try to fix the issue with the external db first.
