### ISSUE TITLE
[stable/grafana] When replica is > 1, login session is lost

### ISSUE THREAD

**Issue by clausa20** [helm/charts#18163]
When I set grafana replica for example in 3, then when I login, the session is lost during browsing.
Is there a way to persist the login session without using a database?

Thanks.

**Comment by Antiarchitect** [comment]
Same here - always redirects back to login. replicas: 2

**Comment by zanhsieh** [comment]
https://grafana.com/docs/tutorials/ha_setup/

**Comment by Antiarchitect** [comment]
@zanhsieh Official grafana guide is good. But the chart has no ability to set up a shared database. Has no docs about PVC / Statefulset storage difference, no way to use Redis for sessions with this chart. And even if you'll stick with the STS storage you'll need sticky sessions (also adding dashboards section is not full and explanatory - will try to fix it in some time)

**Comment by clausa20** [comment]
Hello, I tried to set up a memcached/redis and added in the grafana values.yaml for example:
```
grafana.ini:
....
  remote_cache:
      type: memcached
      connstr: memcached.devenv.svc.skydns.local:11211
```
but it is not working.
Is there some workaround for this?

@zanhsieh I didnt understand very well the problem, can you give little more detail. 
Thanks

**Comment by zanhsieh** [comment]
@clausa20 
Setting Grafana replica to 2+ literally is the same as to configure Grafana as high availability mode. To stablize this, we need to take the storage out of Grafana container and put some cache to ease the inquiry traffic. Currently Grafana chart has been configured as throw-able / openbox type of chart, which does not mean to store the state. That's why Grafana chart could move fast. 

If we open another line for Grafan HA chart, then certainly some users would think why Grafana chart could do this but not for Grafana HA. It's a tradeoff; any tradeoff comes with price. Hope you understand.
