### ISSUE TITLE
[stable/redis-ha]: announce services not created

### ISSUE THREAD

**Issue by groulot** [helm/charts#18190]
**Describe the bug**
After installing a redis-ha app with helm, the config-init container crashes and the redis-ha-server-0 pod never starts.

To my understanding, it is caused by the absence of the -announce services, which I believe should be created by Helm.

**Version of Helm and Kubernetes**:
Helm v2.15.0
Kubernetes 1.16.1
Cilium CNI v1.6.1

**Which chart**:
stable/redis-ha

**What happened**:
The test-redis-ha-server-0 pod is stuck in status Init:CrashLoopBackOff

The config-init container complains:
```
Initializing config..
Could not connect to Redis at test-redis-ha:26379: Name does not resolve
/readonly-config/init.sh: line 84: Could not resolve the announce ip for this pod: not found
```
The announce service does not exist, and therefore the code mentionned in https://github.com/helm/charts/issues/16911#issuecomment-529280098 for example cannot succeed.

**What you expected to happen**:
Helm to install announce services and the redis pods to start and run successfully.

**How to reproduce it** (as minimally and precisely as possible):
```
helm install --dry-run --debug --name redis stable/redis-ha > redis-debug
```
Open redis-debug, note that no "announce" service are present in the manifest.

**Comment by PaulFarver** [comment]
We've taken a look at this. It seems to be a problem with the replicas field
In `redis-ha-announce-service.yaml`, `{{ $replicas := int .Values.replicas }}` for some reason becomes 0, if .Values.replicas is already an integer. This is actually a problem in the statefulset manifest as well, where the same method is used to generate unique SENTINEL_ID's
This can be worked around by setting the replicas value to a string, since the int function does work on that type

**Comment by groulot** [comment]
Thanks ! I ended up creating the services but this should help next time I deploy a redis cluster.
