### ISSUE TITLE
[stable/influxdb] Crash Loop Back Off and "run: write-buffer-size must be greater than 0. To generate a valid configuration file run `influxd config > influxdb.generated.conf'"

### ISSUE THREAD

**Issue by Johann01** [helm/charts#18418]
**Describe the bug**
If I want to install the influxDB instance with helm under the following command: 
`helm install stable/influxdb`

I get the following errors from the kubectl describe command:
![image](https://user-images.githubusercontent.com/37617663/67763697-9374b780-fa48-11e9-9866-c306ae70c772.png)

And the following error from the kubectl logs command.
![image](https://user-images.githubusercontent.com/37617663/67763823-dafb4380-fa48-11e9-9bd9-7963c86b4eda.png)

**Version of Helm and Kubernetes**:
Helm version: v2.15.1
Kubernetes version: 1.12.8

**Which chart**:
stable/influxdb

**What happened**:
Described above

**What you expected to happen**:
The container is starting and not ending up in a CrashLoopBackOff

**How to reproduce it** (as minimally and precisely as possible):
Using Kubernetes Version 1.12.8 and use `helm install stable/influxdb`

**Anything else we need to know**:
If you need any more information feel free to ask! :)

**Comment by onnheimm** [comment]
I was having the same problem. It seems the template rendering of the configmap is not working properly: all values parsed as int64 become set to 0. I.e. the line

`cache-max-memory-size = {{ .Values.config.data.cache_max_memory_size | int64 }}`

in config.yaml becomes
 
`cache-max-memory-size = 0`

instead of the provided value in values.yaml

```
config:
  ...
  data:
    ...
    cache_max_memory_size: 1073741824
```

This is to probably due to https://github.com/helm/helm/pull/6010 and https://github.com/helm/helm/issues/6708. For me the problem disappears when upgrading helm from 2.15.0 -> 2.15.1.

**Comment by Johann01** [comment]
Thank you so much! 
The issue is solved.
I don't know how many hours I was looking into this! 😅
