### ISSUE TITLE
[stable/redis] Support Replica for Redis Master if cluster.enabled is set to False

### ISSUE THREAD

**Issue by vankhoa011** [helm/charts#18713]
Hi folks,
Thanks for developing the chart.  In some cases, I don't want to setup Redis cluster ( Master/Slave ) . I just want a standalone Redis which it's easy to deploy and scale. 

However, our Redis chart doesn't support `replica` to add more pods if we set `cluster.enabled` to false. So I would like to do a PR to support it. 

How do you think about this feature ? I would like to hear feedback from you.  Thank you in advance.

**Comment by juan131** [comment]
Hi @vankhoa011 

Thanks so much for your feedback.

This chart (`stable/redis`) doesn't support master-master architecture (what is kwon as [Redis Cluster](https://redis.io/topics/cluster-tutorial)). Therefore, you cannot increment the number of replicas since thew new replicas will act as independent individuals.

**Comment by vankhoa011** [comment]
Hi @juan131  . Oh I see. But It's not master-master architecture. it's just redis standalone which can scale.

**Comment by vankhoa011** [comment]
So I'm going to close the ticket because the helm chart doesn't support standalone redis.
