### ISSUE TITLE
Sentry Admin Credentials Not Being Preserved

### ISSUE THREAD

**Issue by stevenpall** [helm/charts#1872]
**Is this a request for help?**:

Yes

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

Bug report

**Version of Helm and Kubernetes**:

Kubernetes: 1.7
Helm: 2.6.0

**Which chart**:

sentry

**What happened**:

In `sentry/templates/secrets.yaml`, the following logic exists:
```
data:
  {{ if .Values.sentrySecret }}
  sentry-secret: {{ .Values.sentrySecret | b64enc | quote }}
  {{ else }}
  sentry-secret: {{ randAlphaNum 40 | b64enc | quote }}
  {{ end }}
```
This works well when you install the chart, (`helm install --wait stable/sentry`), however on upgrade (`helm upgrade stable/sentry`), `randAlphaNum 40 | b64enc | quote` sets a new Sentry admin password. At this point, `sentry-web`, `sentry-worker`, and `sentry-cron` pods fail to start.

**What you expected to happen**:

The password should be preserved across upgrades.

**How to reproduce it** (as minimally and precisely as possible):

- `helm install --wait stable/sentry`
- confirm login is working
- `helm upgrade stable/sentry`
- Check status of sentry pods (they should be failing to start)

**Anything else we need to know**:

N/A

**Comment by mrgleeco** [comment]
le'ouch!  I just got bit by this -and it hurt. 
Actually, not the same val, but a`user-password` 
nb https://github.com/kubernetes/charts/blob/master/stable/sentry/templates/secrets.yaml#L18

always hardcoded - 2 strikes and you're out?!

any love for this?

**Comment by lotas** [comment]
/reopen

I happen to have almost the same problem as described above.
initial Installation works fine. But upgrade always fails, because some passwords are being renegerated every time.

Found a workaround of providing values like this:

```
helm upgrade --install --wait efi-sentry -f values.yaml stable/sentry \
  --namespace sentry \
  --set email.password=$(kubectl get secret --namespace sentry efi-sentry -o jsonpath="{.data.smtp-password}" | base64 -D) \
  --set user.password=$(kubectl get secret --namespace sentry efi-sentry -o jsonpath="{.data.user-password}" | base64 -D) \
  --set postgresql.existingSecret=efi-sentry-db
```

Note that `postgres` was also regenerating password each time, so I had to create a new secret with db password, to be able to reuse it later.

Still, `web/worker/cron` pods fail to start, dying with `invalid password` when connecting to db. Password is 100% working, checked manually from the postgres container, externally by creating simple python script to connect to.

Does anyone know a workaround?
