### ISSUE TITLE
[stable/concourse] Move concourse chart out of this repo

### ISSUE THREAD

**Issue by taylorsilva** [helm/charts#18781]
Given https://github.com/helm/helm/issues/5892 stating that this repo will be deprecated in Helm 3, the Concourse team wants to move the concourse chart out of this repo and over to our own git repo and chart repository.

We've already migrated the contents and history of `stable/concourse` over to https://github.com/concourse/concourse-chart and have a PR to add our chart repo to Hub (https://github.com/helm/hub/pull/174).

What steps, if any, should we take to remove `stable/concourse` from the Helm Charts repo? Should we PR the deletion of that directory? Thanks!

cc @cirocosta @YoussB

**Comment by cirocosta** [comment]
👍  👍  

> What steps, if any, should we take to remove stable/concourse from the Helm Charts repo? Should we just PR the deletion of that directory? Thanks!

that might be a good thing to let other maintainers know too - a "migration guide" or something for those deprecating their charts from this repo

**Comment by scottrigby** [comment]
Hey gang, thanks for this issue. 

Re this note from helm/helm#5892:
>The Helm official Charts repository is deprecated. It will be replaced by Helm Hub which is an aggregator for different chart hosts.

See this issue for more detailed info: https://github.com/helm/charts/issues/16720#issuecomment-557250945

Even so, yes, we're working with people to help move to distributed Helm repos. Since the concourse hub PR was merged and is already at https://hub.helm.sh/charts/concourse, the process for de-listing the stable/concourse chart in this git repo is here: https://github.com/helm/charts/blob/master/PROCESSES.md#deprecating-a-chart. Follow https://github.com/helm/charts/issues/7800 for clarifying this process in the README.
