### ISSUE TITLE
[stable/sentry] Does `helm upgrade` work?

### ISSUE THREAD

**Issue by seanarnold** [helm/charts#18791]
I see in [the README](https://github.com/helm/charts/blob/master/stable/sentry/README.md) that `helm upgrade` may not be supported:
> Warning: This Chart does not support helm upgrade an upgrade will currently reset your installation

What does `reset your installation` mean? Will this result in data loss?

If so, what needs to be done to get `helm upgrade` working as expected?

**Comment by seanarnold** [comment]
@okgolove can you help here?

**Comment by okgolove** [comment]
Hi @seanarnold.

This is written in the README because there are [random generated password](https://github.com/helm/charts/blob/master/stable/sentry/templates/secrets.yaml#L23) in the templates.
You can check an [issue](https://github.com/helm/charts/issues/11879).

**Comment by seanarnold** [comment]
Thanks for the reply @okgolove .

From at file you linked, it looks like it will only generate password if a password isn't given via the `values.yaml`: https://github.com/helm/charts/blob/master/stable/sentry/templates/secrets.yaml#L20-L24

Does this mean that `helm upgrade` _will_ work if both the `sentrySecret` and `user.password` are given?

**Comment by okgolove** [comment]
It does.

**Comment by seanarnold** [comment]
@okgolove There's still the issue where Postgresql will re-create a password on an upgrade.

Is there any reason why we don't allow the Postgresql password to be passed manually like the Postgresql chart does?

We could do something like this:
```
  {{ if or (not .Values.postgresql.enabled) (.Values.postgresql.postgresqlPassword) }}
  postgresql-password: {{ .Values.postgresql.postgresqlPassword | default "" | b64enc | quote }}
  {{ end }}
```

This is similar to what Postgresql allows on their chart directly:
https://github.com/helm/charts/blob/master/stable/postgresql/templates/_helpers.tpl#L80-L91

**Comment by okgolove** [comment]
As far as I remember postgresql and redis they had had the same idea we have now in Sentry chart earlier.
And they have been changed.

**Comment by OKNoah** [comment]
After a day or two of trying to use this chart--first trying to set smtp/email stuff during install, then installing without any values and trying to `upgrade` with the new values--this is what I think is necessary: you must set `redis.password`, `postgresql.postgresqlPassword` and (in my case) `email.password`. _Importantly, any `existingSecret` and `existingSecretKey` combo will not work_. That goes for `email`, `redis` and `postgresql` prefixed stuff. Mind you, perhaps only one of these was the problem, but not until I entered the passwords for all of them was I able to upgrade. I also set

```
 --version 4.0.1 \
 --wait
```

**Comment by MBarendregt** [comment]
For those of you still struggling, for me also the solution provided by OKNoah didn't help, I ended up doing the following:
**Setup**
Kubernetes 1.15 on GKE
sentry helm chart 0.14.0 
sentry version 8.22

**Setup after upgrade**
sentry helm chart 4.3.0 
sentry version 9.1.2

Before I started I made backups of my current pvcs  

- I did a sentry export of my current environment by exec into the web container
- Since export can't be imported one on one as a whole (there is an order in which it should be imported) I ended up writing a script that extracted all the useful files and stored them in separate json files. 

Example script:
```python
teams = []
orgmember = []

existing_users = ["user1@example.com", "user2@example.com"]

with open('oldexport.json') as json_file:
    data = json.load(json_file)
    for data_entry in data:
        if data_entry["model"] == "sentry.team":
            teams.append(data_entry)
            with open('1-teams.json', 'w') as outfile:
                json.dump(teams, outfile)

        if data_entry["model"] == "sentry.organizationmember":
            for users in data_entry["fields"]["user"]:  ## Check for existing users, because dump will also give back already deleted users
                if users in existing_users:
                    orgmember.append(data_entry)
            with open('8-orgmembers.json', 'w') as outfile:
                json.dump(orgmember, outfile)
```
- import order:
     - sentry.team
     - sentry.project (remove pk1, because that is the default), also needed to remove team fields for now
     - sentry.projectkey 
     - sentry.project (again, this time with team) 
     - sentry.projectteam
     - sentry.email 
     - sentry.user
     - sentry.organizationmember
     - sentry.useremail
     - sentry.counter (not sure what this did though..) 
     - sentry.projectoption 
     - sentry.rule
     - sentry.useroption  
- Copy all those files to the new web-container and do a sentry import per file 

**This will result in historical data loss, but will keep all the DSNs, securitytokens, webtokens etc in place** 
**This will also result in the loss of personal access tokens (auth tokens), which I was not able to import again** 

Hope this helps to for some of you
