### ISSUE TITLE
[stable/redis-ha] Add configurable service type

### ISSUE THREAD

**Issue by tobiaskohlbau** [helm/charts#19021]
**Is your feature request related to a problem? Please describe.**
The user should be able to configure service type for the published services.

**Describe the solution you'd like**
Add templating in the helm chart to configure service type. Default value should be the same as now to not break any existing users.

**Describe alternatives you've considered**

**Additional context**
I noticed that it's not possible  to use the redis-ha cluster in external solutions by setting for e.g. internal load balancers. In order to support this it would be great to enable annotiations and type on the published services.

**Comment by DandyDeveloper** [comment]
Presumably you're referring to the standalone side of Redis? 

If so, how do you expect this to work with Sentinel in place? The issue here is, although yes you can expose Sentinel and Redis via a LoadBalancer service, Sentinel will only ever display the internal K8 IP for the Redis master, this will not work in practice. 

That is why the HAProxy was implemented, this does support what you seem to want to achieve. 

Can you explain the use case if the above does not work for you?

**Comment by tobiaskohlbau** [comment]
I'm referring to the standalone side of redis, yes.

I was not aware of the structure between Sentinel and Redis. I've read a bit more and got your point that the Sentinel is publishing the internal IPs to the client.

I've ran into some troubles and wanted to preclude that the HAProxy is not the reason for my issues. But as I noticed by your hints my idea is neither possible nor good.

Sorry for bothering you and your time. I will try to identify my issues and have a closer look if HAProxy is really involved in the connection aborts. By now I'm very sure it's more of an client issue than on the Redis/Sentinel part.
