### ISSUE TITLE
[stable/prometheus-operator] naming of objects

### ISSUE THREAD

**Issue by omitrowski** [helm/charts#19051]
**Is your feature request related to a problem? Please describe.**
a human readble naming of objects, that does not exceed 63 chars
A PVC name like `prometheus-prometheus-prometheus-db-prometheus-prometheus-prometheus-0` has no useful information. It burns in my eyes and is not compatible with OpenEBS, that does support max 63 chars. Accordingly my PVC remains in status pending and I need to somehow fix the chart as workaround.

**Describe the solution you'd like**
a name like `prometheus-db-0`

**Describe alternatives you've considered**
there are alternatives to Prometheus??

**Additional context**
![image](https://user-images.githubusercontent.com/19892452/69356622-0ce87a00-0c84-11ea-8de1-2e17efeeae45.png)

![image](https://user-images.githubusercontent.com/19892452/69356953-94ce8400-0c84-11ea-905d-0d60635720c8.png)

**Comment by vsliouniaev** [comment]
The prometheus operator chart follows resource naming guidelines specified by this repository when the chart was created:
- The core resourced are named `<RELEASENAME>-<CHARTNAME>`, which arises so that the same chart can be installed multiple times without resource clashes
- If the chart has multiple components, then the component must be suffixed to this in `<RELEASENAME>-<CHARTNAME>-<COMPONENT>`

At this point, depending on what you named your release you would already be at a `prometheus` resource being named `my-release-prometheus-operator-prometheus`.

From there, you start to get the prometheus operator involved, which also prefixes `prometheus` onto the front of the statefulset generated from the `prometheus` resource, which gives you `prometheus-my-release-prometheus-operator-prometheus`. The operator and the PVC controller get involved here and generate the PVC name that includes that duplicated string with the `db` in the middle, which I'm not certain of the details of.

You are able to use the `fullnameOverride` chart value to replace the value of`<RELEASENAME>-<CHARTNAME>`, so you could get `my-override-prometheus` for the `prometheus` resource and have a much shorter PVC name.
