### ISSUE TITLE
[stable/ambassador] Move chart to another namespace

### ISSUE THREAD

**Issue by rpocase** [helm/charts#19190]
With the charts project in active deprecation, moving the ambassador chart to another namespace (presumably [datawire](https://github.com/datawire)) before any additional changes are made would be ideal. 

**Additional context**
I started working towards including ambassador in my project but saw it did not support helm 3. I am willing to help enable helm 3 support in the upstream chart, but doing so in this project seemed not ideal since CRD rework may require non-trivial coordination.

**Comment by nbkrause** [comment]
@rpocase We recently merged a PR that allows CRD installation with Helm 3 with Ambassador. We still need to figure out how to move and maintain the chart under the https://github.com/datawire org but until then you can still install releases from this repository. 

Make sure you add the `"stable"` repository to your helm repo list since it is no longer included by default 

```
helm repo add stable https://kubernetes-charts.storage.googleapis.com
```

**Comment by rpocase** [comment]
Still needs to happen at some point. Preferably before May, but November will be the hard cutoff.

**Comment by rpocase** [comment]
I think this is basically done now with at datawire/ambassador-chart. The only thing that really needs to happen now is a deprecation notice with redirect in stable/charts/ambassador.
