### ISSUE TITLE
Document how to add stable repo

### ISSUE THREAD

**Issue by oke-py** [helm/charts#19279]
**Is your feature request related to a problem? Please describe.**
Helm 3 does not install `stable` repo by default, and so user must run command:
```
helm repo add stable https://kubernetes-charts.storage.googleapis.com
```
However, I can't remember the URL.

**Describe the solution you'd like**
This should be documented in README of this repo.
I know it is documented in https://helm.sh/docs/intro/quickstart/ , but it is useful if it is also documented in this repo README.

**Describe alternatives you've considered**
https://helm.sh/docs/intro/quickstart/ is enough? 

**Additional context**

**Comment by erendrake** [comment]
Thanks for the documentation. this helped me!

**Comment by hphde** [comment]
With adding the stable repo you'll have the old search capabilities back (even if still ugly because of the hidden tab-regex problem).

After adding the repo as above you can search like before:
`helm search repo -l -r '\vstable/prometheus\v'`

Or use JSON:
`helm search repo -l -o json|jq -r '.[]|select(.name == "stable/prometheus")|.version'`

**Comment by KlavsKlavsen** [comment]
its none sensical to me - that I can do helm search hub metallb.. but then I can't actually install things from hub..  and the url given to install things from the hub (stable f.ex.) is completely different from the url I get in my search?
