### ISSUE TITLE
[stable/prometheus] append to list of scrap_configs[<job name>].relabel_configs

### ISSUE THREAD

**Issue by naseemkullah** [helm/charts#19471]
**Is your feature request related to a problem? Please describe.**
I am very happy with the out of the box relabel_configs for kubernetes-service-endpoints (and others) ... but I would like to add extra relabelling config such as:
```
#### added to improve redis dashboard instance dropdown ####
          - source_labels: [__meta_kubernetes_service_name]
            target_label: instance
            regex: (.*redis.*)
            replacement: $1
```
without affecting the upstream out of the box relabel configs. Since it is provided as a list within `prometheus.yml`, I need to include its entirety to be able to add this addition relabelling. Is there a keep my values file more lean and in sync with upstream relabelling config?

**Describe the solution you'd like**
A value to append to already existing lists of relabelling configs.

**Describe alternatives you've considered**
Include the entirety of the scrap_configs in my values file and just add my extra relabelling.

extraScrapeConfigs would be for additional job_names, but the job_name I need already exists (kubernetes-service-endpoints in this example)

**Additional context**
Please let me know if anything is unclear.

**Comment by naseemkullah** [comment]
cc @gianrubio @zanhsieh

**Comment by pdambrauskas** [comment]
This would be really useful feature for me too.

**Comment by naseemkullah** [comment]
I'm going to open an issue again for this.

**Comment by naseemkullah** [comment]
Yep, we need this. I will see if I can come up with a PR.

**Comment by naseemkullah** [comment]
@zanhsieh Do you have any ideas of how to implement this? There is A LOT of templating going on in that configmap, but hopefully this is possible.

**Comment by pdambrauskas** [comment]
I guess whole `prometheus.yml` value is loaded there https://github.com/helm/charts/blob/master/stable/prometheus/templates/server-configmap.yaml#L37
I don't see any easy way to plug custom relabeling (except for the last job), since whole `prometheus.yaml` value is treated as one huge chunck. 
Only option I can think of is moving job definitions level up in values.yaml file, and adding something like:
```yaml
scrape_configs:
{{- range $key, $value := .Values.server.jobs }}
   - job_name: {{ $key }}
    ...
   relabel_configs: 
{{- range $rule := .Values.server.jobs }}
      - relabel_configs:
        ....
{{- end }}
{{- end }}
```
but this kind of change wouldnt be backwards compatible..

**Comment by naseemkullah** [comment]
Thanks @pdambrauskas that makes sense!


@zanhsieh @gianrubio  Can we make a PR?

Really comes in handy for situations such as https://github.com/oliver006/redis_exporter/pull/344#issuecomment-588041607

**Comment by desaintmartin** [comment]
Hello,
I doubt it should be in prometheus-operator helm chart.
On the contrary, a PR on stable/redis would perfectly make sense (https://github.com/helm/charts/blob/master/stable/redis/templates/metrics-prometheus.yaml), since you can set relabelling in a ServiceMonitor (https://github.com/coreos/prometheus-operator/blob/master/Documentation/api.md#endpoint).

**Comment by naseemkullah** [comment]
Good to know prometheus-operator has this workaround @desaintmartin , what about the vanilla prometheus chart though? Can this be done outside of the prometheus config?

**Comment by naseemkullah** [comment]
@pdambrauskas  would you be willing to open a PR for the prometheus chart if there is no similar workaround as prometheus-operator's ServiceMonitor?

**Comment by desaintmartin** [comment]
I can't see any obvious way to do it through prometheus-operator itself, but I can't be wrong...

**Comment by naseemkullah** [comment]
Hi @desaintmartin I actually mean the regular old prometheus chart (not operator).
