### ISSUE TITLE
Presto for interactive SQL

### ISSUE THREAD

**Issue by sumchak22** [helm/charts#19831]
Our requirement to use presto to access COS data. We have installed presto helm chart on our k8s cluster but not able to configure COS connection with it. Could you please help me to understand what are the steps need to be followed for using presto for interactive SQL connecting to COS data. 

```
kubectl get pod 

my-release-presto-coordinator-6f64697bbc-llb7p      2/2     Running     0          9d
my-release-presto-worker-6857797df8-9qw6b           2/2     Running     6          9d
my-release-presto-worker-6857797df8-bbhp4           2/2     Running     6          9d
my-release-presto-worker-6857797df8-nwv9p           2/2     Running     6          9d
my-release-presto-worker-6857797df8-qgf9x           2/2     Running     0          9d

kubectl exec -it my-release-presto-worker-6857797df8-9qw6b -- /bin/bash               

presto@my-release-presto-worker-6857797df8-9qw6b:/$ presto
presto> show catalog
     -> ;
Error running command: Error starting query at http://localhost:8080/v1/statement returned an invalid response: JsonResponse{statusCode=404, statusMessage=Not Found, headers={cache-control=[must-revalidate,no-cache,no-store], content-length=[244], content-type=[text/html;charset=iso-8859-1], date=[Thu, 02 Jan 2020 12:59:49 GMT]}, hasValue=false} [Error: <html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
<title>Error 404 Not Found</title>
</head>
<body><h2>HTTP ERROR 404</h2>
<p>Problem accessing /v1/statement. Reason:
<pre>    Not Found</pre></p>
</body>
</html>
]

```

**Comment by sumchak22** [comment]
any update on this ?

**Comment by shawnzhu** [comment]
> Could you please help me to understand what are the steps need to be followed for using presto for interactive SQL connecting to COS data.

Assuming you're talking about a S3api compatible object storage service when saying _COS_. In the context of prestosql,  you will need a connector like [Hive Connector](https://prestosql.io/docs/current/connector/hive.html#amazon-s3-configuration) with S3 configuration so that presto can scan data in an object storage. Take [this article](https://blog.minio.io/presto-modern-interactive-sql-query-engine-for-enterprise-ce56d7aea931) for instance, it shows how to query data on a minio backed object storage by presto.

It will need some work to configure a connector for the chart `stable/presto`.

**Comment by shawnzhu** [comment]
I plan to fix this issue by:

1. Uses official container image `prestosql/presto` so that it contains required connector `hive-hadoop2` - #20404 
1. Add new variables to `values.yaml` so that it can configure custom connectors by using `values.yaml`. (either embedded connectors config or a k8s secret)

Then I can alternate my private helm chart for prestosql with this one after PRs get merged.
