### ISSUE TITLE
stable/postgresql Fails chown NFS mounted volume

### ISSUE THREAD

**Issue by krufab** [helm/charts#19921]
**Describe the bug**
stable/postgresql uses an initContainer to chown the files in the postgres/data folder. However, the script does chown ALSO the postgresql/data folder. This leads to a failure in the initialisation process when the postgresql/data folder is a PV from a NFS server which uses [`no_root_squash` option](https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/4/html/Security_Guide/s2-server-nfs-noroot.html) and the mounted folder belongs to a different user than postgresql, which is normally the case.
The actual script uses `find (...) -mindepth 0  (...) | xargs chown -R (...)` which exits with an error if it cannot chown the parent folder (due to `-mindepth 0`). It was introduced in [#17154](https://github.com/helm/charts/pull/17154)
A better approach would be to use `find (...) -mindepth 0  (...) -exec chown -R (...) {} \;` which completes successfully even if it is not able to change ownership of a folder / file (there is only a warning message).

**Version of Helm and Kubernetes**:
Helm: v3.0.0
Kubernetes: v1.17

**Which chart**:
stable/postgresql: v8.1.2

**What happened**:
The initContainer fails to if it cannot change ownership of the mounted folder

**What you expected to happen**:
The initContainer should either not try to change ownership of the parent folder (anyways postgresql doesn't require it) or continue in case of failure. The main container will fail anyways if there is any issue with file permissions / ownerships etc

**How to reproduce it** (as minimally and precisely as possible):
- Have both `.Values.volumePermissions.enabled .Values.persistence.enabled` enabled
- Set both `.Values.securityContext.runAsUser .Values.securityContext.fsGroup` to 999 (postgresql default user and group)
- Have a PV from a NFS with `no_root_squash` option enabled and folder owner i.e. nobody:nobody
- Install the chart and see initContainer fail

**Comment by alemorcuq** [comment]
Hi, @krufab.

The postgresql container does need permissions on the parent folder. See for example this line (https://github.com/bitnami/bitnami-docker-postgresql/blob/master/11/debian-9/rootfs/libpostgresql.sh#L739) that lets the container now that the init scripts have already been executed.

The only concern I have with your proposed change is that it may "mask" an error in the sense that a user may think that, since the init container succeeded, everything is going to work while the init scripts feature may not work. But I also think that working sometimes is better than never working.

**Comment by krufab** [comment]
Solved by #20479
