### ISSUE TITLE
[stable/mongodb] additional options for side car container

### ISSUE THREAD

**Issue by Hartorn** [helm/charts#20022]
**Is your feature request related to a problem? Please describe.**

We are using MongoDB in our chart, and wanted to use official helm chart as dependency.
But we are using filebeat as sidecar container to centralize the logs towards a logstash.

**Describe the solution you'd like**
An idea would be to add some additional options, such as the ones used in [stable/kibana](https://github.com/helm/charts/tree/master/stable/kibana) or [stable/nginx-ingress](https://github.com/helm/charts/tree/master/stable/nginx-ingress)
* extraContainers
* extraVolumeMounts
* extraVolumes
* extraConfigMapMounts
* ...

That way, a sidecar could be added, with a volume such as an emptyDir between the two containers.

I could make a PR on this if the pattern is ok

**Describe alternatives you've considered**
No idea :(

**Comment by alemorcuq** [comment]
Hi, @Hartorn.

It would be great if you sent us a PR implementing this feature! The pattern seems good to me, and we have it implemented in several charts (see [bitnami/mongodb-sharded](https://github.com/bitnami/charts/tree/master/bitnami/mongodb-sharded) for instance).

Just a couple of comments: note that instead of `extraContainers`, we are using `sidecars` as the name of the property, so I would use that instead for consistency. Also, I don't really see the point in adding `extraConfigMapMounts` since ConfigMaps are mounted as volumes so you could use `extraVolumeMounts` for that.

Thank you very much for volunteering to contribute!

**Comment by Hartorn** [comment]
Hi @alemorcuq

I made a PR #20097 
Feel free to have a look, and please tell me if this is ok, then I will do the second chart
