### ISSUE TITLE
[stable/chart/airflow] Airflow helm template failure

### ISSUE THREAD

**Issue by jakepaw** [helm/charts#20248]
When installing Airflow I am receiving an error shown below. I understand I need to run a helm repo update or helm dep update but since I am installing via Rancher (just as a POC) instead of using the cli. 

ERROR:

```
wait helm template failed. Error: found in requirements.yaml, but missing in charts/ directory: postgresql, redis
```

**Version of Helm and Kubernetes**: Kubernetes: v1.16.3

**Which chart**: Airflow

**What happened**: Need to run a pre-spawn command but not sure how

**What you expected to happen**: to auto helm upgrade by itself

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by carrodher** [comment]
This is something related to Rancher itself and not the chart. You will need to run `helm dep update` or `helm dep build` before pushing the chart to your repository. Running those commands a `chart/` folder should appear with the compressed sub-charts.

I think in this case you need to contact the Rancher team because it is not an issue in the chart itself.
