### ISSUE TITLE
[stable/mediawiki]

### ISSUE THREAD

**Issue by toonsevrin** [helm/charts#20278]
**Describe the bug**
When I install mediawiki on my kubernetes cluster with helm, it does not create a separate mariadb server/pod?
```
kubectl logs -n mediawiki-deployer-16445270-staging wiki-mediawiki-7b87ddb8b7-xt2v5

Welcome to the Bitnami mediawiki container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mediawiki
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mediawiki/issues
Send us your feedback at containers@bitnami.com

WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
nami    INFO  Initializing apache
nami    INFO  apache successfully initialized
nami    INFO  Initializing php
nami    INFO  php successfully initialized
nami    INFO  Initializing mysql-client
nami    INFO  mysql-client successfully initialized
nami    INFO  Initializing mediawiki
mysql-c INFO  Trying to connect to MySQL server
Error executing 'postInstallation': Failed to connect to wiki-mariadb:3306 after 36 tries
```
It appears like a mariadb pod is never created?

**Which chart**:
stable/mediawiki

**What you expected to happen**:
For a mariadb instance to be automatically created (as the .Values.mariadb.enabled defaults to True).

**How to reproduce it** (as minimally and precisely as possible):
Just install mediawiki through the recommended procedure.

**Comment by sameersbn** [comment]
@toonsevrin Firstly, can you check if the mariadb pods are created? If yes, please check if they are in the running state and check the mariadb container logs to check if any errors are being encountered.

If you notice that the mariadb pod is in `CrashLoopBackOff` state, then it's possible that the pod is reusing the PVC from a earlier deployment for the persistent storage. If that is the case, please delete the mediawiki deployment and any associated PVCs and retry.

--- 

In order to know what could be going wrong, please share the steps you followed to install the chart and the k8s environment in use. For example on a minikube I am able to test install the chart with 

```
helm install wiki stable/mediawiki \
--set service.type=NodePort \
--set service.nodePorts.http=30080 \
--set mediawikiHost=$(minikube ip):30080
```

**Comment by toonsevrin** [comment]
Hi @sameersbn thank you for the quick response, my environment is sadly enough not present anymore. If this behavior is not supposed to occur then we can close this issue.

No pods where created btw, not even in BackOff state.
