### ISSUE TITLE
[stable/verdaccio] failed to download?

### ISSUE THREAD

**Issue by chrissound** [helm/charts#20286]
```
$ helm repo update
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "jetstack" chart repository
Update Complete. ⎈ Happy Helming!⎈ 

$ helm install --namespace=npm-verdaccio npm-registery-verdaccio stable/verdaccio
Error: failed to download "stable/verdaccio" (hint: running `helm repo update` may help)
```

**Version of Helm and Kubernetes**:
```
helm version    
version.BuildInfo{Version:"v3.0.2", GitCommit:"19e47ee3283ae98139d98460de796c1be1e3975f", GitTreeState:"clean", GoVersion:"go1.13.5"}
kubectl version                                                                            
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.6", GitCommit:"7015f71e75f670eb9e7ebd4b5749639d42e20079", GitTreeState:"archive", BuildDate:"1970-01-01T00:00:01Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:09:08Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by alberto56** [comment]
Same here.

I am using [Helm on Docker](https://github.com/alpine-docker/helm).

My helm alias looks like:

    alias helm='docker run -e KUBECONFIG="/root/.kube/config:/root/.kube/digitalocean-tutorial-kubeconfig.yaml:/root/.kube/helm-drupal-issue-kubeconfig.yaml" -ti --rm -v $(pwd):/apps -v ~/.kube:/root/.kube -v ~/.config/helm:/root/.config/helm -v ~/.helm:/root/.helm alpine/helm'

I cannot install a chart from here though:

    $ helm version
    version.BuildInfo{Version:"v3.1.1", GitCommit:"afe70585407b420d0097d07b21c47dc511525ac8", GitTreeState:"clean", GoVersion:"go1.13.8"}
    $ helm repo add stable https://kubernetes-charts.storage.googleapis.com
    "stable" has been added to your repositories
    $ helm install my-first-vanilla-drupal stable/drupal
    Error: failed to download "stable/drupal" (hint: running `helm repo update` may help)
    $ helm repo update
    Hang tight while we grab the latest from your chart repositories...
    ...Successfully got an update from the "stable" chart repository
    Update Complete. ⎈ Happy Helming!⎈ 
    $ helm install my-first-vanilla-drupal stable/drupal
    Error: failed to download "stable/drupal" (hint: running `helm repo update` may help)

**Comment by alberto56** [comment]
So in my case I was using Helm on Docker and had to fix which volumes I was sharing between my host and my container. For helm charts in repos to work correctly, ~/.cache/helm and ~/.config/helm need to be shared.

Here are the changes to how I'm using helm on Docker:

* https://github.com/alpine-docker/helm/pull/17/files
* https://github.com/alpine-docker/helm/pull/18/files

This is required from what I understand starting in Helm 3.

@chrissound can you please confirm that you are using helm on docker and that your helm command is an alias (not locally installed), possibly in your ~/.bash_profile file. If so you might want to add:

    -v ~/.config/helm:/root/.config/helm -v ~/.cache/helm:/root/.cache/helm

If not, then your problem is not related to mine.
