### ISSUE TITLE
SVG show issue in hub.helm.sh

### ISSUE THREAD

**Issue by daixiang0** [helm/charts#20304]
SVG image cannot show as expected in https://hub.helm.sh, like https://hub.helm.sh/charts/stable/rocketchat:
```
stable/rocketchat$ grep icon Chart.yaml 
icon: https://raw.githubusercontent.com/RocketChat/Rocket.Chat.Artwork/master/Logos/icon.svg
```

If there is a limit about image file type, should document it i think.

**Comment by daixiang0** [comment]
@juan131 @lachie83 mind have a look?

**Comment by juan131** [comment]
Hi @daixiang0 

I guess it could be related with the extension `.svg` since most charts use `.png` and they're correctly rendered. I am afraid I am not maintaining the Helm Hub, therefore I can't help you with this.

By the way, it seems that Kubeapps Hub is also unable to render your icon (see https://hub.kubeapps.com/charts/stable/rocketchat)

**Comment by daixiang0** [comment]
That seems a bug indeed.
Thanks @juan131, could you ping a maintianer of the Hem Hub, i am not familiar with them.

**Comment by juan131** [comment]
cc @mattfarina @unguiculus

**Comment by daixiang0** [comment]
Need to fix.

**Comment by daixiang0** [comment]
keep
