### ISSUE TITLE
EFS resizing

### ISSUE THREAD

**Issue by ryan-gontarek** [helm/charts#20520]
AWS EFS Storage Provisioner

**Is your feature request related to a problem? Please describe.**
When I try to resize the storage capacity I get "Error: UPGRADE FAILED: persistentvolumeclaims "minecraft-minecraft-datadir" is forbidden: only dynamically provisioned pvc can be resized and the storage class that provisions the pvc must support resize.

**Describe the solution you'd like**
The ability to resize the pvc volume.

**Comment by tomaszszlek** [comment]
Hi, 

it seems that capacity is ignored anyways, see:
![image](https://user-images.githubusercontent.com/9800429/76836961-fae1a700-6831-11ea-8d31-cdaf9ac9c163.png).
However I think that EFS provisioner should allow to update capacity (it won't resize physical volume because EFS is unlimited by design) but only update descriptor. The reason is that some metrics/alerts are based on information about capacity and sometimes might be useful to update this value even if it doesn't take any effect on EFS itself.

**Comment by amleshk66** [comment]
I am also facing same issues.. unable to resize the AWS EFS Volume it giving below error.. can anyone please suggest on this.
I have Already configure AWS EFS CSI in my EKS Cluster.

ISSUES : only dynamically provisioned pvc can be resized and the storageclass that provisions the pvc must support resize.
