### ISSUE TITLE
[stable/pgadmin] SMTP Error when changes password

### ISSUE THREAD

**Issue by mfbrj** [helm/charts#20563]
**Describe the bug**
When user tries to change the password from right upper menu, a SMTP Error is shown.

**Version of Helm and Kubernetes**:
Kubernetes 1.17.2

**Which chart**:
stable/pgadmin image version 4.17
Template version: 1.1.3

**What happened**:
User can't change his password due this SMTP Error: 
![image](http://imgur.com/9bOZvaWl.png)

**What you expected to happen**:
User password changed.

**How to reproduce it** (as minimally and precisely as possible):
1. Log in as any user
2. Try to change user password from upper right corner menu
3. Fill fields on form and click Change password.
4. See the error.

**Anything else we need to know**:
That error didn't occur on pgadmin 4.15.

**Comment by rowanruseler** [comment]
This is currently correct, within version 4.16 of the docker image they implemented the user pgadmin to be used. This is causing the following issue:
```
postfix: error: to submit mail, use the Postfix sendmail command
postfix: fatal: the postfix command is reserved for the superuser
```

The issue was already reported here: https://redmine.postgresql.org/issues/5076

If you adjust your image towards: dpage/pgadmin4:postfix_test it should be working. I'm waiting for version 4.18 release that will most likely have this bug fix.

**Comment by fredbeltrao** [comment]
I adjusted to the new image 4.18 and worked. I gonna close since it wasn't a chart bug.
