### ISSUE TITLE
stable/redis - configuring for use outside of cluster

### ISSUE THREAD

**Issue by kbirger** [helm/charts#21186]
**Is your feature request related to a problem? Please describe.**
I want to set up a redis-sentinel cluster in my k8s environment which is accessible outside of the cluster. Currently, sentinel is announcing cluster IPs and ports, which means that when sentinel resolves the server I must use when connecting from outside (NodePort), my client cannot connect to the master. I am able to add "announce-port" to the sentinel config map, but the IPs are still incorrect

**Describe the solution you'd like**
Either documentation provided for how to achieve this, or some sort of solution that would cause each sentinel container to configure itself to announce it's Node IP / Port

**Comment by miguelaeh** [comment]
Hi @kbirger ,
If I understand this correctly your issue is that the sentinel announces the internal Pods IPs that are not reachable from the outside right?
I want to share with you that we are working on a new topology that will not need the sentinel as it uses the Redis cluster topology. This new topology will need to setup a LoadBalancerIP for every Pod to be accessed from the outside.

**Comment by kbirger** [comment]
Are you by chance referring to the redis-ha chart?

Also, to my understanding, sentinel is superior to cluster in terms of number of resources needed and robustness. Why do you want to use the cluster solution? And I'm not clear, does your solution require a load balancer?
