### ISSUE TITLE
[stable/jenkins]  It appears that your reverse proxy set up is broken

### ISSUE THREAD

**Issue by GoDllkE** [helm/charts#21194]
**Describe the bug**
Got a problem where all incoming for jenkins is redirected to the port 8000. By that, if I call "jenkins.myserver.com", a response will come at "jenkins.myserver.com:8000", wich explain the warning about the reverse proxy. 

**Version of Helm and Kubernetes**:  Helm: v3.0.3 && Kubernetes 1.14 (EKS)

**Which chart**: stable/jenkins

**What happened**:
Responses are coming in another port, like 8000 instead of 80

**What you expected to happen**:
Responses come without the port 8000 on DNS.

**How to reproduce it** (as minimally and precisely as possible):
helm install jenkins stable/jenkins --set master.ingress.enabled=true, master.ingress.hostName="jenkins.myserver.com", master.ingress.path="/", master.ingress.annotations="kubernetes.io/ingress.class=\"kong\""

**Comment by pgoga** [comment]
I have the same issue with nginx-ingress

**Comment by GoDllkE** [comment]
I managed to workaround changing the Ingress class to the AWS-ALB.

**Comment by fl-max** [comment]
@GoDllkE did you by chance change the hostName **after** the initial standup?

I'm facing this issue after updating the `master.ingress.hostName`. I can see in Chrome Dev Tools when I go to Jenkins -> Manage Jenkins that it's attempting to hit the old FQDN.

Now to figure out where this is being set...

**Comment by GoDllkE** [comment]
Yes and didn't notice any problem about old FQDN.
About this xml file, I discovered this one in another issue on a oficial jenkins project issue, when I check it up it was all updated.

Somehow, changing de ingress.class solved the issue for me.

**Comment by fl-max** [comment]
The fix for me was to simply go into _Jenkins_ -> _Configure System_ -> _Jenkins Location_ and update the **Jenkins URL** to the one set in `master.ingress.hostName`.

Ideally, `jenkins.model.JenkinsLocationConfiguration.xml` should be updated when the Ingress changes. In fact, not sure why this file isn't just overwritten like the others as these values (JenkinsUrl & adminAdress) are set in the `values.yaml` anyway.

**Comment by feifeixiyu** [comment]
Turns out this is a issue from KONG side instead of Jenkins chart. Here is some discussions([link1](https://discuss.konghq.com/t/x-forwarded-port/3795), [link2](https://github.com/Kong/kong/issues/5018)). 
Simply speaking, root cause is that KONG set the `X-Forwarded-Port` to its own server port instead of the request port. Our current solution is to let KONG listen on 80 & 443 instead of 8000 & 8443. 
There is also a fix [PR](https://github.com/Kong/kong/pull/5861), which is going to be releaded in 2.1.0.
