### ISSUE TITLE
[stable/*] Future locations of helm 3 chart repos 

### ISSUE THREAD

**Issue by anitabee** [helm/charts#21331]
Hello,

With a helm 3 release and follow up plan to make current stable and incubator repos obsolete it is a bit unclear where and are there even some plans to migrate current charts repos. 

I understand that anyone can host chart somewhere, but I believe that most of us want some more sustainable solution and one source of truth when and if that possible. I read somewhere that there was plan to ask product owners to host their charts, I think that would be ideal but I can imagine that for different reasons that will not happen.  

**Describe the solution you'd like**
Reason I'm writing this issue is to ask if it's possible for future maintainers to drop a line somewhere with migration plan so community would be aware of direction of certain charts?  For example I really like initiative from bitnami guys: [issue link](https://github.com/helm/charts/issues/20969). Or maybe even better if we have one ticket open with all future repos listed? What do you think?

Thanks in any case!

**Comment by scottrigby** [comment]
Hi @anitabee I had created this issue to give an overview, including the Bitnami charts migration: https://github.com/helm/charts/issues/21103 

It is not yet comprehensive, but covers chart repos that we have had a hand in helping migrate since the stable and incubator repo [deprecation timeline](https://github.com/helm/charts#deprecation-timeline) was agreed upon.

The goal soon will be to make it comprehensive, including repos that have transitioned (or just deprecated) even before the repo depcrecation timeline was set. We will list all charts, and bundle by canonical location where they have moved. Our recommendation for charts primary migration location has been to retain git history (so users can continue to go back and understand why past changes were made), and invite previous chart OWNERS to help continue to maintain the charts in their new location. We are also encouraging chart repos to make use of helm repo tools for automating chart testing and releasing, just as the stable and incubator repos have done.

However note that the hub may list multiple charts for the same app(s), as more than one member of the wider community may contribute helm repos to the hub and add charts as they wish. This is by design. We also can not force distributed chart repo maintainers to use our automated testing and releasing tools, as they may prefer their own. However there is discussion about making this visible, so users can use that info to help them choose which charts (and versions, etc) to trust - keep an eye in the helm hub repo issue queue for updates on that.

Hope that helps!

**Comment by anitabee** [comment]
Thanks, was searching if something already exist but missed it. I'll close this ticket than as this is kinda what I was looking for.
