### ISSUE TITLE
kube-etcd not up

### ISSUE THREAD

**Issue by chinaboy007** [helm/charts#21530]
k8s 1.16.2
helm 2.14.3

helm list
prometheus-operator     1               Thu Mar 19 03:05:40 2020        DEPLOYED        prometheus-operator-**8.12.2**      0.37.0          monitoring

error:

![image](https://user-images.githubusercontent.com/5228314/77041745-6b84f100-69f5-11ea-813d-1c7a24f9aae2.png)

Get http://192.168.227.127:2379/metrics: read tcp 10.100.140.95:54898->192.168.227.127:2379: read: connection reset by peer

why? 
how ?

**Comment by ymettier** [comment]
For some reason I have not investigated why, the port is now 2381 (at least on my Kubernetes-1.17.4).

```
sudo grep listen-metrics-url /etc/kubernetes/manifests/etcd.yaml 
    - --listen-metrics-urls=http://127.0.0.1:2381
```
Here is how I fixed it in `myvalues.yaml` file : 
```
...
kubeEtcd:
  service:
    port: 2381
    targetPort: 2381
...
```

Then `helm update ... -f myvalues.yaml`

Questions :
* Why has the port changed ?
* Should this be fixed in the upstream default `values.yaml` file ? or to do it yourself as I described above ?

No idea.
