### ISSUE TITLE
[stable/cluster-autoscaler] official docker image ?

### ISSUE THREAD

**Issue by eddycharly** [helm/charts#21698]
The cluster-autoscaler doesn't seem to use the official image:

https://github.com/helm/charts/blob/5a8cfbe5729cb64cc2995326769de89246e37809/stable/cluster-autoscaler/values.yaml#L55

Official images are in the `gcr.io/google-containers/cluster-autoscaler` repository. I can't find anything about  `k8s.gcr.io/cluster-autoscaler`.

Is this expected ? Am i missing something ?

Thanks

**Comment by isaaguilar** [comment]
I also see other official images in later images as: `us.gcr.io/k8s-artifacts-prod/autoscaling/cluster-autoscaler`, `eu.gcr.io/k8s-artifacts-prod/autoscaling/cluster-autoscaler`, and  `asia.gcr.io/k8s-artifacts-prod/autoscaling/cluster-autoscaler`

**Comment by mbarrien** [comment]
https://github.com/kubernetes/k8s.io/blob/master/k8s.gcr.io/Vanity-Domain-Flip.md shows that up until today, k8s.gcr.io was an "alias" to gcr.io/google-containers. Older releases (i.e. before yesterday) were pointing to that location. However that is slowly getting changed over starting today (1 April) so that k8s.gcr.io points to {us,eu,asia}.gcr.io/k8s-artifacts-prod (see the link for details).

Coincidentally at the same time, yesterday's new cluster-autoscaler releases were released to the new location, but with a slightly different path ("autoscaling/" as part of the name). In theory, as k8s.gcr.io flips to the new location, it should point to the new location, but the "autoscaling/" part of the path is new. It's unclear to me whether the release will be found at k8s.gcr.io/cluster-autoscaler or at k8s.gcr.io/autoscaling/cluster-autoscaler when everything settles down; so far pulling the latest tags fails at both paths from my physical location.
