### ISSUE TITLE
[incubator/zookeeper]  Cannot open channel to 1 at election address xxxxxxx-zookeeper-0.zk-zookeeper-headless.default.svc.cluster.local.:3888

### ISSUE THREAD

**Issue by jinleileiking** [helm/charts#21865]
I use version 3.6.0 for the host issue.

But log says:

```
2020-04-10 11:19:10,937 [myid:2] - WARN  [QuorumPeer[myid=2](plain=0.0.0.0:2181)(secure=disabled):QuorumCnxManager@716] - Cannot open channel to 1 at election address zk-zookeeper-0.zk-zookeeper-headless.default.svc.cluster.local.:3888
java.net.UnknownHostException: zk-zookeeper-0.zk-zookeeper-headless.default.svc.cluster.local.
```

The port is ok. I can telnet the 3888 port from other pod:

```
bash-4.3# telnet zk-zookeeper-2.zk-zookeeper-headless.default.svc.cluster.local. 3888
asdf
asdf
Connection closed by foreign host
```

I do not know why

**Comment by jinleileiking** [comment]
https://github.com/helm/charts/pull/11343

**Comment by nvtkaszpir** [comment]
Please look carefully at the error message, you will see `UnknownHostException`, which means the DNS entry for given pod was not yet registered in DNS in kubernetes, because the way headless service is configured.

The fix - headless service should force register unready edpoints, the same issue is in other java apps, especially hadoop based stack - see similiar issue and https://github.com/Gradiant/charts/issues/12 and lined merged fixes.
I'm going to make PR to zk next week to address this issue.

**Comment by jinleileiking** [comment]
But I can ping or telnet `zk-zookeeper-2.zk-zookeeper-headless.default.svc.cluster.local. 3888 ` from other  pod. I will test your merge today

**Comment by jinleileiking** [comment]
The java code does not use the latest dns info?

**Comment by jinleileiking** [comment]
I use `publishNotReadyAddresses: true`. But the question remains.

**Comment by nvtkaszpir** [comment]
UnknownHost exception can be caused by java dns caching (even for negative entries), but AFAIR it works much better than years ago.
The major problem is dns caching within dns services in kubernetes - some cloud provididers set up dns entries after 60s after pod start, even if the pod is up and ready.

**Comment by jinleileiking** [comment]
After some digging. May be the kube-dns problem. My dns version:

    Image:        coredns:1.2.6

**Comment by nvtkaszpir** [comment]
> After some digging. May be the kube-dns problem. My dns version:
> 
> ```
> Image:        coredns:1.2.6
> ```
> 
> [kubernetes-retired/contrib#2737 (comment)](https://github.com/kubernetes-retired/contrib/issues/2737#issuecomment-342469418)

Notice that coredns is not the same as kube-dns - https://coredns.io/2018/11/27/cluster-dns-coredns-vs-kube-dns/

**Comment by jinleileiking** [comment]
My k8s env:

```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:11:31Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:02:58Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by jinleileiking** [comment]
I donot know what changes. But the problem fixed....

**Comment by FfffatAss** [comment]
> I donot know what changes. But the problem fixed....


Finally, what did you do
