### ISSUE TITLE
stable/airflow , Weird Error: "“starting container process caused ”exec: \“/usr/bin/dumb-init\”: stat /usr/bin/dumb-init: no such file or directory""

### ISSUE THREAD

**Issue by Vishal2696** [helm/charts#22483]
**Describe the bug**
I built a customised Docker image of airflow following this document: "https://github.com/puckel/docker-airflow". Built and ran it in my local VM. Everything was successful and airflow was up. Pushed the image to ACR (Azure container registry) and launched it in aks via stable helm chart. Referred this link "https://github.com/helm/charts/tree/master/stable/airflow". Now suddenly in kubernetes the pods are not up and fails out with the below error.

```
Error: failed to start container "airflow-scheduler": Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"/usr/bin/dumb-init\": stat /usr/bin/dumb-init: no such file or directory": unknown
Back-off restarting failed container
```
Also immediately after the helm install I see these below lines 

```
coalesce.go:199: warning: destination for groups is a table. Ignoring non-table value []
coalesce.go:199: warning: destination for metrics is a table. Ignoring non-table value []
coalesce.go:199: warning: destination for groups is a table. Ignoring non-table value []
coalesce.go:199: warning: destination for metrics is a table. Ignoring non-table value []

```
I checked my `values.yaml` after the above message, and can confirm that all the values shown above had `{}` in them. They were not empty. Is this some problem with the chart? Is the entire chart down or something? 

Another thing to note is I'm seeing this error from 22/05/20 only. The same installation worked fine till 21/05/2020. Was there any new code pushed that is causing this error? 

**Version of Helm and Kubernetes**:
Helm == v3.1.1
kubernetes = 1.15.10
Airflow = 1.10.9

**Which chart**:
Airflow

**Comment by thesuperzapper** [comment]
Please review what version you are installing, as after v7.0.0 you must use the official Airflow docker images `apache/airflow` , not those from puckel `puckel/docker-airflow`. 

This is a good example of why you should always pin the version of the helm chart you are installing, rather than blindly taking the latest version.

**Comment by vishal8k** [comment]
@thesuperzapper  Good info there. For testing purpose I tried helm installation with the chart `7.0.0` but still faced the same error. Tried with `6.9.9` helm wasn't able to find such a chart itself. Where am I going wrong now? has 7.0.0 also been updated? Below is the command I used for installtion:

`helm install custom-airflow --namespace airflow --values values.yaml --version 7.0.0`

After Installation when I try `helm list` it shows the chart version correctly as 7.0.0 and airflow version as 1.10.10. what can be the problem here?

**Comment by thesuperzapper** [comment]
@vishal8k 
Firstly, 7.0.1 is the latest version (but 7.1.0 is coming very soon with lots of fixes). 

Secondly, you are almost certainly specifying old configs in your `values.yaml`, I recommend starting again from the one in the repo, as there have been MANY changes in 7.0

**Comment by AnonymousNoob** [comment]
@vishal8k this should be working with a previous version of airflow stable chart `6.7.3`
