### ISSUE TITLE
[stable/airflow] Support for LivenessProbe in scheduler deployment

### ISSUE THREAD

**Issue by nathanwong91** [helm/charts#22680]
**Is your feature request related to a problem? Please describe.**
It seems from time to time the scheduler pod will just stop working with the following error 
`The scheduler does not appear to be running. Last heartbeat was received x minutes ago. The DAGs list may not update, and new tasks will not be scheduled`. The pod continues to "run"

**Describe the solution you'd like**
Support for livenessProbe with the function to run a command/script to check if the scheduler is still working and restart the pod if it stops.

**Describe alternatives you've considered**
Cronjob to delete the pod each day
Using NewRelic to alert on certain metrics that appear when scheduler stops then manually delete the pod.

**Additional context**
There has been others with a similar issue posted. 
https://github.com/helm/charts/issues/19399

**Comment by thesuperzapper** [comment]
I completely agree, this has been something I have been worried about, as we only have a health check on the Web Pods (for Celery Flower and Airflow WebUI). 

Airflow provides [`/health`](https://airflow.apache.org/docs/stable/howto/check-health.html), which reports the status of scheduler and metadata DB, the trick is that the `/health` API is served on the `Webserver` pod, and so we will need to be careful polling it from the Scheduler Pod. To do this, we should use a Python script running the the scheduler Pod, as it will require parsing JSON.

**Comment by thesuperzapper** [comment]
Is anyone able to pick this up?

**Comment by nitesh-kumar-sharma** [comment]
Any solution yet?

![image](https://user-images.githubusercontent.com/22424381/87315189-cbbe1680-c541-11ea-91e6-223c324933b7.png)

**Comment by thesuperzapper** [comment]
I am working on this now

**Comment by KIRY4** [comment]
Hello @thesuperzapper any updates? I faced same issue... Using KubernetesExecutor+KubernetesPodOperator+external Postgres. After deploying airflow to k8s using helm stable airflow chart I can execute only one dag it completed successfully and after that I can't schedule anything and getting following error: The scheduler does not appear to be running. Last heartbeat was received x minutes ago. The DAGs list may not update, and new tasks will not be scheduled

**Comment by KIRY4** [comment]
Hello @thesuperzapper is it still in progress? Maybe you can provide any estimations or maybe some workaround exists ?

**Comment by thesuperzapper** [comment]
@KIRY4 I don't understand what your scheduler would be crashing regularly enough for this to be a significant problem.

And either way, you should look into why the scheduler is dying in the first place. Do you have logs?

**Comment by nielstenboom** [comment]
For people landing upon this because looking for a fix for their scheduler getting stuck occasionally. I found this blog post to fix this for the time being in a hacky way:

https://roland.de-boo.nl/airflow-healthcheck/

Worked well for us so far, but would be great if this PR helps to do this in an easier way!

**Comment by KIRY4** [comment]
@thesuperzapper I have two DAG's. One of these DAG's more or less long running it called jira_batch_jp.py (used Kubernetes pod operator) and another just for test called test_k8s_pod_operator.py (Kubernetes pod operator with hello world examples). While first one is running I can't schedule any other DAG. And even if first one is finished succesfully I can't schedule anything more because of error which showed in UI (and all dags stay in hang state): The scheduler does not appear to be running. Last heartbeat was received 4 minutes ago. The DAGs list may not update, and new tasks will not be scheduled. Only if I kill pod with scheduler container inside this error disappear and I can schedule again. Here is my scheduler log. 3 times I'm successfully run jira_batch_jp 15 times test_k8s_pod_operator one by one and in parallel I even had a hope that the error disappeared. But after that I saw again in UI: The scheduler does not appear to be running. Last heartbeat was received 14 minutes ago. The DAGs list may not update, and new tasks will not be scheduled.

And all newly scheduled DAG's hangs in no status state. But the most interesting thing that 10 or so minutes lateк this error about about heartbeat disappeared and after that DAG's with no state status started execution... Very strange behavior honestly...

[scheduler.log](https://github.com/helm/charts/files/5195492/scheduler.log)

**Comment by thesuperzapper** [comment]
Hi all, got some midnight coding in to implement this in version `7.8.0` of the chart.

Enjoy!

**Comment by thesuperzapper** [comment]
@KIRY4 this fix wont fix your issue

However... Airflow `1.10.12` may have fixed your issue, some changes were made to `KubernetessPodOperator(`, it will now reattach to existing pods. (NOTE: Airflow `1.10.12` is also included in version `7.8.0` of the chart) 

But looking at your logs, I wonder if its your Kubernetes master having issues, what is the IP: `10.158.0.1`?

**Comment by KIRY4** [comment]
@thesuperzapper  thank you. waiting for 7.8.0 and livenessprobe because switching to 1.10.12 1.10.10 by itself didn't helped...
