### ISSUE TITLE
[stable/jenkins] defaultConfig not documented - turning on breaks Jenkins

### ISSUE THREAD

**Issue by sarg3nt** [helm/charts#22693]
**Describe the bug**
JCascC.defaultConfig is not documented, other than to say "Enables default Jenkins configuration via configuration as code plugin" Which does not make any sense to me.  We've been deploying many instances of Jenkins with JCascC and Terraform for a while now and have never had that option on, but now that it is on by default in v 2.0.0 of the Helm chart it is breaking our configs.  I can turn it off and Jenkins starts up as expected, but we want to be in compliance with future movements of the Jenkins chart and that's really hard to do when an undocumented config suddenly become on by default.  The docs say we should look at the Demos project, but there is not a single instance of defaultConfig mentioned in any file in that repository.

When we do turn on defaultConfig a config file is created at  /var/jenkins_home/casc_configs/jcasc-default-config.yaml that has configs in it we are not giving it.  For example, our JCasC code specifies Jenkins.Mode: EXCLUSIVE however the generated file has it set to NORMAL and I don't know where that is coming from.  When I shut down Jenkins and look at casc_configs directory the jcasc-default-config.yaml file is not there.
So is that file being generated by the defaultConfig  setting?  If so, why aren't my settings override it???

**Which chart**:
stable/jenkins 2.0.0

**What happened**:
Jenkins crashes upon upgrade to the 2.0.0 version of the chart with an error indicating that mode: is already defined 

**What you expected to happen**:
Docs?!

**How to reproduce it** (as minimally and precisely as possible):
Use the following config
JCasC:
    enabled: true
    defaultConfig: true
    configScripts:
      config: |
        jenkins:
          mode: EXCLUSIVE

**Anything else we need to know**:

**Comment by torstenwalter** [comment]
@dsargent3220 Thank you for raising the issue.

Configuration as Code configs are rendered in [jcasc-config.yaml](https://github.com/helm/charts/blob/master/stable/jenkins/templates/jcasc-config.yaml) or [config.yaml](https://github.com/helm/charts/blob/master/stable/jenkins/templates/config.yaml). The first one is used if `configAutoReload` is `true`.

To keep the templating identical both files use `{{- include "jenkins.casc.defaults" .}}`

You can find it in [_helpers.tpl](https://github.com/helm/charts/blob/master/stable/jenkins/templates/_helpers.tpl)

You asked where `nodeUsageMode: "NORMAL"` is coming from. It's [here](https://github.com/helm/charts/blob/master/stable/jenkins/templates/_helpers.tpl#L221). At the moment that values is hard coded. I'd love to see a PR which allows configuration. E.g. the current value could be moved to `values.yaml` so that you can easily change it.

The whole idea of the default configuration is to replicate exactly what the XML configuration did before. You find more context in #16931

**Comment by njtman** [comment]
This is helpful, thanks @torstenwalter . I was running into similar issues.
It would be nice if these values in the `_helpers.tpl` were documented in the readme.

For example
`master.jenkinsUrl`
`master.jenkinsAdminEmail`

Both of these tripped me up as I was previously setting these values using JCasC, however they must now be set via helm chart overrides.
