### ISSUE TITLE
[stable/Airflow] - External Redis with SSL

### ISSUE THREAD

**Issue by vologue** [helm/charts#22854]
I'm attempting to connect to an external redis server which uses SSL however I can't find anything on the chart which lets me add SSL certs or set SSL as true?
External redis connection with SSL should be configurable.

**Comment by thesuperzapper** [comment]
Here is the template for the Redis connection string, what additional paramaters do you need:
https://github.com/helm/charts/blob/master/stable/airflow/templates/_helpers.tpl#L102

**Comment by alexbegg** [comment]
I looked into this as it is something I will soon need to do. There are 3 ways to set up Redis to use SSL in Airflow that I know of (but have yet to test i with this chart, planning to in the next week or so) so maybe this helps you:

1. Set the following in config values (inputs the values into the default celery config):
    - `AIRFLOW__CELERY__SSL_ACTIVE`
    - `AIRFLOW__CELERY__SSL_KEY`
    - `AIRFLOW__CELERY__SSL_CERT`
    - `AIRFLOW__CELERY__SSL_CACERT`
2. Add your own customized celery config (Note: I previously had issues with Flower trying to do this method as I couldn't find a way to have flower used a customized celery config such as this, it just places the broker URL in the Flower cli when it starts):
    1. Use the contents of https://github.com/apache/airflow/blob/1.10.10/airflow/config_templates/default_celery.py as a ConfigMap as the key `celery_config.py` and set the `mountPath` value to `/opt/airflow/config/celery_config.py` and subPath value to `celery_config.py`
    2. change `DEFAULT_CELERY_CONFIG` to `CELERY_CONFIG` (since it is no longer default)
    3. Finally change the `AIRFLOW__CELERY__CELERY_CONFIG_OPTIONS` value to path to that the class (should be `celery_config.CELERY_CONFIG` -- the CELERY_CONFIG dict inside of the celery_config.py file)
2. Make a PR to change that `airflow.connection.celery.broker` definition @thesuperzapper linked to allow for adding query params to the end of the url, for example: `?ssl_cert_reqs=CERT_NONE` (this is required for some some providers such as Azure Cache for Redis which I use since they don't provide an SSL certificate but require SSL, but Airflow's default celery config requires a cert if you enable SSL for Celery)

    Here are the params (as taken from https://docs.celeryproject.org/en/master/userguide/configuration.html#id12):
    - `ssl_cert_reqs` (required): `CERT_NONE`, `CERT_OPTIONAL`, or `CERT_REQUIRED`
    - `ssl_ca_certs` (optional): path to the CA certificate
    - `ssl_certfile` (optional): path to the client certificate
    - `ssl_keyfile` (optional): path to the client key

So in my case I would need to go with option 3 since I use Azure Cache for Redis, but option 2 will be nice to use without having to make a PR if I can find a way to have Flower use that custom config

**Comment by alexbegg** [comment]
Also of note, only in Flower 0.9.4 was the ability to use the `broker_use_ssl` celery configuration added for Flower, the airflow image this chart uses installs the older Flower 0.9.3. So you will need to use a custom docker image that is based on the apache/airflow image (`FROM apache/airflow:1.10.10-python3.6`) and then install Flower 0.9.4 and hopefully then it can use the `broker_use_ssl` dict that Airflow configures. Otherwise you need to use option 3 or just not use Flower.

**Comment by charlesgreen** [comment]
Is it possible to append `?ssl_cert_reqs=CERT_OPTIONAL` to `REDIS_CONNECTION_CMD` on line 109?

https://github.com/helm/charts/blob/master/stable/airflow/templates/_helpers.tpl#L109

**Comment by thesuperzapper** [comment]
@charlesgreen please raise any issues with the chart on the new repository: https://github.com/airflow-helm/charts/tree/main/charts/airflow

**Comment by charlesgreen** [comment]
Will do. thank you. Sorry for the inconvenience.
