### ISSUE TITLE
[incubator/druid] Can I change druid.zk.paths.base and druid.discovery.curator.path?

### ISSUE THREAD

**Issue by didip** [helm/charts#23017]
I don't see a way to change both of those options in values.yaml documentation.

**Is your feature request related to a problem? Please describe.**
I cannot customize druid.zk.paths.base and druid.discovery.curator.path

**Describe the solution you'd like**
I'd like to be able to customize druid.zk.paths.base and druid.discovery.curator.path

**Comment by AWaterColorPen** [comment]
@didip do you mean that you have an other zookeeper cluster and don't want use the default zookeeper chart？so that you want customize `druid.zk.paths.base` and `druid.discovery.curator.path`

1. https://github.com/helm/charts/blob/master/incubator/druid/values.yaml#L344 you should set `zkHosts` to your zookeeper cluster ip and port. And  set `zookeeper.enabled` with `false`

2. https://github.com/helm/charts/blob/master/incubator/druid/values.yaml#L15 you should set `configVars.druid_zk_paths_base` and `configVars.druid_discovery_curator_path` into install command.
