### ISSUE TITLE
[stable/jenkins] Adding/Mounting ssh-key-secrets to master pod (e.g. for private github access)

### ISSUE THREAD

**Issue by frewilhelm** [helm/charts#23025]
**Is your feature request related to a problem? Please describe.**
I'd like to completely automatize a jenkins-deployment via helm-chart. For this I need SSH keys in my master-pod to import jobs from my private GitHub-repository later. However, I have not yet found a way to achieve this.

**Describe the solution you'd like**
I'd like to find a way to add, import, or mount SSH keys into the jenkins master-pod.

**Describe alternatives you've considered**
There is a similar issue '_Is there any way to add ssh-key-secret to master pod for private git access_' (#10809) that is linking to this issue '_OwnSshKey setting does not actually allow for specifying your own key_' (#12140). However, the described solutions do not work since neither `OwnSshKey` nor `adminSshKey` are still implemented in `values.yaml`, if I am not mistaken.

**Comment by fwilhelm92** [comment]
Closed, since it was "solved". 

The local chart repository was not updated. After the jenkins helm chart was updated to the latest version (2.3.3), mounting the secrets worked as follows: 

In `values.yaml`:
<pre><code> 
persistence:
  enabled: true
  volumes:
    - name: jenkins-ssh-key
      secret:
        secretName: jenkins-ssh-key
  mounts:
    - mountPath: /var/jenkins_home/.ssh
      name: jenkins-ssh-key
      readOnly: true
</code></pre>

In `jenkins-ssh-key.yaml` (as k8s-Secret):
<pre><code>
apiVersion: v1
kind: Secret
metadata:
  name: jenkins-ssh-key
data:
  id_rsa: cHJpdmF0ZUtleQo=         # Sample Values
  id_rsa.pub: cHVibGljS2V5Cg==     # Sample Values
</code></pre>
