### ISSUE TITLE
[stable/fluent-bit] Add support for Merge_JSON_Log option in Kubernetes filter

### ISSUE THREAD

**Issue by sagikazarmark** [helm/charts#2322]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Feature request

**Version of Helm and Kubernetes**:
Helm: 2.6
Kubernetes: 1.6

**Which chart**:
stable/fluent-bit

/cc @edsiper

**Comment by nictuku** [comment]
Is this change being considered? Our applications produce structured output using the Go `logrus` library. I use the fluentd formatter from https://github.com/joonix/log. The log output is nicely formatted:
```
{"branch":"breaking-change-for-testing","commit":"8e925c9515d50d2ddee8d64b1814bcbda99a6d51","duration":5.7e-7,"message":"INFO: Elapsed time: 3.501s, Critical Path: 1.26s","owner":"yourbase","repoURL":"github.com/yourbase/test-ci","severity":"info","time":"2018-01-21T08:34:19Z"}
```
But unfortunately the fluentd kubernetes filter isn't merging those fields in, so they are treated as an opaque string and I can't do aggregations in the ELK stack.

I would like to enable this option so we can merge all JSON string maps for each line. The [documentation](http://fluentbit.io/documentation/current/filter/kubernetes.html) says that this filter option behaves nicely if the entry is _not_ a JSON entry, in which case it doesn't merge the JSON fields. The JSON field merging probably increases CPU usage a tiny bit, but I don't see a downside since we would leave it off by default.

I am happy to contribute a change for this. I suspect we need to add a Chart config option for merging the log entries, and then use it here: https://github.com/kubernetes/charts/blob/master/stable/fluent-bit/templates/config.yaml#L26

Thoughts @edsiper ?
