### ISSUE TITLE
helm increases the complexity of kubernetes？

### ISSUE THREAD

**Issue by forbxy** [helm/charts#23316]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by mattfarina** [comment]
Helm is a package manager, like apt is for Debian and Ubuntu. In that way it simplifies the Kubernetes experience.

Consider MySQL. Is it easier to use `apt install mysql` or to get the binaries, put them on the operating system, put the configuration files where they need to go, run the commands to set the root password, and set the system to start it? `apt install mysql` is simpler because the package and package manager do a lot of work for you.

Helm is the same way. It's easier to run `helm install mysql stable/mysql` than it is to find the images, create the Kubernetes manifests (which means knowing a fair amount about operating mysql), and running it yourself.

If you try to use Helm outside of a package manager style workflow you might create a situation where Helm is more complicated. But, that applies to any tool you try to use for something other than its purpose.

Kubernetes itself is complicated. The docs to deploy and manage applications are well over 1,000 pages if you printed them. Then you have to know how to operate the application, too.

Since this isn't related to a particular chart or this repository, I'm going to close the issue.
