### ISSUE TITLE
Prometheus PVC support for more than one replica or Statefulset

### ISSUE THREAD

**Issue by joseppla** [helm/charts#2346]
**Is this a request for help?**:
No
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
FEATURE REQUEST

**Version of Helm and Kubernetes**:
Kubernetes 1.6.2
Helm 2.6.1

**Which chart**:
stable/prometheus

**What happened**:
started 2 repicas of prometheus server with an ebs PVC
'''server:
  name: prometheus
  persistentVolume:
    size: 20Gi
    annotations:
      volume.alpha.kubernetes.io/storage-class: ebs'''

**What you expected to happen**:
Start 2 Prometheus servers with one EBS attached each one

**How to reproduce it** (as minimally and precisely as possible):
Configure server replicas to 2 with persistent storage

**Anything else we need to know**:

**Comment by ghost** [comment]
Just experienced this too with alertmanager.

I get two alertmanager pods and one alertmanager pvc which is RWO, so they cannot share it.  I've set only 1 replica for server, due to https://github.com/prometheus/prometheus/issues/2609 , which I'm sure is related.

This file needs updates, at least:

https://github.com/kubernetes/charts/blob/master/stable/prometheus/templates/alertmanager-pvc.yaml

**Comment by empyrean987** [comment]
Any Update on supporting replicas for Server or AlertManager?

**Comment by empyrean987** [comment]
Is there any update on running more than one replica for alert manager or prometheus server and mapping PVC volumes and how that is done?
