### ISSUE TITLE
[stable/prometheus-operator] Error after deleting Crds

### ISSUE THREAD

**Issue by ayoubeddafali** [helm/charts#23838]
**Describe the bug**

I have installed today the prometheus operator charts on my cluster, and while I was playing around I deleted the prometheus crd, and after that my cluster broke, and the Api server no longer function correctly. Here is the errors I get from the apiserver logs : 

```
I1002 14:06:23.997790       1 controller.go:81] Starting OpenAPI AggregationController
I1002 14:06:23.997887       1 crdregistration_controller.go:111] Starting crd-autoregister controller
I1002 14:06:23.997907       1 shared_informer.go:197] Waiting for caches to sync for crd-autoregister
I1002 14:06:24.000521       1 crd_finalizer.go:274] Starting CRDFinalizer
E1002 14:06:24.000761       1 controller.go:154] Unable to remove old endpoints from kubernetes service: StorageError: key not found, Code: 1, Key: /registry/masterleases/10.78.130.10, ResourceVersion: 0, AdditionalErrorMsg: 
I1002 14:06:24.061734       1 controller.go:85] Starting OpenAPI controller
I1002 14:06:24.061769       1 customresource_discovery_controller.go:208] Starting DiscoveryController
I1002 14:06:24.061793       1 naming_controller.go:288] Starting NamingConditionController
I1002 14:06:24.061812       1 establishing_controller.go:73] Starting EstablishingController
I1002 14:06:24.061831       1 nonstructuralschema_controller.go:191] Starting NonStructuralSchemaConditionController
I1002 14:06:24.061852       1 apiapproval_controller.go:185] Starting KubernetesAPIApprovalPolicyConformantConditionController
I1002 14:06:24.126956       1 shared_informer.go:204] Caches are synced for crd-autoregister 
I1002 14:06:24.153074       1 cache.go:39] Caches are synced for AvailableConditionController controller
I1002 14:06:24.153439       1 cache.go:39] Caches are synced for APIServiceRegistrationController controller
I1002 14:06:24.165359       1 cache.go:39] Caches are synced for autoregister controller
I1002 14:06:24.180075       1 controller.go:606] quota admission added evaluator for: leases.coordination.k8s.io
E1002 14:06:24.357045       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 2531 [running]:
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.logPanic(0x3ce83e0, 0xaa83850)
	/workspace/anago-v1.16.0-rc.2.1+2bd9643cee5b3b/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0xa3
.........
.........
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc00cdb03d0, 0x3b9aca00, 0xc00dc860c0)
	/workspace/anago-v1.16.0-rc.2.1+2bd9643cee5b3b/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d
created by k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/controller/finalizer.(*CRDFinalizer).Run
	/workspace/anago-v1.16.0-rc.2.1+2bd9643cee5b3b/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/controller/finalizer/crd_finalizer.go:282 +0x188
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xe0 pc=0x310cce2]
...............
..............

```

**Version of Helm and Kubernetes**:

Helm Version : v3.0.0
Kubernetes Version : 1.16

**Which chart**:
stable/prometheus-operator

**Anything else we need to know**:

The cluster stopped working exactly after deleting that crd, Now i can no longer interact with the API Server or anything else.

**Comment by zanhsieh** [comment]
@ayoubeddafali 
This already moved to kube-prometheus-stack under prometheus-community/helm-charts repo. Please read README.md under this chart for deprecation notice.

**Comment by RichardHsiung** [comment]
@ayoubeddafali  did you resolve the problem?    or how to resolve the problem? i had the same problem and do not know how to resolve it.

**Comment by ayoubeddafali** [comment]
@RichardHsiung  Nope, I recreated the cluster at the end.

**Comment by ayoubeddafali** [comment]
If you have any etcd backups, maybe you can restore and move on.

**Comment by SuryaTeja369** [comment]
Hi,
@ayoubeddafali @RichardHsiung I found another way of resolving this issue without going for upgrade of the Kubernetes.

The issue lies in the fact that kube-apiserver is trying to fetch details with respect to CRDs from ETCD but the memory address of the CRDs are changed as soon as we run the delete statement.

To resolve this you can exec into the etcd pod(if running as a pod) and run the following commands to delete the entries from there permanently:

1. List all the CRDs in ETCD --> ETCDCTL_API=3 etcdctl get /registry/apiextensions.k8s.io/customresourcedefinitions --limit=10 --prefix --keys-only --cacert=cacertfile --cert=tlscertfile --key=tlskeyfile --endpoints https://127.0.0.1:2379
2. ETCDCTL_API=3 etcdctl del /registry/apiextensions.k8s.io/customresourcedefinitions/podmonitors.monitoring.coreos.com --cacert=cacertfile --cert=tlscertfile --key=tlskeyfile --endpoints https://127.0.0.1:2379

There will be several other CRDs of promtheus(5 as far as I remember), delete them in a similar manner and take a restart of your docker and kubelet services.

PS: This was the quickest and the only fix without upgrading or crashing the server and reinstalling kubernetes or doing a backup restore of ETCD.

I have tried and tested this in my ENV and works like a charm :)
