### ISSUE TITLE
redis-ha chart does not work with persistence

### ISSUE THREAD

**Issue by zzorba** [helm/charts#2386]
**Is this a request for help?**:
No
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Helm and Kubernetes**:
Helm 2.6.1, Kubernetes v1.7.5-gke.1

**Which chart**:
redis-ha

**What happened**:
Does not work with persistence enabled, fails to create enough PVC instances for secondaries or refer to them by the correct names.

**What you expected to happen**:
The chart to deploy.

**How to reproduce it** (as minimally and precisely as possible):
Set `persistentVolume.enabled` to true and install the chart, observe that it does not start up.

**Anything else we need to know**:
Changing the template to use `{{ template "fullname" . }}-pvc` instead of `{{ template "name" . }}` allows the master to start, but no additional pvc claims are made for the secondaries.

**Comment by unguiculus** [comment]
I just looked at the chart and think it is fundamentally broken in various ways.

/cc @smileisak

A few things I noticed:
- Statefulsets need `volumeClaimTemplates` so they can scale.
- Slaves should be a statefulset as well and use `volumeClaimTemplates` if persistance is enabled. Otherwise they won't be able to scale up.
- Statefulsets need governing stateless services.

**Comment by smileisak** [comment]
@zzorba fixed here https://github.com/kubernetes/charts/pull/2543
@unguiculus Thank you for your comments, i'll take it  into consideration :+1:
