### ISSUE TITLE
[incubator/aws-alb-ingress-controller] request for migration

### ISSUE THREAD

**Issue by gmelillo** [helm/charts#23898]
**Is your feature request related to a problem? Please describe.**

This repository will be deprecated soon (#21103). There is any plan to migrate this chart somewhere else or I'll need to maintain a local copy in order to avoid issues in the future?

**Describe the solution you'd like**

Have a version available that is not in `stable` or `incubator`

**Describe alternatives you've considered**

Have a local copy of the chart

**Comment by bryankaraffa** [comment]
Looking in the [OWNERS](https://github.com/helm/charts/blob/master/incubator/aws-alb-ingress-controller/OWNERS) file I see @bigkraig and @M00nF1sh .  Just wondering if there are any plans to maintain this chart?

AWS has their own chart for this as well -- [aws-load-balancer-controller](https://github.com/aws/eks-charts/tree/master/stable/aws-load-balancer-controller).  It is a different implementation and at this time I am hoping to be able to just update the repo for the charts we are using instead of switching over... but if it's no longer maintained then that may be the better choice.

**Comment by M00nF1sh** [comment]
@bryankaraffa
thanks for the notification 👍 
I'll discuss with team whether we want to migrate this over to eks-charts
