### ISSUE TITLE
[stable/locust] support the new locust images and changes

### ISSUE THREAD

**Issue by user10x** [helm/charts#23905]
**Describe the bug**
With the new locust release of locust >=1.0, the config flags have changed for the master/worker to connect, and moving away from previously terms like master slave terminology. This will make easier to use the updated locust images. 

Config options are to be updated here. https://docs.locust.io/en/stable/configuration.html

Image specified/to be udpated:
https://github.com/helm/charts/blob/master/stable/locust/values.yaml#L5

Env Variables to be updated:
https://github.com/helm/charts/blob/master/stable/locust/templates/master-deploy.yaml#L38

Master config flags/env vars to be updated 
 - name: LOCUST_MODE_MASTER
    value: 'true'
 - name: LOCUST_EXPECT_WORKERS
    value: '5'

Worker config flags/env vars to be updated 
https://github.com/helm/charts/blob/master/stable/locust/templates/worker-deploy.yaml#L42

- name: LOCUST_MODE_WORKER
   value: 'true'
- name: LOCUST_MASTER_NODE_HOST
   value: {{ template "locust.master-svc" . }}

Additionally worker command needs to be updated with this option or a similar variable
containers:
      - command:
        - locust
        - "--worker"

https://docs.locust.io/en/stable/changelog.html

**Version of Helm and Kubernetes**:
version.BuildInfo{Version:"v3.3.4", GitCommit:"a61ce5633af99708171414353ed49547cf05013d", GitTreeState:"dirty", GoVersion:"go1.15.2"}

**Which chart**:
stable/locust

**What happened**:

**What you expected to happen**:

Startup the chart

**How to reproduce it** (as minimally and precisely as possible):
Try using a new image in the values file and the tasks would not run because of old locust syntax and workers not able to interact

**Anything else we need to know**:

Move this chart into to locust directory

**Comment by nickhalden** [comment]
I can contribute to this feature/bug if someone can let me know if they would like to chart to be moved over to https://github.com/locustio/locust

**Comment by mfcrocker** [comment]
@scottrigby This chart seems pretty much abandoned by this point, and Locust has moved on a *lot* since then. In the issue above that @nickhalden opened on locustio/locust, the locust team pointed towards this chart https://github.com/deliveryhero/helm-charts/tree/master/stable/locust that deploys locust 1.3.0 (the stable chart is currently pinned to 0.9.0, the docker images that feed the chart stopped being updated past 0.14.5). It might be worth reaching out to the maintainer of that chart to see if it could become the new stable chart.
