### ISSUE TITLE
Restart policy in the test pod

### ISSUE THREAD

**Issue by Kirill-Garbar** [helm/charts#23931]
https://github.com/helm/charts/blob/668b7757c106d4a60a1aed22ca9d18c60c719c48/stable/metrics-server/templates/tests/test-version.yaml#L27
If chart is deployed into the kubernetes where some problems with network or something else are existing then test is not successfull and pod is not restarted. It is not cloud-native. RestartPolicy OnFailure should be used here.

**Comment by schollii** [comment]
I think this point should be discussed briefly in the docs because onfailure may not always be suitable, just like never is not always suitable. Eg in our CI/CD, if a test fails, I don't want it to run over and over, even when the next update of service gets run. I just want it to stay there in a stopped state so I can look at the logs, and if it failed because of an intermittent network issue, I can rerun it manually from the pipeline.

**Comment by bridgetkromhout** [comment]
Hi, @Kirill-Garbar & @schollii - thanks for your ideas. If you'd like to contribute docs updates to clarify the status as of Helm 3, the English docs are found at https://github.com/helm/helm-www/tree/main/content/en/docs.
