### ISSUE TITLE
Unable to install Mongo DB replicaset chart

### ISSUE THREAD

**Issue by viglesiasce** [helm/charts#242]
After installing the mongodb-replicaset chart, the install container in the first pod in the StatefulSet hangs as follows:

```
$ kubectl logs famous-coral-mongodb-rep-0 install
installing config scripts into /work-dir
installing mongod.conf into /config
chown: invalid user: 'mongodb:mongodb'
```

cc @foxish

**Comment by Dmitry1987** [comment]
Hi @viglesiasce , I'm trying to experiment with this chart, and it gets stuck somewhere after provisioning the PV and "storage volume claims" (because those get created properly and shown as ready and attached), on AWS.
I see this error on k8s 1.4.6:   
![image](https://cloud.githubusercontent.com/assets/9369080/21075456/4243feae-bf1b-11e6-8012-a6736853fbe2.png)

Then after deleting this pod (hoping it'll start normally on 2nd run) it actually starts having real issues with volumes: 
![image](https://cloud.githubusercontent.com/assets/9369080/21075462/9c06037e-bf1b-11e6-8474-8993302bbba1.png)

in pod yaml I see a clue that it's bootstrap container which is stuck  "containers with incomplete status: [install bootstrap]",  maybe you can advice how to further troubleshoot this? 
I try to view log of install container but it says "Error from server: container "install" in pod "mongodb-mongodb-replicas-0" is waiting to start: PodInitializing"  does it mean it didn't even start?

**Comment by Dmitry1987** [comment]
+1  , same issue,
chown: invalid user: 'mongodb:mongodb'

**Comment by seanknox** [comment]
Just gave the chart a whirl in a cluster and looks like this is fixed.
