### ISSUE TITLE
[incubator/istio] istio install failed

### ISSUE THREAD

**Issue by gyliu513** [helm/charts#2447]
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Version of Helm and Kubernetes**:

**Which chart**:
istio

**What happened**:

```
Lins-MacBook-Pro:Downloads linsun$ helm repo add incubator http://storage.googleapis.com/kubernetes-charts-incubator
"incubator" has been added to your repositories
Lins-MacBook-Pro:Downloads linsun$ helm install --name istio incubator/istio --namespace istio-system
Error: file "incubator/istio" not found
```

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by gyliu513** [comment]
Related with https://github.com/istio/istio.github.io/pull/531#issuecomment-335281205

/cc @linsun @lachie83

**Comment by rimusz** [comment]
this is the problem https://github.com/kubernetes/charts/blob/master/incubator/istio/Chart.yaml#L6 why istio chart can't be installed from helm repos

**Comment by gyliu513** [comment]
Why `version: 0.2.7-chart2` caused the install failed from incubator repo? Can you please elaborate? Any comments for how to make this work? @rimusz

**Comment by rimusz** [comment]
helm does not like `version: 0.2.7-chart2` it breaks it's semver logic.
as soon you change to `version: 0.2.7`, istio install from remote helm repo works again

**Comment by gyliu513** [comment]
Thanks @rimusz , this seems to be a limitation of semver https://github.com/Masterminds/semver/blob/master/constraints_test.go#L296 , if use `version: 0.2.7`, then we will not able to track all of the different versions, what do you think @ldemailly @lachie83

**Comment by rimusz** [comment]
@gyliu513 chart version does not have to be the same as app's :)

**Comment by lachie83** [comment]
The chart version does conform to semver v2 but it falls under pre-release so you have to use the `--devel` flag upon install. We are working on ways to expose the appVersion as it may be more relevant to some users. See https://github.com/kubernetes/helm/issues/3009 and it's related issue to expose appVersion in search

**Comment by linsun** [comment]
Could we change it to version: 2.0.7 so that the istio helm chart can work given istio 0.2.7 is just announced today?

**Comment by lachie83** [comment]
Would like to get something definitive from @ldemailly given that I've been working with him on this.

https://github.com/kubernetes/helm/issues/3009#issuecomment-334608551

**Comment by lachie83** [comment]
Also some additional context that I've been working with the Helm upstream developers on https://github.com/kubernetes/helm/issues/3010 cc @ldemailly

**Comment by ldemailly** [comment]
apologies for the lag: the search isn't there yet, is it

I assume you are asking if we can decouple the 2 versions, I prefer we keep them in lockstep if possible but if not practical maybe having 0.2.7-pre1 ... until it seems to be "working" enough to promote it to 0.2.7 ?

if we decouple the versions, what would the helm one look like ? (1.0.x ?)

**Comment by linsun** [comment]
I'd prefer to keep the istio helm chart version and istio version in sync as that reduces a lot of confusion.

Since Istio 0.2.8 is coming out this week and contains critical fixes, is it possible to allow users to always install the latest Istio in 0.2.x and optionally user can specify a particular version of 0.2, like 0.2.7 or 0.2.8 or 0.2.9 to install?

**Comment by lachie83** [comment]
I don't think keeping the versions in sync is the right approach. The chart version indicates a set of values and templated Kubernetes resource definitions which is not actually intrinsically linked to the application version. I don't want to lock a released chart in so that it cannot be modified within the same semver release as things change all the time and functionality may be added or removed at any point. 

I do however think that we could do a better job bubbling up the application version as a searchable and installable install time flag. Out of the 80+ upstream charts no one has flagged this a serious issue for users. Services like monocular expose the appVersion in a nicer way - https://kubeapps.com/charts?q=istio

I think given the current ask it's best simply make the chart versions so different that they cannot possibly be confused. Possibly 10.0.0 to start. Hopefully by that time we have a reasonable approach to the exposing the app version.

**Comment by lachie83** [comment]
The next release of helm will allow you to search via app version. Does this help?
 https://github.com/kubernetes/helm/pull/3059

**Comment by stealthybox** [comment]
Current workaround:
```
helm install --name istio incubator/istio --namespace istio-system --devel --version 0.2.7-chart2
helm upgrade istio incubator/istio --reuse-values --set istio.install=true --devel --version 0.2.7-chart2
```
