### ISSUE TITLE
Update charts k8s org teams

### ISSUE THREAD

**Issue by mattfarina** [helm/charts#2500]
There are currently 2 teams for charts. There is the @kubernetes/charts-admins and @kubernetes/charts-maintainers. Neither of these teams represent what's in the OWNERS file.

Can we get a clear distinction on the different and update the maintainers to be the list of maintainers?

**Comment by michelleN** [comment]
Looks like the difference is that @kubernetes/charts-admins have admin rights to the repo while @kubernetes/charts-maintainers have write access to the repo.
1. Do we still need this distinction? @prydonius 
2. What is OWNERS actually used for in this repo? @mattfarina 
3. OWNERS (depending on what it means for this repo or if it just here for consistency across repos) should probably reflect the people in @kubernetes/charts-maintainers group which should also contain the folks from @kubernetes/charts-admins 

My 2 cents based on historical context. Probably should be discussed at the next charts meeting.

**Comment by prydonius** [comment]
1. Looks like the admins/maintainers groups are used in other projects too, so I guess it makes sense to keep it
2. OWNERS is being used to make it possible for non-repo maintainers to approve and merge PRs via the merge bot.
3. Given the above, the OWNERS at the root should reflect @kubernetes/charts-admins and @kubernetes/charts-maintainers, but deeper OWNERS files may not.

Due to historical use of this repo, the @kubernetes/charts-maintainers and @kubernetes/charts-admins groups have members that are not in our current root OWNERS files, and so we should maybe clean these groups up.

**Comment by prydonius** [comment]
I went through the team and removed anyone not listed in the root OWNERS file of this repository.
