### ISSUE TITLE
helm delete --purge does not delete pods which are in completed state

### ISSUE THREAD

**Issue by alhafoudh** [helm/charts#2540]
**Is this a request for help?**:

no

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

BUG REPORT

**Version of Helm and Kubernetes**:

helm 2.6.2
kubernetes 1.7.5

**Which chart**:

minio

**What happened**:

I installed the minio chart, waited few minutes and then deleted it.
Pod <release name>-create-bucket does not get deleted aftr issuing `helm delete --purge`.
I suppose its because the pod is in Completed state.

**What you expected to happen**:

All resources deleted including this completed pod.

**How to reproduce it** (as minimally and precisely as possible):

1. helm install stable/minio
2. waited until the chart starts up
3. helm delete --purge <release name>

**Anything else we need to know**:

nope

**Comment by krancour** [comment]
Although this is probably not desirable behavior, this is the way Helm works. That job is defined in a post-install hook. Resources defined in hooks are not managed by Helm on an ongoing basis for their lifetime. While there are complex things that could probably be done with this chart to rectify this, like creating another job in another hook to make it clean up after the first hook/job (and itself), it might be more constructive to open a feature request against Helm itself for hooks that defined resources that would be managed on an ongoing basis (which would include their removal upon deletion of the release). I have privately asked for this feature as well, but it hasn't gotten much traction yet because recent Helm releases, like the rest of k8s have been focused on stability instead of features.

**Comment by stela** [comment]
Looks like this has been resolved now for minio using a `helm.sh/hook-delete-policy` annotation, see #2655. 

A side-effect of this though is that you cannot get the logs out of the deleted pod, I did manage to get them while it was still running though with `while true; do kubectl logs -f mychart-minio-create-bucket; done`.

Time to close this issue?
