### ISSUE TITLE
traefik acme certificate error

### ISSUE THREAD

**Issue by haseebnaseem** [helm/charts#2654]
**Is this a request for help?**:
Yes
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
None

**Version of Helm and Kubernetes**:

**Which chart**:
Traefik

**What happened**:
The tls certs were not found when request was made using https

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:
release config as follows:
dashboard.enabled=true
ssl.enabled=true
acme.enabled=true
acme.email=xxx@yyy.com
metrics.datadog.enabled=true
metrics.statsd.enabled=true

**Comment by krancour** [comment]
The likely cause of this is that Let's Encrypt has recently disabled their old default challenge type TLS-SNI-01, due to vulnerabilities. Logs would be enlightening here, but in their absence, I will assume this was the cause, as it's _incredibly likely_.

Note that even though that Let's Encrypt has removed support for the TLS-SNI-01 challenge, Traefik / this chart still use that challenge by default. Why? Because it would be a breaking change to the chart to change the default. (There's a small number of users whitelisted and still permitted to use the TLS-SNI-01 challenge.)

#1299 recently added support for using the DNS-01 challenge instead and #3347 (still open) looks to add support for the HTTP-01 challenge.

I believe this sufficiently addresses the issue that was reported and since one newer, better option exists, with a second in the works, I'm going to close this.

/close
