### ISSUE TITLE
[incubator/elasticsearch] Switch to default docker image rather than specialized

### ISSUE THREAD

**Issue by mikn** [helm/charts#2782]
**Is this a request for help?**: No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

**Version of Helm and Kubernetes**: Not relevant

**Which chart**: elasticsearch

**What happened**: When installing the elasticsearch helm chart, I noticed that the version of elasticsearch is fairly outdated.

**What you expected to happen**: The helm chart is structured in a way that allows it to track upstream elasticsearch closely.

**How to reproduce it** (as minimally and precisely as possible): Not relevant.

**Anything else we need to know**: Based on work done here: https://github.com/clockworksoul/helm-elasticsearch, we've been working on making our own helm chart that supports some features that we'd like to see as well for elasticsearch. The main feature that the linked helm chart has is that it just uses a standard kubernetes service pointing to the masters for discovery, rather than fabric8's plugin, allowing it to use almost any docker image. Further development have been done here: https://github.com/lalamove/helm-elasticsearch, where we moved support for plugin installation from using an environment variable to an init container making it compatible with the official Elasticsearch docker image as well as any other non-specialized image.

If the maintainers are interested in some of the features developed in these two repositories, I would be very happy to open a series of pull requests incorporating most of the features into the official chart instead.

The main features I would open PRs for would be:
 - Switch to using DNS-based discovery with a Kubernetes service rather than kubernetes-specific plugin
 - Elasticsearch Curator
 - Upgrading to Elasticsearch 6.0 (with alpine image)
 - Plugin installs through initContainer
 - Parallel startup of the StatefulSets

And future PRs (not yet developed) would most likely involve:
 - Using the CA in Kubernetes to issue certificates to cluster nodes for TLS (probably using search-guard-ssl, but could perhaps make it agnostic)
 - Using SearchGuard for Authorization and Authentication for Elasticsearch clients and log shippers

**Comment by tmaier** [comment]
What I like about lalamove/helm-elasticsearch and clockworksoul/helm-elasticsearch is that it is based on a very popular [kubernetes-elasticsearch-cluster](https://github.com/pires/kubernetes-elasticsearch-cluster) template. This means nothing is getting re-invented, but re-used.

I don't know whats better DNS-based discovery or [fabric8io/elasticsearch-cloud-kubernetes](https://github.com/fabric8io/elasticsearch-cloud-kubernetes). Is there a comparison available?

**Comment by vreon** [comment]
I'm in favor of this :raised_hands:

Neither the fabric8 plugin nor the centerforopenscience image have released a 5.6 version, which I need to [migrate seamlessly to 6.x](https://www.elastic.co/guide/en/kibana/current/migrating-6.0-index.html). It'd be nice to stick to the official images!

**Edit**: I missed #2889 somehow. That covers most of my concerns!

**Comment by icereval** [comment]
@mikn, some feedback

* Switch to using DNS-based discovery with a Kubernetes service rather than kubernetes-specific plugin
  - https://github.com/kubernetes/charts/pull/2889 - nearly g2g!

* Elasticsearch Curator
  - :+1:

* Upgrading to Elasticsearch 6.0 (with alpine image)
  - Certainly good to support the latest version :+1:. We could add a note in the readme about the leaner alpine image. I would prefer we stick with the [official images](https://www.docker.elastic.co/) by default.
  - We'll need to update custom scripts to no longer depend on `jq`, these can be updated to use `python`.

* Plugin installs through initContainer
  - This would be nice, as an opt-in deployment parameter. Some might not be comfortable / have strict requirements regarding images accessing the internet on spin up.

* Parallel startup of the StatefulSets
  - [Parallel startup and termination](https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#deployment-and-scaling-guarantees) seems interesting, however I would be concerned parallel termination will likely break the `pre-stop-hook.sh` script which migrates documents and shards when the cluster is resized, thus avoiding data loss.

---

Additional items we should consider adding:

* Support naming for Coordinating/Ingest Nodes

* Pod Disruption Budgets (see. https://github.com/kubernetes/charts/pull/2530 ) 

* User controlled [additional affinities](https://github.com/CenterForOpenScience/helm-charts/blob/master/elasticsearch/templates/client-deployment.yaml#L26) so very specific policies can be enforced, such as avoiding preemptible/spot instances in a cluster.

**Comment by icereval** [comment]
To support using the official ElasticSearch image, I've been updating our forked chart. Once tested, and the changes validated, I'll see to a PR for further review.

Plugin Management via InitContainer: https://github.com/CenterForOpenScience/helm-charts/commit/8436ec92bac3d09c4d4d149db6c657503d624359

Remove `jq` dependency: https://github.com/CenterForOpenScience/helm-charts/commit/b058395e16ab16a353ddc99d383afd5ce5cbd5ce
