### ISSUE TITLE
stable/keel and stable/weave-cloud explicitly installing in kube-system

### ISSUE THREAD

**Issue by prydonius** [helm/charts#2830]
It looks like the keel and weave-cloud charts are setting the namespace to `kube-system` explicitly in the templates. Is there any specific reason for this? It's better if this is left out of the templates and passed to `helm install --namespace` instead.

cc @errordeveloper @rimusz @rusenask

**Comment by rusenask** [comment]
Initially Keel used `keel` namespace but we had to move to `kube-system` for some reason. I will have to check it. I would prefer a separate or user specified namespace as well.

**Comment by noonien** [comment]
Also, there doesn't appear to be any RBAC support for the current keel chart

**Comment by rusenask** [comment]
thanks @fejta-bot for reminding this. I recently refreshed my mind on this. Keel needs kube-system when it's running with Helm provider support as it needs to contact Tiller's GRPC API.

**Comment by errordeveloper** [comment]
We are looking to make a major update Weave Cloud chart soon, which will
introduce a lot of changes, but ideally we would avoid letting users to
override namespace, as it is compatible with our non-Helm installation mode
and we only support one installation per cluster at the moment anyway,
however new version uses 'weave' namespace instead of 'kube-system'.
