### ISSUE TITLE
helm-test, against k8s master, is failing

### ISSUE THREAD

**Issue by mattfarina** [helm/charts#2978]
Background: Some of the charts in this repo are run against Kubernetes master as part of the end to end tests. They are currently failing and have been for a long time.

We should fix these.

Some details:

* The code is in the `test/helm-test` directory
* The status of the tests can be seen in [testgrid](https://k8s-testgrid.appspot.com/sig-apps#charts-gce&show-stale-tests=)
* Logs from the failed runs can be found in [gubernator](https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/logs/ci-kubernetes-charts-gce/)
* There are a few touch points in the [test-infra](https://github.com/kubernetes/test-infra) repo as well

We should either fix these are remove the failing testing from k8s upstream. At the moment they aren't useful but are doing a lot of work which costs some $$ and resource time.

cc: @spiffxp @viglesiasce

**Comment by viglesiasce** [comment]
cc @foxish 

This looks like its the spinnaker chart failing due to timeout which can happen since there are a lot of images to pull for this chart. 

My recommendation would be to pull Spinnaker out for now until we can update the timeouts to something more appropriate for larger charts. I'll get that submitted now.

**Comment by mattfarina** [comment]
Re-opening since things are still failing
