### ISSUE TITLE
[stable/wordpress] - How to deploy an existing wordpress website to k8s using this helm and gitlab (Or github or bitbucket)

### ISSUE THREAD

**Issue by davidcommarmond** [helm/charts#2986]
**Is this a request for help?**:
YES
---

**Version of Helm and Kubernetes**:
Latest on GKE

**Which chart**:
[stable/wordpress]

**The Question**:
1. Let's say I deployed wordpress to GKE successfully using this helm.
2. I have an existing woocommerce website in production since 5+ years hosted on a Dedicated Server that was developped on that DS directly (not git) via FTP (Yes... I know...). And it's big (nearly 10GB of images uploaded by users)
3. I saw gitlab had an integration with deploying the different stages automatically to GKE (But I don't mind doing it the other way around using Sources from GCE and link it up to github or any other repository if it's easier)
4. How can I use this helm to package my existing woocommerce store into gitlab (or github, or bitbucket, or any other git I don't mind) and deploy on GKE ?
5. From this moment we'll be then using git to work on updates (No more FTP!)

I tried to look around here, on google, on youtube, on stackoverflow, couldn't find anything...

I'm sure I'm not the only one willing to do this, so maybe if someone wants to write a tutorial, this'll help a lot of "Traditional" WordPress Developpers and server admins move to k8s :-)

Thanks

**Comment by timothyclarke** [comment]
## Disclaimer 
Please note that I don't know wordpress and this response is a more generic "How do I get content in to a pod". Please take all of my response as food for though rather than a direct technical implementation. 

From my view you have 2 ways forward depending on how you want to manage your content.

### Move the database. 
This one should be a simple dump from your existing dedicated server then import into your new one.

### Move the content. 
For a more traditional approach you could attach persistent storage the [copy the content](https://medium.com/@nnilesh7756/copy-directories-and-files-to-and-from-kubernetes-container-pod-19612fa74660)

For a more CI/CD/DevOps approch you could commit all the content into version control, then whenever you commit to the repo with your content it builds a new docker image with your layer on top of the existing ones, stores that image in your container repo and you then deploy your customised container instead of the stock one.

**Comment by sushen** [comment]
I have the same issue. If possible answer it from a technical point of view.
