### ISSUE TITLE
Dockerfile for the zookeeper image

### ISSUE THREAD

**Issue by charlesverdad** [helm/charts#3020]
**Is this a request for help?**: Yes

The image in incubator/zookeeper/templates/statefulset.yaml is harcoded to be "gcr.io/google_samples/k8szk:v2". Would anyone know where I can find the Dockerfile for that particular image?

**Comment by heeeello** [comment]
unsubscribe


________________________________
发件人: charlesverdad <notifications@github.com>
发送时间: 2017年12月13日 15:15
收件人: kubernetes/charts
抄送: Subscribed
主题: [kubernetes/charts] Dockerfile for the zookeeper image (#3020)


Is this a request for help?: Yes

The image in incubator/zookeeper/templates/statefulset.yaml is harcoded to be "gcr.io/google_samples/k8szk:v2" but I couldn't trust it completely since I couldn't find any public Dockerfile associated with it

Would anyone know where I can find the Dockerfile for that particular image?

―

**Comment by mattfarina** [comment]
@charlesverdad I think the file is in https://github.com/kubernetes/contrib/tree/master/statefulsets/zookeeper.

The incubator/zookeeper chart needs some work. It's certainly not ready for production use. The image should be configurable, for instance. If you look at the [REVIEW_GUIDELINES.md](https://github.com/kubernetes/charts/blob/master/REVIEW_GUIDELINES.md) you'll get the idea.

PRs to improve it are welcome.

**Comment by charlesverdad** [comment]
@mattfarina Thanks!

**Comment by mattfarina** [comment]
Closing. Please re-open if there is a further issue.
