### ISSUE TITLE
Update Odoo from version 10 to 11

### ISSUE THREAD

**Issue by jusle** [helm/charts#3156]
Hello,

The KubeApp image for Odoo is outdated. Could you please update it to the latest version of Odoo 11?

**Comment by mattfarina** [comment]
cc: @prydonius @tompizmor @sameersbn

**Comment by sameersbn** [comment]
@jusle Thanks for reaching out. The upgrade to odoo 11 is currently being worked on. Since this is a major release we have had to update our intergration tests. As a result it could take a couple weeks before we're ready with a throughly tested release.

We'll update this issue once the release is out.

**Comment by sameersbn** [comment]
chart version 0.7.0 installs odoo 11 :tada:

**Comment by jusle** [comment]
Cool! Thanks! :-)
