### ISSUE TITLE
support for # Zookeeper servers in Kafka chart

### ISSUE THREAD

**Issue by skunkwerk** [helm/charts#3175]
**Is this a request for help?**:
No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Feature request

If this is a FEATURE REQUEST, please:
  - Describe *in detail* the feature/behavior/change you'd like to see.

A user should be able to pass a configuration from the Kafka YAML file to Zookeeper to set the number of zookeeper servers.

**Version of Helm and Kubernetes**:
Kubernetes 1.8.4, Helm 2.7.2

**Which chart**:
Kafka, version 0.2.7

**What happened**:
Zookeeper uses 3 servers by default.

**What you expected to happen**:
allow Kafka config YAML to specify # zookeeper servers

**How to reproduce it** (as minimally and precisely as possible):
just install Kafka chart

**Anything else we need to know**:

**Comment by mattfarina** [comment]
@skunkwerk This is a good feature request and pull requests are welcome. I understand this as you may want to have 5 so that in a rolling update you wouldn't run into split brain. I would run 5 in production if I did it.

cc: @faraazkhan @h0tbird @benjigoldberg

**Comment by benjigoldberg** [comment]
@skunkwerk @mattfarina you should be able to override this on installation since we're using the zookeeper chart as a dependency.

aka
`helm install incubator/kafka --set zookeeper.servers=5`

or you could add the block 
```
zookeeper:
    servers: 5
```
to an override `values.yaml`

Does that work for your needs or do we want to explicitly call this out in the default values?
