### ISSUE TITLE
[stable/traefik] add an option to deploy traefik as daemonset

### ISSUE THREAD

**Issue by dfang** [helm/charts#3190]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
FEATURE REQUEST

**Version of Helm and Kubernetes**:
> helm version
Client: &version.Version{SemVer:"v2.7.2", GitCommit:"8478fb4fc723885b155c924d1c8c410b7a9444e6", GitTreeState:"clean"}

**Which chart**:
stable/traefik

**What happened**:

**What you expected to happen**:
add an option to deploy traefik as daemonset

**Comment by mattfarina** [comment]
cc @krancour

**Comment by krancour** [comment]
This has been discussed extensively in this PR: https://github.com/kubernetes/charts/pull/477

tl;dr: While the reasons for wanting to do this are understood, this isn't a safe way to scale Traefik.

**Comment by dfang** [comment]
hi, @krancour 

i send a [pull request](https://github.com/kubernetes/charts/pull/3191/files) for this a couple of days ago.  i know [deployment is more scalable than daemonset](https://docs.traefik.io/user-guide/kubernetes/#deploy-trfik-using-a-deployment-or-daemonset), but if i just want to deploy traefik on minikube for a test, i prefer daemonset. However we can set default deployType(if you think deploymentModel is more accurate, i can change it) to deployment.

**Comment by hlascelles** [comment]
If the goal is to "scale with the cluster" (our use case), could an alternative be a Deployment with the [pod nanny](https://github.com/kubernetes/autoscaler/tree/master/addon-resizer)? I don't know if that avoids the unsafe Traefik scaling problems -  I suspect not, but it would go well with a Deployment change.

**Comment by krancour** [comment]
@hlascelles I don't think that's necessary. Traefik's own docs now show an example of scaling using a DaemonSet, so we're taking a cue from that and assuming it's not actually as unsafe or naive an approach as we'd once feared. There's already a PR open to address this. #3191

**Comment by m-osmani** [comment]
i would really appreciate this feature.

my on-prem setup exists of 3 nodes (1 x master & 2 nodes).

i have deployed traefik based on the stable helm chart with externalIP + Letsencrypt.
Everything works execpt "traefik.ingress.kubernetes.io/whitelist-source-range", the reason is that the client ip is not forwarded to traefik.

if i change the option externalTrafficPolicy to "Local" then the client ip is available through X_FORWARDED_FOR but **only** over the NodePorts but not directly over the custom externalIP-80/443 (caused by kube-proxy - iptables - nat).

I know that the idea is to have a LB in front of traefik which will talk over proxy-protocol but in my case i dont want an external LB.

From my point of view its enough for small setups  to have a reverse proxy (traefik ingress controller) to expose services to the outside world.

Based on this sentence [DaemonSets can be run with the NET_BIND_SERVICE capability, which will allow it to bind to port 80/443/etc on each host. This will allow bypassing the kube-proxy, and reduce traffic hops.](https://docs.traefik.io/user-guide/kubernetes/#deploy-traefik-using-a-deployment-or-daemonset) i think that it would work.
