### ISSUE TITLE
[stable/redis-ha] Announced service no longer working

### ISSUE THREAD

**Issue by thecodeassassin** [helm/charts#3197]
**Version of Helm and Kubernetes**:
```
Client: &version.Version{SemVer:"v2.5.1", GitCommit:"7cf31e8d9a026287041bae077b09165be247ae66", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.7.2", GitCommit:"8478fb4fc723885b155c924d1c8c410b7a9444e6", GitTreeState:"clean"}

```
kubernetes version: 1.8.3-gke.0

**Which chart**:

stable/redis-ha version 2.0.0

**What happened**:

Because the main service was deleted in 2.0.0 all the applications using the announced service no longer work. The cluster can only be reached through the master service.

**What you expected to happen**:

This should work:
```
2. Connect using the Redis CLI:

  redis-cli -h my-name-redis-ha.default.svc.cluster.local

```

But because the service was deleted. This endpoint no longer exist, causing the applications that use this endpoint to fail.

Also, persistence seems to be unavailable in version 2.0.0.

**How to reproduce it** (as minimally and precisely as possible):

* Install version 2.0.0 of this chart
* try to reach the cluster using the announced service URL.

**Comment by mattfarina** [comment]
cc @prydonius @tompizmor @sameersbn

**Comment by prydonius** [comment]
cc @ianmaddox @smileisak as this is related to the redis-ha chart

**Comment by smileisak** [comment]
cc @ianmaddox

**Comment by afreeland** [comment]
Was curious if this was resolved or what the proper workaround was.  I too cant connect to `my-name-redis-ha.default.svc.cluster.local`.  I thought maybe it was doing something stealthy in DNS somewhere or I was just missing something obvious.

Does connecting to the sentinels service work as desired from a redis client perspective. Not sure of the significance of the master service... 

Something like:
```
var Sentinel = require('redis-sentinel');
var endpoints = [{ host: my-name-redis-ha-sentinel.default.svc.cluster.local, port: 26379 }];
```

**EDIT**
Looks like the sentinel service works as desired as long as you are in the cluster, as expected. However, I am curious how people run their local environments.  Since the sentinels just return an IP address of the current master, it just exposes out the masters ClusterIP which is inaccessible  outside of cluster.  What is the best way people are handling this without altering client connection and still leveraging sentinels?

cc @ianmaddox

**Comment by novakg** [comment]
Is it optimal to access the Redis cluster through the master service, or is this a bug?

**Comment by emanuelecasadio** [comment]
I confirm I cannot resolve the name `my-name-redis-ha.default.svc.cluster.local`but I can indeed resolve the name `my-name-redis-ha-master-svc.default.svc.cluster.local`

**Comment by sneerin** [comment]
also, you can't find it using variable, e.g. kubectl exec my-nginx-3800858182-e9ihh -- printenv | grep REDIS doesn't return anything thought other items works fine
