### ISSUE TITLE
[stable/redis-ha] Upgrade to 2.0.0 (Redis 4.0.6R2) is not stable

### ISSUE THREAD

**Issue by thecodeassassin** [helm/charts#3237]
**Is this a request for help?**:

Yes, since upgrading to 2.0.0 we only had crashed. Note that we use preemtible instance on google cloud (same as spot instances). When the nodes periodically go down the redis-ha setup completely fails and doesn't come back up. This is in part due to using redis 4.0.6R2, we reverted to 4.0.2 and all the failures were gone. When we switched back to 4.0.6R2 the same thing happened and it crashed our elasticsearch cluster.

Version of Helm and Kubernetes:

```
Client: &version.Version{SemVer:"v2.5.1", GitCommit:"7cf31e8d9a026287041bae077b09165be247ae66", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.7.2", GitCommit:"8478fb4fc723885b155c924d1c8c410b7a9444e6", GitTreeState:"clean"}
```
kubernetes version: 1.8.3-gke.0

Which chart:
stable/redis-ha version 2.0.0

**What happened**:

We received thousands of messages per second on our elasticsearch cluster and it actually crashed our monitoring platform. The reason was redis spewing out the following messages.

```
an 04 09:50:05 api-cache-acceptance-redis-ha-master-0-acceptance acceptance[sentinel]:  Current master is 
Jan 04 09:50:05 api-cache-acceptance-redis-ha-master-0-acceptance acceptance[sentinel]:  BusyBox v1.27.2 (2017-11-28 16:17:30 GMT) multi-call binary.
Jan 04 09:50:05 api-cache-acceptance-redis-ha-master-0-acceptance acceptance[sentinel]:  Usage: grep [-HhnlLoqvsriwFE] [-m N] [-A/B/C N] PATTERN/-e PATTERN.../-f FILE [FILE]...
Jan 04 09:50:05 api-cache-acceptance-redis-ha-master-0-acceptance acceptance[sentinel]:  Search for PATTERN in FILEs (or stdin)
Jan 04 09:50:05 api-cache-acceptance-redis-ha-master-0-acceptance acceptance[sentinel]:  	-H	Add 'filename:' prefix
Jan 04 09:50:05 api-cache-acceptance-redis-ha-master-0-acceptance acceptance[sentinel]:  	-h	Do not add 'filename:' prefix
Jan 04 09:50:05 api-cache-acceptance-redis-ha-master-0-acceptance acceptance[sentinel]:  	-n	Add 'line_no:' prefix
Jan 04 09:50:05 api-cache-acceptance-redis-ha-master-0-acceptance acceptance[sentinel]:  	-l	Show only names of files that match
Jan 04 09:50:05 api-cache-acceptance-redis-ha-master-0-acceptance acceptance[sentinel]:  	-L	Show only names of files that don't match
Jan 04 09:50:05 api-cache-acceptance-redis-ha-master-0-acceptance acceptance[sentinel]:  	-c	Show only count of matching lines
Jan 04 09:50:05 api-cache-acceptance-redis-ha-master-0-acceptance acceptance[sentinel]:  	-o	Show only the matching part of line
Jan 04 09:50:05 api-cache-acceptance-redis-ha-master-0-acceptance acceptance[sentinel]:  	-q	Quiet. Return 0 if PATTERN is found, 1 otherwise
Jan 04 09:50:05 api-cache-acceptance-redis-ha-master-0-acceptance acceptance[sentinel]:  	-v	Select non-matching lines
Jan 04 09:50:05 api-cache-acceptance-redis-ha-master-0-acceptance acceptance[sentinel]:  	-s	Suppress open and read errors
Jan 04 09:50:05 api-cache-acceptance-redis-ha-master-0-acceptance acceptance[sentinel]:  	-r	Recurse
Jan 04 09:50:05 api-cache-acceptance-redis-ha-master-0-acceptance acceptance[sentinel]:  	-i	Ignore case
Jan 04 09:50:05 api-cache-acceptance-redis-ha-master-0-acceptance acceptance[sentinel]:  	-w	Match whole words only
Jan 04 09:50:05 api-cache-acceptance-redis-ha-master-0-acceptance acceptance[sentinel]:  	-x	Match whole lines only
Jan 04 09:50:05 api-cache-acceptance-redis-ha-master-0-acceptance acceptance[sentinel]:  	-F	PATTERN is a literal (not regexp)
Jan 04 09:50:05 api-cache-acceptance-redis-ha-master-0-acceptance acceptance[sentinel]:  	-E	PATTERN is an extended regexp
Jan 04 09:50:05 api-cache-acceptance-redis-ha-master-0-acceptance acceptance[sentinel]:  	-m N	Match up to N times per file
Jan 04 09:50:05 api-cache-acceptance-redis-ha-master-0-acceptance acceptance[sentinel]:  	-A N	Print N lines of trailing context
Jan 04 09:50:05 api-cache-acceptance-redis-ha-master-0-acceptance acceptance[sentinel]:  	-B N	Print N lines of leading context
Jan 04 09:50:05 api-cache-acceptance-redis-ha-master-0-acceptance acceptance[sentinel]:  	-C N	Same as '-A N -B N'
Jan 04 09:50:05 api-cache-acceptance-redis-ha-master-0-acceptance acceptance[sentinel]:  	-e PTRN	Pattern to match
Jan 04 09:50:05 api-cache-acceptance-redis-ha-master-0-acceptance acceptance[sentinel]:  	-f FILE	Read pattern from file
```

**What you expected to happen**:
No errors or at least not this many.

**How to reproduce it** (as minimally and precisely as possible):
* Install the helm chart with default values in a node pool of at least 4 nodes, and shut down the  instances one-by-one.

@ianmaddox @smileisak @prydonius @tompizmor @sameersbn

**Comment by mattfarina** [comment]
cc @smileisak @ianmaddox

**Comment by patricklx** [comment]
I also see this issue. When restarting a Kubernetes node (of 2), the setup fails.
What happens is that the new pods are created and old ones terminated, but just before terminating the new pods see the master on the old node and try to connect to it. The problem is that the PODs dont shutdown after connection failure.
Another issue is that the redis pods are sometimes selecting an old POD as master that is currently in terminating state... and then everything is stuck.
I can see the same behaviour if I scale down the servers to 0 and then fast to 3 again. So without waiting for the old PODs to disappear

**Comment by patricklx** [comment]
even with just one server, you can kill it and the new server will select the killed one... since its still there in terminating state

**Comment by patricklx** [comment]
also quorum with 2 is not working, don't know what is the expected behaviour...
in the redis docs they explain as example that it should work.
with 3 nodes , each 1 sentinel/redis. 
But later they explain that also authorization is required from majority to make failover. (with quorum 2 would be 3 sentinels)
But if node of master+sentinel crashed, then there is no majority since only 2 are available.
So we need to set quorum to 1 (2 sentinels required). Or better make it configurable through ENV.
Another thing I read is that redis-sentinel and redis instances should be added one by one.
So StatefulSet would be better here. Deployments just starts all at the same time. This would probably also fix other issues, like selection pods that are still terminating or pending

**Comment by smileisak** [comment]
cc @ianmaddox

**Comment by bzumhagen** [comment]
We are seeing this same behaviour.

**Comment by tuananh** [comment]
any update?

**Comment by bzumhagen** [comment]
@tuananh I have been working on this and am planning to submit my changes for review soon (In the next few days).

**Comment by tuananh** [comment]
@bzumhagen that's awesome.

**Comment by thecodeassassin** [comment]
@bzumhagen thanks!

**Comment by bzumhagen** [comment]
FYI, my PR is up.
