### ISSUE TITLE
Plex Media Server chart

### ISSUE THREAD

**Issue by munnerz** [helm/charts#3289]
I've developed a Plex Media Server helm chart. I'm considering submitting it upstream if it would be accepted? https://github.com/munnerz/kube-plex

Currently it also enables 'remote transcoding' (dispatching transcode jobs as individual pods across the Kubernetes cluster). I've opened https://github.com/munnerz/kube-plex/issues/14 to provide the option to *disable* this behaviour, which I imagine will make the more paletable upstream. I'd love to get some feedback on what the upstream requirements would be for this! 😄

**Comment by mattfarina** [comment]
As a plex user, I'm happy to see this. And, I like the idea of using jobs to transcode media. That's a good direction to go in. I think you're idea of using the shim and transcoding as an opt-in (or opt-out).

In the chart itself, this mostly looks well put together. I do have a couple notes:

* Use tagged versions of images (for reproducibility) instead of latest. 
* Use apps/v1beta2 instead of app/v1. Only Kubernetes 1.9 supports apps/v1 and we support more than that.

Please feel free to ping me if you create a PR for the chart here.

**Comment by davidkarlsen** [comment]
@munnerz can this be re-attempted? I'd love to see it in the official repo!
