### ISSUE TITLE
[stable/concourse] Support pruning of stalled workers.

### ISSUE THREAD

**Issue by ahume** [helm/charts#3365]
**FEATURE REQUEST**

When an underlying node instance is shutdown without proper termination of worker pods, they move into a `stalled` state. When the pod is restarted on an alternative node it will not register back with tsa until a prune-worker command is run. 

Could it be possible for the worker pod to recognise when it has got in to a `stalled` state (all I can see in the logs is repeated printing of `Process exited with status 1`) and issue a prune-worker command to concourse?

A primary use case for this is to be able to run worker pods on preemptible VM instances on GKE/GCE.

**Comment by ahume** [comment]
Further investigation, this may not be a chart related root cause (although possibly the chart could work around it?) https://github.com/concourse/concourse/issues/1497

**Comment by ahume** [comment]
@william-tran Hello. Wondering if you have a view here, as I know you've done a bunch of work on worker lifecycle.

**Comment by 2color** [comment]
I'm experiencing the same problem with the official helm chart.

Running the `fly prune-worker` command resolves the restart loop of the pod, whereby the logs are repeated `Process exited with status 1`.

**Comment by william-tran** [comment]
@ahume @2color To deal with this I've resorted to another app polling the /api/v1/workers endpoint and `DELETE` ing workers that are stalled. It's not possible to do this from the worker itself, and the team is aware that retire-worker should succeed when the worker is stalled (instead of `Process exited with status 1`), but they're looking at a big revamp of how the web and worker synchronizes state that should make all this go away.

https://github.com/concourse/concourse/issues/1959#issuecomment-360263416

**Comment by ahume** [comment]
@2color We have used the same solution for the time being. A cronjob in the cluster that runs every minute to remove stalled workers.

**Comment by tanner-bruce** [comment]
@ahume @william-tran are either of you able to share your code for the poll & delete cronjob?

**Comment by william-tran** [comment]
@tanner-bruce here's a snippet of java, which is what it's implemented in on our end (we have a complimentary app that does more than the poll & delete)
