### ISSUE TITLE
kubernetes.default.svc.cluster.local

### ISSUE THREAD

**Issue by Flowkap** [helm/charts#4461]
BUG REPORT

**Version of Helm and Kubernetes**:

Helm version 2.8.2
Kubernetes 1.9,3 (Hypercube CoreOS.0)

**Which chart**:

rabbitmq-ha

**What happened**:

Pods won't connect to  cluster_formation.k8s.host

**What you expected to happen**:

Connect to it.

**How to reproduce it** (as minimally and precisely as possible):

We used a custom cluster_name but the configmap template uses the fully qualified default name and is not configurable. 

It should eiterh use kubernetes.default or be configurable in terms of cluster_name 

Line 58 https://github.com/kubernetes/charts/blob/master/stable/rabbitmq-ha/templates/configmap.yaml

**Anything else we need to know**:

**Comment by Flowkap** [comment]
Bump?

**Comment by JamesonNetworks** [comment]
Seeing the same using Helm 2.9.1 and Kubernetes 1.11. I'm getting stuck in CrashLoopBackoff with:

{"Kernel pid terminated",application_controller,"{application_start_failure,rabbit,{bad_return,{{rabbit,start,[normal,[]]},{'EXIT',{{case_clause,{error,\"{failed_connect,[{to_address,{\\"kubernetes.default.svc.cluster.local\\",443}},\n I'm assuming this is the same thing you are seeing @Flowkap ?

**Comment by Flowkap** [comment]
Seems so. This is definitely a big as the value in the chart is fix but cluster name definitely is configurable.

**Comment by JamesonNetworks** [comment]
@Flowkap Was able to work around this be providing a values.yml file that contained the IP and port of the kubernetes host instead of the DNS name. The two lines were:

      cluster_formation.k8s.host = <ip>
      cluster_formation.k8s.port = 6443

Not sure if it respects the port or not but I put it in for good measure. The rest of the file looked just like https://github.com/kubernetes/charts/blob/master/stable/rabbitmq/values.yaml . You can specify the value file on the command line when you install with helm:

helm install -f values.yaml --namespace=<namespace>

**Comment by arcana261** [comment]
Same problem here...

**Comment by amolmishra23** [comment]
Same problem even now. I get the same issue listed above. Even after trying to do @JamesonNetworks  solution, doesnt solve the issue.
