### ISSUE TITLE
traefik provide NodePort for dashboard

### ISSUE THREAD

**Issue by fragtom** [helm/charts#4699]
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
FEATURE REQUEST

**Version of Helm and Kubernetes**:

Client: &version.Version{SemVer:"v2.7.0", GitCommit:"08c1144f5eb3e3b636d9775617287cc26e53dba4", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.7.2", GitCommit:"8478fb4fc723885b155c924d1c8c410b7a9444e6", GitTreeState:"clean"}

kubernetes 1.9.2

**Which chart**:

https://github.com/kubernetes/charts/tree/master/stable/traefik

**What happened**:

On any new install of helm chart, the port for dashboard (svc) changes..

$ kubectl -n kube-system get svc traefik-with-ui-traefik -w
NAME                      TYPE       CLUSTER-IP     EXTERNAL-IP   PORT(S)                                     AGE
traefik-with-ui-traefik   NodePort   10.100.33.76   <none>        80:30953/TCP,443:32541/TCP,8080:30423/TCP   30m

**What you expected to happen**:

Looking for setting service.NodePort.dashboard or similar

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by krancour** [comment]
> NAME TYPE CLUSTER-IP EXTERNAL-IP PORT(S) AGE
traefik-with-ui-traefik NodePort 10.100.33.76 80:30953/TCP,443:32541/TCP,8080:30423/TCP 30m

The service you're looking at doesn't appear to be the service for the dashboard. It is the service for Traefik itself.

There is no reason for the service for the dashboard to ever be of any type other than `ClusterIP` because once Traefik is working and handling ingress, Traefik becomes the proxy to all the other services in the cluster, including its own dashboard.

If it's the ports for Traefik itself (i.e. not the dashboard) that you're concerned about the unpredictability of, have a closer look at `values.yaml`, because those can already be defined explicitly if you choose.

**Comment by fragtom** [comment]
In my case, I look for the svc behind 30423, I guess, thats dashboard for using the PING request there. In my AWS setup, the NodePort 30953 is the traefik port. The ALB routes the traffic to that. My challenge is to connect the health check correctly. I cannot use the 30953 (traefik) for requesting PING. I did use the 30432/TCP for health check, that works. 

![screen shot 2018-04-04 at 17 35 52](https://user-images.githubusercontent.com/586528/38352889-f1af9bbe-38b4-11e8-8c70-f41978d4e3d0.png)

**Comment by krancour** [comment]
> In my case, I look for the svc behind 30423

That is not the dashboard. (Even if it were, what you're doing isn't right.) The following shows that 30423 is mapped to 8080 in the Traefik pod. 8080 is an endpoint for metrics gathering (and it might not even be enabled / listening). Do not involve this port in your healthchecks.

> NAME TYPE CLUSTER-IP EXTERNAL-IP PORT(S) AGE
traefik-with-ui-traefik NodePort 10.100.33.76 80:30953/TCP,443:32541/TCP,8080:30423/TCP 30m

The pod's ports 80 and 443 (mapped to 30953 and 32541, respectively) are the HTTP and HTTPS (respectively) proxies for _everything else_ in your cluster that has an ingress. That includes the dashboard.

Take a step back... if all you want to do is get the healthchecks working correctly, don't concern yourself with the dashboard. Concern yourself only with the proxies on 80:30953 and 443:32541.

All this having been said, it's not clear to me why you're setting all of this up manually in the first place. If you're deploying to a k8s cluster in Amazon, let Traefik's service be of the default type-- `LoadBalancer`-- instead of `NodePort`, which is an override you appear to have chosen yourself.

When the service is of type `LoadBalancer`, an ELB will be provisioned and configured correctly for you _automatically_. If you feel it needs any fine-tuning, that can all be accomplished through annotations on the service and those can already be set by adding options to the `values.yaml`.
