### ISSUE TITLE
[stable/mongodb-replicaset] won't start with TLS enabled

### ISSUE THREAD

**Issue by jasperfect** [helm/charts#4773]
**Is this a request for help?**:
request
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
bug report

**Version of Helm and Kubernetes**:
helm: 2.8.2
kubernetes: 1.9.6

**Which chart**:
stable/mongodb-replicaset

**What happened**:
mongod won't startup with TLS enabled

**What you expected to happen**:
start mongod with TLS enabled

**How to reproduce it** (as minimally and precisely as possible):
tls:
  /# Enable or disable MongoDB TLS support
  enabled: true

**Anything else we need to know**:
1. "--ssl" is an invalid flag to mongod, should be changed to "--sslMode requireSSL", or better only set sslMode in configmap, since on-start.sh used by peer-finder only reads from mongo.conf.
2.  mongo shell flags configured in "args:" won't be picked up by mongo cli in livenessProbe, which gets mongod killed again and again.

**Comment by unguiculus** [comment]
Would you mind creating a PR to fix this?

@saschagrunert Could you have a look as well, since you contributed SSL support?

**Comment by saschagrunert** [comment]
I will also have a look into this but I am not sure why it should not work right now.

**Comment by saplla** [comment]
I'm finding that it's not even getting beyond the bootstrap init container. It seems peer-finder is hanging. I have created a wildcard cert for my namespace but right now the init container isn't completing with chart 3.3.0.

**Comment by saplla** [comment]
There are multiple issues. I can't open a PR because my org hasn't signed the CLA. Here are the issues and fixes:

* `on-start.sh` tries to write `openssl.cnf` to the current working directory which is unspecified. I assume it's root, but either way running `find` doesn't show that file anywhere. The fix is to specify `workingDir: /work-dir` for the `bootstrap` init container. This change also allows `mongo.pem` to be written, which it isn't otherwise.
* The README uses an incorrect path in the sample `configmap` for the `CAFile`. The correct path is `/data/configdb/tls.crt`.
* As @jasperfect mentions, in the stateful set YAML file, `mongod` is invoked with the `--ssl` option which should be `--sslMode=requireSSL`, or come from the mongodb configmap to take the same value. Note: Just the `args` section needs changing, not the `livenessProbe` one.

Using chart 3.3.0, these change have been enough to bring up a mongo cluster with TLS with all members of the stateful set running.

**Comment by anupshrestha** [comment]
@saplla I am seeing the same issue and tried out your changes. It successfully started up the first replica set host but the second is hung on the bootstrap init container stage.

    2018/07/09 20:07:26 Peer list updated
    was []
    now [mongodb-mongodb-replicaset-0.mongodb-mongodb-replicaset.default.svc.cluster.local 
    mongodb-mongodb-replicaset-1.mongodb-mongodb-replicaset.default.svc.cluster.local]
    2018/07/09 20:07:26 execing: /init/on-start.sh with stdin: mongodb-mongodb-replicaset-0.mongodb-mongodb-replicaset.default.svc.cluster.local
    mongodb-mongodb-replicaset-1.mongodb-mongodb-replicaset.default.svc.cluster.local

Would you have any idea why that might be happening? Thanks

**Comment by robertervin** [comment]
Any update to this? I'm running into a similar issue where the init containers appear to get stuck when TLS is enabled

**Comment by saplla** [comment]
@robertervin / @anupshrestha  I'm not sure TBH. The only real difference I can see between the latest chart, 3.5.3 and mine is the latest chart passes `--bind_ip=0.0.0.0` to mongod, but I pass `--bind_ip_all` instead (in the stateful set).
