### ISSUE TITLE
traefik transition from acme.staging=true to false doesn't fetch new certificates

### ISSUE THREAD

**Issue by dangarthwaite** [helm/charts#4932]
$ helm version
Client: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-27T00:13:02Z", GoVersion:"go1.9.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-07T11:55:20Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}

Chart: stable/traefik

I successfully retrieved dummy certs from the staging server with acme.staging=True.  Then I changed it to false and upgraded the release.  It failed to retrieve new non-staging certs from letsencrypt.

Expected:  To be able to practice on staging and when ready to go live flip acme.staging from true to false.

I suspect this might involve deleting the PersistentVolume or a helm delete --purge Release.

**Comment by KlavsKlavsen** [comment]
Was this ever resolved?

**Comment by iamliamc** [comment]
I don't think so because we are experiencing the same thing... getting proper dummy cert's from Let's Encrypt, changed acme.staging to false and now we are still getting dummy cert's after running a helm upgrade --install with the new values.yaml...

Bit of a bummer because purging means we will get a new IP in our cluster and have to redo DNS... (we can't reserve static IPs at the moment)
