### ISSUE TITLE
[stable/rabbitmq] The statefullset does not store exchange and queue configuration

### ISSUE THREAD

**Issue by WimDer** [helm/charts#5224]
BUG REPORT 
stable/rabbitmq
version  0.7.6
Kubectl version 1.10.1

Since moving from deployment to statefulset the rabbitmq does not save any configuration data that has changed after installation to a PVC even with PVC enabled. 

This was working in version 0.6.25 where it was still a deployment

So switching off the pod in kubernetes makes the system loose its configuration when kubernetes restarts another one.

I would expect the PVC stores this configuration and the rabbitmq in the new pod uses it. as was the case before.

Any suggestions would be very much appreciated.

**Comment by james-masson** [comment]
Yes - seems weird that it's implemented in this way, in this helm chart.

The problem comes down to the fact that the pod ip changes every time, and the Mnesia DB path is based on this. So the mnesia DB does actually survive the pod deletion/recreation on the persistant volume - but it's simply not used.

One solution would be to set RABBITMQ_MNESIA_DIR to a fixed thing - probably the stateful set instance number. This would ensure that the DB is re-used every time, rather than ignored.
https://www.rabbitmq.com/relocate.html

My short term solution is to use a RMQ policy to ensure all my queues are HA, and run with at least 3 nodes. That way, when each node goes down for replacement, the others can re-replicate state back to the new one on startup. Of course, this doesn't help if _all_ the pods are down.
