### ISSUE TITLE
[stable/datadog] Add ability to use service with DaemonSet

### ISSUE THREAD

**Issue by praseodym** [helm/charts#5671]
Currently the stable/datadog chart only configures a Kubernetes Service when the Datadog Agent is installed as a Deployment, but not when it is installed as a DaemonSet. To use APM (tracing), using the Service is a lot easier than using the DaemonSet directly, because it would require exposing a host port and then using some `fieldRef` trickery to get the correct IP address configured for pods that use tracing.

I'd thus like to suggest to make the Service configurable even for DaemonSet installations. If there is another best practice (e.g. installing a DaemonSet for host monitoring and a Deployment for APM) then this should be documented somewhere.

**Comment by xvello** [comment]
First and foremost, please keep in mind that using a load-balanced `Service` will require you to properly force the metrics/traces hostname at emission, as the hostname added by the agents will be non-deterministic. This is why our recommended method is to directly talk to the local agent via a host port, or a unix socket (for dogstatsd).

Adding the service to daemonset installs is in our roadmap for the coming weeks, but a contribution would be welcome on that. To enable the service, one needs to update [the service definition](https://github.com/kubernetes/charts/blob/master/stable/datadog/templates/service.yaml) to be enabled with a common `.Values.datadog.exposeService` option instead of only the ` .Values.deployment.enabled` option. Previous behaviour should be kept though.

Our "big plan" is to merge back all `.Values.daemonset` and `.Values.deployment` options into the `.Values.datadog` object, in order to homogenise the two deployment cases, that diverged too much, see https://github.com/kubernetes/charts/pull/6382 for more context.

**Comment by plumdog** [comment]
@xvello I find myself in a similar situation. I want to report statsd things from an application.

I have found the `daemonset.useHostPort` configuration option:
https://github.com/helm/charts/blob/01f7b1664a37f3b057c2894bac1fd5e278c32806/stable/datadog/templates/daemonset.yaml#L39-L44

which I think is what you were referring to above. Then as per https://docs.datadoghq.com/tracing/setup/kubernetes/#deploy-agent-daemonset I would use the
```
env:
  - name: DD_AGENT_SERVICE_HOST
    valueFrom:
      fieldRef:
        fieldPath: status.hostIP
  - name: DD_AGENT_SERVICE_PORT
    value: 8126
```
snippet - or something a bit like it - in my application pods. Also, I assume that accessing the statsd port at 8125 would work too (though the linked docs make little mention).

I would ideally find a way of making this work without using a hostPort. Now that #6382 is merged, are there any other options?

**Comment by sammerry** [comment]
We're attempting to use the helm chart in the daemonset configuration. We've been able to use bash to send a custom metric to the daemonset but it required adding an un-documented environment variable to the helm chart.

```
   env:
     - name: DD_BIND_HOST
       value: "0.0.0.0"
```

The helm chart exposes 8125 as the metrics port. However setting the following on our python service doesn't seem to find the datadog agent.
```
env:
  - name: DD_AGENT_SERVICE_HOST
    valueFrom:
      fieldRef:
        fieldPath: status.hostIP
  - name: DD_AGENT_SERVICE_PORT
    value: 8126
```

exec'ing into the pod and testing with the following command does trigger an event.
```
echo -n "custom_metric:160|g|#shell" | nc -w 1 -u $DD_AGENT_SERVICE_HOST $DD_AGENT_SERVICE_PORT
```

however during that same session triggering a metric using the python agent doesn't trigger an event
```
from datadog import statsd
statsd.gauge('custom_metric', 42)
```

My guess is that you'r required to manage your own environment variables on the client side.
