### ISSUE TITLE
[stable/spark] Zepplin Config Not found

### ISSUE THREAD

**Issue by mhamilton723** [helm/charts#6784]
**Version of Helm and Kubernetes**:

**Which chart**:
Spark

**What happened**:
Zepplin Config not Found, is fixed when removing these two commits 
[spark/stable] Added Horizontal pod autoscaler according to documenta…  …

@jonaseck2
@k8s-ci-robot
jonaseck2 authored and k8s-ci-robot committed 8 days ago
 
[spark/stable] Added persistence for notebooks and configuration (#3345)  …

@jonaseck2
@k8s-ci-robot
jonaseck2 authored and k8s-ci-robot committed 8 days ago

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):
Install the chart without changing anything on a new AKS cluster

**Anything else we need to know**:

**Comment by ekeroid** [comment]
Looks like a bug that is introduced in the commit "Added persistence for notebooks and configuration". 

I believe the problem is in the file "spark-zeppelin-deployment.yaml", lines 56 & 65. AFAIKT the condition "{{- if .Values.Zeppelin.Persistence.Config }}" is wrong and the container is trying to mount a  pvc that is not allocated (the pvc is not allocated, since persistent storage is turned off by default).

The install won't work unless you enable persistent storage:
helm install stable/spark --set Zeppelin.Persistence.Config.Enabled=true --set Zeppelin.Persistence.Notebook.Enabled=true

**Comment by VinceMD** [comment]
As mentioned here , setting persistence to true does not work if using multiple zones (GCE or AWS):
https://github.com/helm/charts/issues/7478

Is there a way to get this chart working?
