### ISSUE TITLE
[stable/elastalert] Support custom SSL certificates

### ISSUE THREAD

**Issue by sneko** [helm/charts#7095]
Hi @mumoshu!

I saw you are a maintainer of the ElastAlert Chart and I was wondering if you plan to support custom SSL certificates?

Because in my case I would like to specify some properties like:
```
  ssl_version TLSv1_2
  ca_file "/.../ca.crt"
  client_key "/.../es01.key"
  client_cert "/.../es01.crt"
```
(name properties are not the ones from ElastAlert, it's just an example)

One of the possible way to do that would be to authorize custom volume mounts.

Thank you 😃 !

**Comment by sneko** [comment]
Having a look at OWNERS it seems I could have mention @jertel too 😄

**Comment by jertel** [comment]
Hi @sneko,

Have you seen the open PR #6733? It is attempting some of what you're requesting, but it appears the submitter hasn't finished signing the CLA form or addressed the merge issues. Perhaps you'd be interested in using that PR as a template for one that you could submit, along with your volume suggestions for the custom certificate options.

**Comment by sneko** [comment]
Hi! @jertel thank you for the answer and sorry about answering late I'm quite busy currently 😢 

I noticed too that the PR is not letting the choice to the user about certificate files location.

I would have liked to participate to the PR but I can't presently. As soon as I'm done with my huge TODO list I will dig into it 😄

**Comment by kskewes** [comment]
Yes it would be preferable to extend my minor PR and mount the certs into ElastAlert container, otherwise ElastAlert creates log entries about insecure certificates.
I added the verify_certs switch into the chart as a quick way to verify functionality with Elastic Search over TLS.
I have since moved away from Helm Charts so please go ahead if you'd like to use it as a base, push commits to it or otherwise. I'm happy to close that PR too.

**Comment by sneko** [comment]
Hi,

I finally had the time to make the required changes : #7629

@kskewes you can close your PR.

Have a good day,
