### ISSUE TITLE
[stable/mongodb] No credentials used after upgrade 

### ISSUE THREAD

**Issue by ghost** [helm/charts#7169]
**Is this a request for help?**: yes

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): bug report

**Version of Helm and Kubernetes**:
Helm version:

Client: &version.Version{SemVer:"v2.10.0-rc.1", GitCommit:"aa98e7e3dd2356bce72e8e367e8c87e8085c692b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.10.0-rc.1", GitCommit:"aa98e7e3dd2356bce72e8e367e8c87e8085c692b", GitTreeState:"clean"}

Kubernetes version:

Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.4", GitCommit:"5ca598b4ba5abb89bb773071ce452e33fb66339d", GitTreeState:"clean", BuildDate:"2018-06-06T08:13:03Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.4", GitCommit:"5ca598b4ba5abb89bb773071ce452e33fb66339d", GitTreeState:"clean", BuildDate:"2018-06-06T08:00:59Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

**Which chart**:

mongodb

**What happened**:

If you deploy stable/MongoDB with usePassword=true, mongodbUsername and mongodbDatabase it works fine. Authentication is on and my application can connect to mongodb. But if I upgrade chart of my application with helm my sub chart mongodb doesn't have authentication on anymore so I can't login with my credentials.

**What you expected to happen**:

After upgrading it should work as it works for installation. I don't have any clue why on upgrade it misses values provided and used during the installation and goes for not using a password.

**How to reproduce it** (as minimally and precisely as possible):

Use mongodb in any chart as sub chart and install it providing in values.yaml:

mongodb:
  usePassword: true
  mongodbUsername: "admin"
  mongodbDatabase: "push"

After deployment go to the logs and shell and check that you can log in to a database with your credentials. At the end try to update release with helm and check if login still works.

**Anything else we need to know**:

**Comment by GiORg1** [comment]
It's my first issue on Github, so if something is unclear or missing please let me know and I will provide additional details upon necessity

**Comment by gboston** [comment]
Hi, the first time you deploy the helm chart it will create a secret that is used as credentials for configuration of the MongoDB. If you don't reuse that secret when updating the helm chart, it will overwrite the root password and you won't be able to reconnect as a root user to the MongoDB database. So make sure you specify the mongodbRootPassword or reuse the secret from initial install.

**Comment by GiORg1** [comment]
@gboston Thing is that I don't want to use root user. And still, with this approach, it's unclear how I should save the old secret. When MongoDB is recreated with its Parent Chart application there is no solution to do this in a clean way. If you have any suggestion I will be happy to listen.

But my problem is unanswered, why MongoDB on upgrade decides to not use credentials and doesn't create a username?

**Comment by gboston** [comment]
You have to specify the secret with "existingSecret" when you are doing an upgrade otherwise it will just create a new secret.

**Comment by GiORg1** [comment]
@gboston Thanks for your help. I will try this approach later next week and reply if it solves my problem

**Comment by GiORg1** [comment]
@gboston 

Hello again. I think approach you suggested doesn't work. After using the helm upgrade with existingSecret operation fails saying that there is no secret named **secretName**. When I check secrets it really doesn't exist. Maybe upgrade command destroys it before pod tries to access it.

So to show my steps I am running these commands:

`helm install --name mongodb-test --namespace polygon stable/mongodb --set mongodbUsername=admin,mongodbDatabase=push`

And to upgrade:

`helm upgrade --namespace polygon mongodb-test stable/mongodb --set existingSecret=mongodb-test --recreate-pods`

I've tried without recreate-pods argument and it gets me the same result.

**Comment by ryanapking** [comment]
I assume interest in this is long gone after six months, but I've been running into this same issue, which isn't fully explained above. I think it's a question of documentation, because fixing the issue within Helm doesn't seem practical/possible.

There are two things that are not clearly documented:

1. Once the existingSecret value is set, any secret that was created by the chart is deleted. The relevant logic from templates/secrets.yaml:
```
{{ if and .Values.usePassword (not .Values.existingSecret) -}}
...our secret manifest
{{- end }}
```
This means that any password randomly generated by the chart will be removed if you try to reuse it by setting existingSecret, as suggested before.

2. If you don't set existingSecret, because you realized the above, the chart will just create a new random password with each upgrade. These new passwords will not work because they won't match the passwords that were initially created. 

There doesn't seem any way, within Helm, to resolve these issues.

So possible ways to work with this:

1. Create your own secret and set it as existingSecret during the install. It will need the data points from that secrets.yaml template: mongodb-root-password, mongodb-password, mongodb-replica-set-key

2. Just --set the passwords on install and roll with it. As I understand it, the way that Helm stores config maps is comparable to using a secret in terms of security.
