### ISSUE TITLE
[stable/wordpress] Chart creates multiple ingresses per host name

### ISSUE THREAD

**Issue by boosh** [helm/charts#7306]
**Is this a request for help?**: No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Bug report

**Version of Helm and Kubernetes**: N/A

**Which chart**: stable/wordpress 2.1.10

**What's the issue?**:
The [Wordpress ingress](https://github.com/helm/charts/blob/c1e2d69c81479c21b04f22dac8f6005dd7474217/stable/wordpress/templates/ingress.yaml) `ranges` over `.Values.ingress.hosts`. This is suboptimal because it will create one ingress per hostname. A better approach would be to create a single ingress with multiple rules and multiple TLS configurations, for example like the [Keycloak ingress](https://github.com/helm/charts/blob/48ed41255035c10ba0b97c735ab8ad5d3108a840/stable/keycloak/templates/ingress.yaml) does.

The Wordpress ingress also hard-codes the annotation `ingress.kubernetes.io/secure-backends: "true"` if TLS is true. This [has been deprecated](https://github.com/kubernetes/ingress-nginx/blob/master/docs/user-guide/nginx-configuration/annotations.md#secure-backends-deprecated-since-0180), and anyway, annotations shouldn't be hard-coded or it limits their configurability.

**Comment by mattjmcnaughton** [comment]
I'm happy to implement the first component of this - just want to confirm with @migmartri (or someone else involved with the chart) that there isn't an intentional reason for having a separate ingress for each host.

Re the second component. The annotation is only added if `ingress.hosts.tls` is true, so I'm not sure I see the point about limited configurability. The deprecation point is a great one. We'll just want to be careful, because its only deprecated as of 0.18.0, which was released a couple of days ago (and `nginx-ingress` in Charts is still using `0.17.1`).
