### ISSUE TITLE
Add simple charts without PVC

### ISSUE THREAD

**Issue by sebgoa** [helm/charts#82]
While having PVs is key for real setup, for folks who get started with k8s having PV setup is not the default.

I think we need to think about charts 101 which would be charts that don't need PV. and only have volumes HostPath and EmptyDir.

PetSets are great, but we need more simple example like the mariadb one. We had a ton of them in the repo early on.

**Comment by viglesiasce** [comment]
Hey @sebgoa!

I think this would be best handled by the following:
1. `helm create` has a basic layout for an app with a templates service and deployment, maybe using nginx as the example
2. Docs that can take people through simple manual chart creation and then to building out more complex applications

The goal of this repo should be to provide users with real world workable applications. As part of that persistence of some sort will be required in most cases. 

As of 1.4 AWS, GCE, Azure, Gluster, Openstack, vSphere and Minikube all support dynamic PVC provisioning. I think its something that chart maintainers should be able to rely on moving forward. If a platform does not support it we should prod them in the right direction.

I do agree though that the on-boarding experience for charts is lacking but firmly believe that this should be approached as an in depth documentation effort rather than having applications that are packaged but not usable beyond an example. 

One thing to note is that all of the charts that use persistence can have it disabled via a value. Generally `persistence.enabled` can be set to false. 

cc @erictune @prydonius to keep me honest

**Comment by sebgoa** [comment]
Good idea on `helm create`, maybe something like `kubectl run` i.e `helm create --image=ghost`

Didn't know that minikube was supporting dynamic PV in 1.4, that's great.

Agree about real world examples, but some don't need PV (out of the box) like Spark for instance.

A new helm user will try some of these charts and get into an error because of lack of PV. Then will have to dig around to learn about PVs, sending them on on a chase...of course if minikube supports dynamic PV, then it is much less of a problem.

**Comment by viglesiasce** [comment]
Yep I ran into the exact issue you described here with minikube then sent over a PR to those folks and it is now in as of the 0.10.0 release. 

Not all charts need PVs and they shouldnt use them if not required. If the spark chart we have is doing this lets get a PR or issue in place to rectify it. I agree that if its not required it should not be used.

**Comment by prydonius** [comment]
Agreed that the purpose of this repo is to focus on real-world applications, and not examples/scaffolds. There are more charts in incubator right now because we're banking on alpha features (like PVCs) becoming beta within the next few weeks with the 1.4 release, so we'll be able to promote some charts from incubator to stable pretty soon.

I'm not sure about `helm create` bootstrapping a working example chart, maybe that could be an option, but could get annoying as a default (if you use it regularly and have to keep deleting manifests it creates). A good place for example/scaffold charts is in the helm repo under `docs/examples`.

**Comment by prydonius** [comment]
Closing this out since PVC provisioning is now in beta.
