### ISSUE TITLE
[stable/mongodb-replicaset] control restart procedure

### ISSUE THREAD

**Issue by montyz** [helm/charts#8512]
FEATURE REQUEST

After spending a day with a MongoDB consultant, there are some best practices that are hard to achieve with mongodb in this chart:

1. When restarting the members of a replicaset, it is best to restart all the secondaries first. Before restarting the primary it is a good idea to execute `rs.stepDown()` to force the primary to step down and initiate the election of a new primary. See https://docs.mongodb.com/manual/reference/method/rs.stepDown/index.html

2. After restarting a mongo replicaset node, it's a good idea to allow the replication to catch up before shutting down the next node. `rs.status()` gives this information in JSON format. See https://docs.mongodb.com/manual/reference/method/rs.status/#rs.status

My understanding is that blindly restarting the primary node on a heavily loaded mongodb replicaset could lead to data loss as there may be in-memory writes which have not been flushed to the oplog yet.

I don't know that StatefulSets will allow any control over the order of restarting, however a `preStop` container hook could run a command to check if it is primary and if so run the `rs.stepDown()` command.

On starting up, a `readinessProbe` could run the `rs.status()` command and only return when the replication lag is below a given threshold.

**Version of Helm and Kubernetes**:
```
$ k version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:17:39Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.9", GitCommit:"57729ea3d9a1b75f3fc7bbbadc597ba707d47c8a", GitTreeState:"clean", BuildDate:"2018-06-29T01:07:01Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

$ helm version
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
```

**Which chart**:
stable/mongodb-replicaset

**Comment by steven-sheehy** [comment]
1) can rs.stepDown be called on a secondary? Because the preStop command will be ran on all instances. StatefulSets are by design have a specific order of startup and shutdown, but any replica in the StatefulSet can become primary at any time (for example, due to a network partition). I've thought before about increasing the first replica priority so he's more likely to be primary.

2) This functionality is already [present](https://github.com/helm/charts/blob/2bc37c9c1f98c4164512f9fcc95e660e31874996/stable/mongodb-replicaset/init/on-start.sh#L185).

These charts are entirely community supported, so PRs welcome if you have specific changes you want.

**Comment by montyz** [comment]
`rs.stepDown()` will fail on secondaries:
> The method is only valid against the primary and throws an error if run on a non-primary member.

so maybe some JS to only run if the node is primary? Something like `if (db.isMaster()) rs.stepDown()`. I don't know JS though so add correct syntax....
