### ISSUE TITLE
[stable/elasticsearch]: only drain nodes in pre-stop hook if node goes down permanently

### ISSUE THREAD

**Issue by andrenarchy** [helm/charts#8618]
**Is this a request for help?**: No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Feature request

The `pre-stop-hook.sh` script currently drains a ES data node – independent of whether the ES node is terminating temporarily or not. This moves around a massive amount of data unnecessarily, for example if you only want to upgrade the Kubernetes cluster where the pod would be rescheduled on another node immediately. I think the ES node draining only makes sense when you scale a ES cluster down. 

**Version of Helm and Kubernetes**: Helm 2.11.0, Kubernetes v1.10.7-gke.6

**Which chart**: stable/elasticsearch

**What happened**: The pre-stop hook drains the ES data node even if it's not terminated permanently.

**What you expected to happen**: Immediate termination of the ES data node pod.

**How to reproduce it** (as minimally and precisely as possible): Just delete a pod and wait...

**Anything else we need to know**: There was a discussion about this in slack with @desaintmartin @rendhalver @simonswine and @rccrdpccl a while ago and I think two contributions are worth mentioning:
* one approach to fix this is to check how many ES nodes are desired: https://github.com/jetstack/elasticsearch-pet/blob/master/pre-stop-hook.sh (@simonswine)
* what happens if ephemeral disks are used? (@rccrdpccl)

**Comment by desaintmartin** [comment]
FYI I have entirely disabled those hooks in my fork. My opinion is that operator should do manual action if he wants to permanently turn down a node.

**Comment by andrenarchy** [comment]
Temporarily I'd also be happy with an option to just disable the hooks. That would certainly be better than waiting for ~3 hours for upgrading a small cluster that usually only took 15min.

**Comment by rendhalver** [comment]
Would either of you mind making a PR to make them optional?

**Comment by desaintmartin** [comment]
There you go. :)

**Comment by arianitu** [comment]
This is crazy, why in the world would this be added as a pre-stop hook? 

What if I want to shutdown the instances for upgrades versions for example? Why would I want to re-balance each nodes shards?

I'm in a situation where I'm trying to shutdown my entire Elasticsearch cluster (for a full upgrade, not a rolling upgrade.) but the data nodes won't shutdown because the stupid pre-stop hook is trying to re-shard everything...

So the gracefulPeriod is 1 hour, but I guess the best thing to do is forcefully stop each node now and remove this horrible feature or whatever this was intended to be?

**Comment by farvour** [comment]
There isn't a big enough face palm for making the default, albeit optional, for this type of action to be true. The entire purpose of a StatefulSet is that k8s will hande the ordered rollout and reattach the PVs that were already claimed for the pod.

Due to this horrendus default, I ended up a graylog ES cluster that lost all of its data when the deadline timeouts exceeded and kube forcefully killed the pod anyway. Luckily I didn't care about the data much, but really? This should be defaulted to `false`. *STATEFUL SET*

**Comment by desaintmartin** [comment]
Hello @farvour,
I suggest you to switch to the official elasticsearch chart at https://github.com/elastic/helm-charts/tree/master/elasticsearch
It adopts a different approach that makes it quite easy to upgrade nodes.

**Comment by farvour** [comment]
Thanks! I will look into this one. 🥳
