### ISSUE TITLE
[stable/prometheus-operator]

### ISSUE THREAD

**Issue by agolomoodysaada** [helm/charts#8669]
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Version of Helm and Kubernetes**: 2.9.1 and 1.11.3

**Which chart**: stable/prometheus-operator

**What happened**: 

Tried installing the chart but got an error

```
Error: apiVersion "monitoring.coreos.com/v1" in prometheus-operator/charts/prometheus-operator/templates/alertmanager/servicemonitor.yaml is not available
```

**What you expected to happen**:

CRDs should be created before ServiceMonitor instances are created for prometheus, alertmanager, and the operator itself. I had to manually turn off self monitor flags.

**How to reproduce it** (as minimally and precisely as possible):

```sh
helm install stable/prometheus-operator
```

**Anything else we need to know**:
@gianrubio

**Comment by vsliouniaev** [comment]
@agolomoodysaada, the ability to use the crd-install hook was only introduced in helm 2.10, which is why the CRDs aren't created for you at the right point in the process.

If you can't upgrade helm you can do this in two releases, creating a deployment of prometheus-operator only and then another one with everything else

**Comment by agolomoodysaada** [comment]
You're right! I'm using Helm 2.9.1. 
Perhaps, we should specify in the README that this chart requires Helm > 2.10
