### ISSUE TITLE
stable/percona uses mysql image

### ISSUE THREAD

**Issue by ReDev1L** [helm/charts#8747]
https://github.com/helm/charts/blob/798226aac49d8f28bca9b6afb03a89df8ce1d467/stable/percona/templates/deployment.yaml#L29

**Comment by g0blin79** [comment]
I probably called my branch in the wrong way, but this PR https://github.com/helm/charts/pull/8978 (that otherwise should be listed here) solve this issue.

**Comment by g0blin79** [comment]
Guys we cannot close this issue. The related PR was not approved or rejected and, at this stage, this chart is unusable simply because **it doesn't use percona image**!!! Then you have two choices: resolve this issue (approving and merging or rejecting giving infos about that) or remove the percona chart from your repo. Tertium non datur.

Please give a feedback or merge.
