### ISSUE TITLE
[stable/rabbitmq-ha] RabbitMQ Timeouts waiting for other pods, if there are data within PersistentVolumes

### ISSUE THREAD

**Issue by marcinbojko** [helm/charts#8783]
**Is this a request for help?**:
NO
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG

**Version of Helm and Kubernetes**:
Client and Server: v2.11.0
kubernetes: 1.11.3
**Which chart**:
stable/rabbitmq-ha

**What happened**:

When used chart with persistant storage, any situation when all StatefulSet pods were down (redeploy, all noded went down) RabbitMQ is unable to be brough to live as it throws: Timeout waiting for mnesia tables.
In set without persistent volumes, it doesn't happen. With a set with persistane volumes, after all pods (rabbitmq cluster nodes) went down at least 2 of them need to communicate with each other to establish a cluster.
It will never happen, as one pod is being constantly restarted and the rest of deploy is waiting for 1 pod to be successful.

**What you expected to happen**:
All pods are dployed (redeployed) in parallel, in the same time, to allow rabbitmq cluster nodes to communicate with each other.

**How to reproduce it** (as minimally and precisely as possible):
Push chart with persisten volumes, redeploy/update set OR
Push chart with persisten volumes, delete all pods in the same time.

**Anything else we need to know**:
I've tested settings in statefulset.yaml:

```yaml
spec:
  podManagementPolicy: Parallel
```
which helped to countermeasure the problem. Now all nodes are being redeployed at the same time, so cluster can be establish with success.

**Comment by steven-sheehy** [comment]
Have you tried to setting to updateStrategy: RollingUpdate (perhaps with a partition) and marking discovery service as tolerating unready endpoints as mentioned in #5879? The rabbitmq-ha default update strategy of OnDelete is not really useful.

**Comment by marcinbojko** [comment]
@steven-sheehy - Yes, I've switched to RollingUpdate, no effect.
About #5879  - I can try to use this, but it's more RabbitMQ issue, not Kubernetes/pod itself. If data exist, cluster won't allow to have one node if he is aware of their previous existence.
Deploying pods in parallel seems to be working.
Can we consider adding extra variable to statefulset template?

**Comment by marcinbojko** [comment]
@steven-sheehy I've checked mentioned annotation, unfortunately no combination of flags and annotations works in this case. The only was I was able to establish rabbitmq was usine mentioned podManagementPolicy.

**Comment by steven-sheehy** [comment]
So in your case, only one pod is actually running at a time when you encounter this scenario, correct? The tolerate unready endpoints will help when multiple are concurrently starting at once. When rabbitmq starts, it attempts to synchronize its distributed mnesia database with its peers. But they can't be reached until they are marked ready unless we tolerate unready. So we definitely need unready annotation which is why I opened PR #8767 previously.

If only one pod is attempting to run then you're right that parallel may be the only way. There is a [PR](https://github.com/helm/charts/pull/7683) for it already and we should definitely expose it as an option, just not sure if making it default is a good idea. With parallel, client will be unable to reach any rabbitmq during a rolling upgrade. Can you also try increasing your partition size so more pods (but not all) can be down at once?

**Comment by steven-sheehy** [comment]
So we definitely can't change the default from OrderedReady to Parallel since it will break upgrades:

> Error: UPGRADE FAILED: StatefulSet.apps "rabbitmq-ha" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden.

I've added the ability to customize podManagementPolicy to my PR since the other PR author doesn't seem to be active. It will be available for new installs for people that need it.

**Comment by marcinbojko** [comment]
@steven-sheehy Thanks for input.
From my internal test:
1. 
```yaml
# Source: rabbitmq-ha/templates/service-discovery.yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
    
  name: qa-shr-mq1-rabbitmq-ha-discovery
```
does exactly nothing in my cluster.
I think we're dealing with 2 separate cases:

1. PersistentVolume: false
In this case, when there is no danger of mnesia tables having there, regardless of how many pods we'll loose, cluster will be up and running.
podManagementPolicy can be OrderedReady.
2. PersistentVolume: true
In this state we can, have situation when we need at least 2 pods being able to communicate with each other during their launch phase. I cannot tell if it should be majority or 2 will be enough, I don't have cluster ready to test this theory. 
Here I'd suggest to switch podManagementPolicy to Parallel, as with any tests I've made only this setting ensured cluster survival.
Now upgrades: I was able to upgrade set (as you mentioned in one of comments for PR, in not production ready way) ONLY when podManagementPolicy was set to Parallel.

I am woried though `service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"` doesn't seem to make any difference in mu setup.

**Comment by marcinbojko** [comment]
Unfortunately adding `publishNotReadyAddresses` as suggested in https://github.com/kubernetes/kubernetes/pull/63742 didn't help either.
The only way I am able to establish a working rabbitmq cluster with previous data on it is to release all pods at once.

**Comment by steven-sheehy** [comment]
@marcinbojko Thanks for testing this with the various options. I didn't even know about publishNotReadyAddresses and that the annotation will be deprecated. I'll add that to my PR.

Yeah, I'm only considering scenarios with persistence enabled. You're definitely right about rabbitmq needing more than one up to start up successfully ( I think a quorum of replicas, but may depend upon how your queues are replicated). In my testing, having tolerate unready only helps if you have two or more un-ready rabbitmq pods running simultaneously (both "Waiting for mnesia tables"). If you have only one running while the other is pending or not scheduled due to statefulset then annotation will do nothing.

For your case you should really consider not running RabbitMQ with an even number of replicas since it won't be able to maintain a quorum during network partitions. And this may be causing some of your issue if all are down and it can't decide on a master to sync messages from.

**Comment by BenCoughlan15** [comment]
@marcinbojko you seem to be correct here, I also got the same issue when one pod went down.
