### ISSUE TITLE
After exposing service via kubectl load balancer, see logon screen but cannot logon 

### ISSUE THREAD

**Issue by sconrod-tester** [helm/charts#9087]
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Version of Helm and Kubernetes**:

**Which chart**:

**What happened**:

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by sconrod-tester** [comment]
Version of Helm and Kubernetes: Most recent on azure

Which chart: Stable Concourse

What happened: Deployed successfully and when using Kubectl port fowarding can logon and access concourse Ok. However, after I configured a load balancer to expose it via an external IP, I can see the logon screen but I cannot logon.

What you expected to happen: 
I expected that I would be able to logon
How to reproduce it (as minimally and precisely as possible):

 kubectl expose deployment mydeploymentnameofconcourseweb --port=80 --target-port=8080 --name=kube-concourse --type=LoadBalancer

**Comment by cirocosta** [comment]
Hey @sconrod-tester ,

<br />

Please correct me if I'm wrong, but, are you facing a redirect to an undesired location when trying to finish the login process?

That might be because `concourse.web.externalUrl` is not set (which is required for these scenarios).

I guess that's something we can improve in the README.

Could you please confirm if that's what's happening for you?

<br />
Thanks!
