### ISSUE TITLE
Why do we have two Redis charts?

### ISSUE THREAD

**Issue by yurrriq** [helm/charts#9185]
**Is this a request for help?**:
Yes.

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
This is a feature (or rather, _{clarific,document}ation_) request.

**Which chart**:
- [stable/redis](https://github.com/helm/charts/blob/master/stable/redis)
- [stable/redis-ha](https://github.com/helm/charts/blob/master/stable/redis-ha)

**What happened**:
There are two seemingly redundant charts for Redis.

**What you expected to happen**:
One chart to rule them all... or documented rationale for maintaining both.

**Comment by ssalaues** [comment]
Tbh I would prefer only 1 as well. I'm bias towards the stable/redis-ha chart since that's more typical of what I would see in a production environment with sentinel management. However the stable/redis seems to have more features like metrics, NetworkPolicies, and more service configurations. Although I can't imagine these would be too difficult to port.

**Comment by juan131** [comment]
The charts are maintained by different people too. The **redis** is mantained by Bitnami while **Redis-ha** is mantained by Salim Salaues.

Now we're moving to distributed repositories, it should't be an issue anymore since there could be hundreds of charts for similar solutions. The only difference would be the people maintaining them and how reliable the charts are.

**Comment by ssalaues** [comment]
@juan131 what exactly do you mean when you say:

> we're moving to distributed repositories

Are the official Helm charts moving to new repositories?

**Comment by carrodher** [comment]
Yes, you can find more information in this blogpost:

https://helm.sh/blog/intro-helm-hub/index.html

But in summary, [Helm Hub](https://hub.helm.sh/) provides a means for you to find charts hosted in many distributed repositories (for example, via GitHub or Gitlab) hosted by different people and organizations.

**Comment by yurrriq** [comment]
I can't say I'm at all a fan of even further fragmentation, but my question's been answered. Thanks for the information and links.
