### ISSUE TITLE
[stable/spinnaker] Unusable, very high CPU usage, kubernetes goes unresponsive

### ISSUE THREAD

**Issue by rislah** [helm/charts#9217]
**Is this a request for help?**: Yes

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Version of Helm and Kubernetes**: Helm 2.11.0, Kubernetes 1.12.0

**Which chart**: stable/spinnaker

**What happened**: High CPU usage, kubernetes goes unresponsive. Unusable

**What you expected to happen**: Run at reasonable CPU usage and not crash kubernetes

**How to reproduce it** (as minimally and precisely as possible): helm install --name cd stable/spinnaker

**Anything else we need to know**: Chart is completely unusable. Tried it on minikube, thought it was some minikube issue, then deployed a cluster with vagrant using kubespray and still. CPU is ryzen 1700 on 8 cores and if I give the node 8 cores to use then it maxes my CPU out at ~70%. Kubernetes goes completely unresponsive, sometimes getting "the connection to :8443 was refused". Doing simple "kubectl get po" takes literally 3 minutes. Regardless of the memory or CPU cores I give its completely fucked. Minikube running on 8gb memory and 4 cores, on vagrant with cluster deployed by kubespray same. Never had such issue before. To get rid of it and have my system back I have to destroy the vagrant vm or with minikube stop the minikube, no other way as everything kubernetes related is unresponsive

**Comment by ChrisCooney** [comment]
Also having this issue on EKS running t2.medium instance types. The API was still responsive since EKS provides a highly available set of nodes that pods don't get deployed to, but the EC2 that the pods got deployed to died almost immediately and I had to manually terminate and destroy. Helm would time out.

Additionally, it looks like every single pod was scheduled onto one node. I'm not sure if you're setting resource requests in your helm chart but that might be welcome.

**Comment by GoingFast** [comment]
stale

**Comment by GoingFast** [comment]
stale

**Comment by brianlund** [comment]
I'm seeing something of the same running both t2.medium and t3.medium. Fresh spinnaker install on EKS. My pipeline (just a simple hello world pod) will trigger once or twice on push to github and then everything on the worker node grinds to a halt as cpu usage goes to +20. ps shows docker as the cause.
