### ISSUE TITLE
[stabel/jenkins]: how to enable jenkins debug

### ISSUE THREAD

**Issue by walthhy** [helm/charts#9573]
**Is this a request for help?**:
YES
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Version of Helm and Kubernetes**:
# kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:17:28Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:08:19Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

**Which chart**:
stable/jenkins

**What happened**:
python jenkinsapi doesn't work.

**What you expected to happen**:
enable debug message. now no message printed and 500 error was received by python jenkinsapi

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by maorfr** [comment]
Hey @walthhy,

Thanks for bringing this up!
As a first step, I would try to check if the remote access api works as expected, without the python package. Read these docs for more info:
https://wiki.jenkins.io/display/JENKINS/Remote+access+API

If the remote access api works - this is an issue for python api
If the remote access api does not work - this is an issue for jenkinsci/jenkins

In any case, this issue is probably not related to the chart, as it is working as far as I know.
