### ISSUE TITLE
[stable/redis-ha] do we still need a statefulset?

### ISSUE THREAD

**Issue by burnettk** [helm/charts#9944]
**Which chart**:

stable/redis-ha

**What**

stable/redis-ha uses a statefulset. With the large refactor in https://github.com/helm/charts/pull/7323, do we still need it? Sorry for the newb question, but statefulsets are way more annoying to deal with than deployments, and it seemed like some of the reasons for its existence may have gone away, but maybe not all? I was thinking you probably knew the answer to this question, @ssalaues . thanks!

**Comment by ssalaues** [comment]
Even before that refactor, there was a big push and several PRs that were trying to switch to stateful sets that got abandoned because of the review timeline (#7323 took over 2 months to get merged!) I was just carrying that torch and wrapped it up with additional changes.

But while Statefulsets may have different constraints than deployments, they also allow for more predictability (stable names) when dealing with things like trying to maintain a quorum or discovering other members. Before when it was still a deployment, the chart didn't support any persistence to disk and this was part of the big push to switch to Statefulsets. Other guarantees in Statefulsets are that they will handle the PVC creation for each pod and will not delete the PVCs automatically after a helm delete. Which means an accidental or even intentional delete of the chart will not delete your data.

More info on the guarantees over deployments that make sense for use with replicated databases:
https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#deployment-and-scaling-guarantees

Deployments on the other hand require a pvc definition for each pod and on helm delete of the chart, it would delete the PVC as well (Although steps can be taken to prevent this). This is why it's simpler to go with the more native StatefulSet.

https://github.com/helm/charts/blob/master/REVIEW_GUIDELINES.md#kubernetes-native-workloads

Hopefully that helps explain a bit more!
