### ISSUE TITLE
readinessprobe port setting is resolved as http://:http/status.php in my kube 

### ISSUE THREAD

**Issue by peidong-hu** [helm/charts#9989]
https://github.com/helm/charts/blob/de9118bb98690b6b454efb2da34c73d067a5664f/stable/owncloud/templates/deployment.yaml#L104

The kube version I have is 1.11

**Comment by carrodher** [comment]
As both issues https://github.com/helm/charts/issues/9988 and https://github.com/helm/charts/issues/9989 are practically the same, to avoid duplications, can discuss it here?

The [readinessProbe](https://github.com/helm/charts/blob/de9118bb98690b6b454efb2da34c73d067a5664f/stable/owncloud/templates/deployment.yaml#L104) and [livenessProbe](https://github.com/helm/charts/blob/de9118bb98690b6b454efb2da34c73d067a5664f/stable/owncloud/templates/deployment.yaml#L94) defined in `deployment.yaml` uses the following structure
```yaml
readinessProbe:
  httpGet:
  path: /status.php
    port: http
    httpHeaders:
    - name: Host
      value: {{ include "owncloud.host" . | quote }}
  initialDelaySeconds: 30
  timeoutSeconds: 3
  periodSeconds: 5
```

Where the line [`port: http`](https://github.com/helm/charts/blob/de9118bb98690b6b454efb2da34c73d067a5664f/stable/owncloud/templates/deployment.yaml#L107) is not a hardcoded value, it is a [variable defined some lines above](https://github.com/helm/charts/blob/de9118bb98690b6b454efb2da34c73d067a5664f/stable/owncloud/templates/deployment.yaml#L92):
```yaml
ports:
- name: http
  containerPort: 80
```
It is a common practice to use a named port: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/#use-a-named-port. We are using a similar approach in the `host`, including it from the template.

In your case, are you opening the issue because the readinessProbe/livenessProbe are failing or because you saw a weird value using `describe`? I mean, if you execute `kubectl describe pod` you can find different information related to the probes.
The most important one is the information in the `Events` section (at the end of the output), in this place you can find information related to the status of the probes, for example this is a failing probe:
```
Type     Reason                 Age                  From               Message
----     ------                 ----                 ----               -------
Warning  Unhealthy              3s (x6 over 3m23s)   kubelet, minikube  Readiness probe failed: Get http://172.17.0.8:80/status.php: dial tcp 172.17.0.8:80: getsockopt: connection refused
```
In the same way, the `kubectl describe pod` command also returns some information related to the pod, containers, etc; in this section you can find some data about the probes:
```
Liveness:   http-get http://:http/status.php delay=120s timeout=5s period=10s #success=1 #failure=6
Readiness:  http-get http://:http/status.php delay=30s timeout=5s period=10s #success=1 **#failure=6**
```
and here appears the weird syntax that you reported, but I think that this is not affecting how the probes works it because the defined values for the `port` and `host` are not properly render when `kubectl describe pod` shows the information.
